### ISSUE TITLE
Cocoapods can not install between Firebase/Core and Firebase/Analytics

### ISSUE THREAD

**Issue by peepo3663** [firebase/firebase-ios-sdk#10965]
### Description

Working on updating Firebase SDK to the latest version (current work used 7.11.0)

I found out that Pocspec between these 2 framework relay on mismatched versions.

FirebaseCore depends on Firebase Analytics (~> 10.6.0) which is correct while Firebase Analytics depends on Firebase Core (~> 10.0) which will not allow installing via Cocoapods

### Reproducing the issue

Install frameworks with `pod install`

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In snapshot (Podfile.lock):
    FirebaseCore (= 9.6.0, ~> 9.0)

  In Podfile:
    Firebase/Core (~> 10.6.0) was resolved to 10.6.0, which depends on
      FirebaseAnalytics (~> 10.6.0) was resolved to 10.6.0, which depends on
        FirebaseCore (~> 10.0)

Specs satisfying the `FirebaseCore (= 9.6.0, ~> 9.0), FirebaseCore (~> 10.0)` dependency were found, but they required a higher minimum deployment target.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
There may be an issue with the minimum iOS version specified in the Podfile. Firebase 10 requires at least iOS 11.

If you're still stuck, please share the Podfile.

**Comment by peepo3663** [comment]
Yes, My project's minimum iOS is iOS 12.0

Podfile
```
$firebase_version = '10.6.0'
$mlkits_version = '1.3.0'
$scandit_version = '6.16.1'
$scanbot_version = '3.5.0'
$mapbox_navigation_version = '2.11.0'
$appsflyer_version = '6.3.5'
$hypertrack_version = '4.14.0'

source 'https://github.com/CocoaPods/Specs.git'
workspace 'MyAppName'
use_frameworks!
inhibit_all_warnings!

def firebase_dependency_pods
  pod 'FirebaseUI'
  pod 'GTMSessionFetcher'
  pod 'GoogleToolboxForMac'
  pod 'GoogleUtilities'
end

def firebase_core_pods
  # pod 'FBSDKCoreKit'
  pod 'Firebase/Core', $firebase_version
  pod 'Firebase/Auth', $firebase_version
  pod 'Firebase/Performance', $firebase_version
  pod 'Firebase/RemoteConfig', $firebase_version
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/OAuth'
end

def firebase_pods
  pod 'Firebase/Messaging', $firebase_version
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Phone'
end

def mlkits_pods
  pod 'MLKitBarcodeScanning', $mlkits_version
  pod 'MLKitTextRecognition', $mlkits_version
end

def scandit_pods
  pod 'ScanditBarcodeCapture', $scandit_version
end

def scanbot_pods
  pod 'ScanbotBarcodeScannerSDK', $scanbot_version
end

def crashlytics_pods
  pod 'Firebase/Crashlytics', $firebase_version
end

def googlemap_pods
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end

def appsflyer_pods
  pod 'AppsFlyerFramework', $appsflyer_version
end

def mapbox_pods
  # pod 'Mapbox-iOS-SDK'
  # pod 'MapboxMobileEvents'
  pod 'MapboxNavigation', $mapbox_navigation_version
end

def here_pods
  # pod 'HEREMaps', '3.21.2.2'
  pod 'HEREMapsUI', :path => '../msdkui-ios/'
end

def util_pods
  #    pod 'AFNetworking'
  #    pod 'AFOAuth2Manager'
  #    pod 'APTimeZones'
  #    pod 'CHCSVParser'
  pod 'libPhoneNumber-iOS'
  #    pod 'KeychainAccess'
  pod 'KVOController'
  #    pod 'libextobjc'
  #    pod 'MASAttributes'
  #    pod 'NSData+Base64'
  pod 'SimpleKeychain'
  #    pod 'SwiftyXMLParser'
  #    pod 'XMLDictionary'
end

def ios_util_pods
  util_pods
  pod 'ReachabilitySwift'
  pod 'Validator'
end

def ios_location_pods
  pod 'HyperTrack', $hypertrack_version
end

def watch_util_pods
  util_pods
end

def tv_util_pods
  util_pods
  pod 'Validator'
end

def mac_util_pods
  util_pods
end

def uikit_pods
  pod 'Charts', '4.1.0'
  pod 'Differ'
  pod 'FormatterKit'
  #    pod 'GoogleMaps'
  pod 'ImageScrollView'
  #    pod 'MARKRangeSlider'
  pod 'Masonry'
  pod 'pop'
  #    pod 'PPBadgeView'
  pod 'RAGTextField'
  pod 'RDHCollectionViewGridLayout'
  pod 'SDWebImage'
  pod 'SwiftSignatureView'
  pod 'TTTAttributedLabel'
end

def ios_ui_pods
  ios_util_pods
  uikit_pods
  pod 'COSTouchVisualizer'
  pod 'DrawerMenu'
  pod 'DXCustomCallout-ObjC'
  pod 'FloatingPanel', '~> 1.7.6'
  pod 'HMSegmentedControl'
  pod 'iCarousel'
  pod 'JTCalendar'
  pod 'M13ProgressSuite', :git => 'https://github.com/beansai/M13ProgressSuite.git'
  pod 'NVActivityIndicatorView'
  pod 'SwiftMessages'
  pod 'TagStyledView'
  pod 'UIImage-Categories'
  pod 'PinCodeInputView'
end


def ios_map_ui_pods
  pod 'MKMapView-ZoomLevel'
  pod 'OCMapView'
end

def tomtom_ios_pods
  pod 'TomTomOnlineSDKMaps'
  pod 'TomTomOnlineSDKSearch'
  pod 'TomTomOnlineSDKRouting'
  pod 'TomTomOnlineSDKTraffic'
  pod 'TomTomOnlineSDKMapsUIExtensions'
  pod 'TomTomOnlineSDKMapsStaticImage'
  pod 'TomTomOnlineSDKDriving'
  pod 'TomTomOnlineSDKGeofencing'
end

def arcgis_pods
  pod 'ArcGIS-Runtime-SDK-iOS', '100.5'
end

abstract_target 'iOS' do
  platform :ios, '12.0'

  target 'Utilities' do
    project 'Utilities/Utilities'
    ios_util_pods
  end

  target 'UtilitiesTests' do
    project 'Utilities/Utilities'
    util_pods
  end

  target 'UIToolkits' do
    project 'UIToolkits/UIToolkits'
    uikit_pods
  end

  target 'UIToolkitsTests' do
    project 'UIToolkits/UIToolkits'
    uikit_pods
  end

  target 'UIAppToolkits' do
    project 'UIToolkits/UIToolkits'
    ios_ui_pods
  end
  
  target 'UIAppToolkitsTests' do
    project 'UIToolkits/UIToolkits'
    ios_ui_pods
  end

  target 'RoutingKit' do
    project 'RoutingKit/RoutingKit'
    util_pods
  end

  target 'RoutingKitTests' do
    project 'RoutingKit/RoutingKit'
    util_pods
  end

  target 'PlatformRouting' do
    project 'PlatformRouting/PlatformRouting'
    ios_ui_pods
  end

  target 'PlatformRoutingTests' do
    project 'PlatformRouting/PlatformRouting'
    ios_ui_pods
  end

  target 'ParticlesKit' do
    project 'ParticlesKit/ParticlesKit'
    util_pods
  end

  target 'ParticlesKitTests' do
    project 'ParticlesKit/ParticlesKit'
    util_pods
  end

  target 'ParticlesCommonModels' do
    project 'ParticlesCommonModels/ParticlesCommonModels'
    util_pods
  end

  target 'ParticlesCommonModelsTests' do
    project 'ParticlesCommonModels/ParticlesCommonModels'
    util_pods
  end

  target 'PlatformParticles' do
    project 'PlatformParticles/PlatformParticles'
    ios_ui_pods
  end

  target 'PlatformParticlesTests' do
    project 'PlatformParticles/PlatformParticles'
    ios_ui_pods
  end
  
  target 'MapParticles' do
    project 'MapParticles/MapParticles'
    ios_ui_pods
    ios_map_ui_pods
  end

  target 'MapParticlesTests' do
    project 'MapParticles/MapParticles'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'WebParticles' do
    project 'WebParticles/WebParticles'
    ios_ui_pods
  end

  target 'WebParticlesTests' do
    project 'WebParticles/WebParticles'
    ios_ui_pods
  end

  target 'JedioKit' do
    project 'JedioKit/JedioKit'
    ios_util_pods
  end
  
  target 'JedioKitTests' do
    project 'JedioKit/JedioKit'
    ios_util_pods
  end

  target 'PlatformJedio' do
    project 'PlatformJedio/PlatformJedio'
    ios_ui_pods
  end
  
  target 'PlatformJedioTests' do
    project 'PlatformJedio/PlatformJedio'
    ios_ui_pods
  end
  
  target 'FirebaseCoreStaticInjections' do
    project 'FirebaseStaticInjections/FirebaseStaticInjections'
    util_pods
    firebase_dependency_pods
    firebase_core_pods
    crashlytics_pods
  end
  
  target 'FirebaseStaticInjections' do
    project 'FirebaseStaticInjections/FirebaseStaticInjections'
    util_pods
    firebase_dependency_pods
    firebase_pods
    mlkits_pods
  end
  
  target 'FirebaseStaticInjectionsTests' do
    project 'FirebaseStaticInjections/FirebaseStaticInjections'
    util_pods
    firebase_dependency_pods
    firebase_pods
    mlkits_pods
  end
  
  target 'ScanditInjections' do
    project 'ScanditInjections/ScanditInjections'
    util_pods
    scandit_pods
  end

  target 'ScanditInjectionsTests' do
    project 'ScanditInjections/ScanditInjections'
    util_pods
    scandit_pods
  end

  <<-DOC
  Scanbot target
  DOC
  target 'ScanbotInjections' do
    project 'ScanbotInjections/ScanbotInjections'
    util_pods
    scanbot_pods
  end

  target 'ScanbotInjectionsTests' do
    project 'ScanbotInjections/ScanbotInjections'
    util_pods
    scanbot_pods
  end
  
  target 'GoogleMapStaticInjections' do
    project 'GoogleMapStaticInjections/GoogleMapStaticInjections'
    util_pods
    googlemap_pods
  end
  
  
  target 'GoogleMapStaticInjectionsTests' do
    project 'GoogleMapStaticInjections/GoogleMapStaticInjections'
    util_pods
    googlemap_pods
  end
  
  # target 'HEREInjections' do
  #   project 'HEREInjections/HEREInjections'
  #   util_pods
  #   # here_pods
  #   uikit_pods
  # end
  
  
  # target 'HEREInjectionsTests' do
  #   project 'HEREInjections/HEREInjections'
  #   util_pods
  #   # here_pods
  # end
  
# target 'MapboxInjections' do
#  project 'MapboxInjections/MapboxInjections'
#  util_pods
#  ios_ui_pods
#  mapbox_pods
# end
  
  
#  target 'MapboxInjectionsTests' do
#    project 'MapboxInjections/MapboxInjections'
#    util_pods
#    mapbox_pods
#  end

  target 'HyperTrackInjections' do
    project 'HyperTrackInjections/HyperTrackInjections'
    ios_location_pods
  end
  
  
  target 'HyperTrackInjectionsTests' do
    project 'HyperTrackInjections/HyperTrackInjections'
    ios_location_pods
  end
  
  target 'AppsFlyerStaticInjections' do
    project 'AppsFlyerStaticInjections/AppsFlyerStaticInjections'
    util_pods
    appsflyer_pods
  end
  
  target 'BeansCommonModels' do
    project 'BeansCommonModels/BeansCommonModels'
    util_pods
  end
  
  target 'BeansCommonModelsTests' do
    project 'BeansCommonModels/BeansCommonModels'
    util_pods
  end
  
  target 'BeansCommonPlatformParticles' do
    project 'BeansCommonPlatformParticles/BeansCommonPlatformParticles'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'BeansCommonPlatformParticlesTests' do
    project 'BeansCommonPlatformParticles/BeansCommonPlatformParticles'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'BeansMapperModels' do
    project 'BeansMapperModels/BeansMapperModels'
    util_pods
  end
  
  target 'BeansMapperModelsTests' do
    project 'BeansMapperModels/BeansMapperModels'
    util_pods
  end
  
  target 'BeansMapperPlatformParticles' do
    project 'BeansMapperPlatformParticles/BeansMapperPlatformParticles'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'BeansMapperPlatformParticlesTests' do
    project 'BeansMapperPlatformParticles/BeansMapperPlatformParticles'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'BeansMapperUI' do
    project 'BeansMapperUI/BeansMapperUI'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'BeansMapperUITests' do
    project 'BeansMapperUI/BeansMapperUI'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'Beans Mapper' do
    project 'Beans Mapper/Beans Mapper'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    crashlytics_pods
    firebase_core_pods
    firebase_pods
    # scandit_pods
    # scanbot_pods
    googlemap_pods
    appsflyer_pods
  end
  
  target 'Beans MapperTests' do
    project 'Beans Mapper/Beans Mapper'
    pod 'iOSSnapshotTestCase'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    firebase_core_pods
    firebase_pods
    # scandit_pods
    # scanbot_pods
    appsflyer_pods
  end
  
  target 'BeansNavigatorModels' do
    project 'BeansNavigatorModels/BeansNavigatorModels'
    util_pods
  end
  
  target 'BeansNavigatorModelsTests' do
    project 'BeansNavigatorModels/BeansNavigatorModels'
    util_pods
  end
  
  target 'BeansNavigatorPlatformParticles' do
    project 'BeansNavigatorPlatformParticles/BeansNavigatorPlatformParticles'
    ios_ui_pods
    ios_map_ui_pods
    mapbox_pods
    scandit_pods
    scanbot_pods
  end
  
  target 'BeansNavigatorPlatformParticlesTests' do
    project 'BeansNavigatorPlatformParticles/BeansNavigatorPlatformParticles'
    ios_ui_pods
    ios_map_ui_pods
    scandit_pods
    scanbot_pods
  end
  
  target 'BeansNavigatorUI' do
    project 'BeansNavigatorUI/BeansNavigatorUI'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'BeansNavigatorUITests' do
    project 'BeansNavigatorUI/BeansNavigatorUI'
    ios_ui_pods
    ios_map_ui_pods
  end
  
  target 'Beans Navigator' do
    project 'Beans Navigator/Beans Navigator'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    crashlytics_pods
    firebase_core_pods
    firebase_pods
    googlemap_pods
    mapbox_pods
    #here_pods
    appsflyer_pods
    ios_location_pods
    # scandit_pods
    # scanbot_pods
  end
  
  target 'Beans NavigatorTests' do
    project 'Beans Navigator/Beans Navigator'
    pod 'iOSSnapshotTestCase'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    firebase_core_pods
    firebase_pods
    # scandit_pods
    # scanbot_pods
    appsflyer_pods
    ios_location_pods
  end
  
  target 'Beans Tour' do
    project 'Beans Navigator/Beans Navigator'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    crashlytics_pods
    firebase_core_pods
    firebase_pods
    # scandit_pods
    # scanbot_pods
    googlemap_pods
    mapbox_pods
    #here_pods
    appsflyer_pods
    ios_location_pods
  end
  
  target 'Beans TourTests' do
    project 'Beans Navigator/Beans Navigator'
    pod 'iOSSnapshotTestCase'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    firebase_core_pods
    firebase_pods
    # scandit_pods
    # scanbot_pods
    appsflyer_pods
    ios_location_pods
  end
  
  target 'Beans Maps Clip' do
    project 'Beans Navigator/Beans Navigator'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    crashlytics_pods
    firebase_core_pods
  end
  
  target 'Beans Maps ClipTests' do
    project 'Beans Navigator/Beans Navigator'
    pod 'iOSSnapshotTestCase'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    firebase_core_pods
  end
  
  target 'Beans Delivery' do
    project 'Beans Navigator/Beans Navigator'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    crashlytics_pods
    firebase_core_pods
    firebase_pods
    mlkits_pods
    # scandit_pods
    # scanbot_pods
    googlemap_pods
    mapbox_pods
    #here_pods
    appsflyer_pods
    ios_location_pods
  end
  
  target 'Beans DeliveryTests' do
    project 'Beans Navigator/Beans Navigator'
    pod 'iOSSnapshotTestCase'
    ios_ui_pods
    ios_map_ui_pods
    firebase_dependency_pods
    firebase_core_pods
    firebase_pods
    mlkits_pods
    # scandit_pods
    # scanbot_pods
    appsflyer_pods
    ios_location_pods
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings['SWIFT_VERSION'] = '5.0'
            # Need for M1
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            # Need for Xcode 14
            config.build_settings["DEVELOPMENT_TEAM"] = "MY DEVELOPMENT ID"
          end
      end
  end
end
```

**Comment by paulb777** [comment]
GoogleMLKit was not compatible with Firebase 10.x until today's release of GoogleMLKit. 

The `Podfile.lock` file should explain why different versions are chosen. Please share that as well.

**Comment by peepo3663** [comment]
@paulb777 Actually, In my current work, I bumped MLKitBarcode Scanning to `2.2.0` and Text Recognition to `1.4.0`. In addition, It can not be installed, so `Podfile.lock` can not contained any information at all.

What if you guys update Podspec of `FirebaseAnalytics` to depends on `FirebaseCode` `~> 10.6.0`, It would solve this issues of dependencies.

**Comment by paulb777** [comment]
FirebaseAnalytics 10.x requires FirebaseCore 10.x.

Where is the dependency on FirebaseCore version 9.6.0 coming from?

**Comment by peepo3663** [comment]
@paulb777 

Even I removed the Podlife.lock it still did not work, however, I finally made this installed by updating each dependency like `FirebaseAuth` directly not `Firebase/Auth`. You can close this issue. I can install it with `10.7.0`

On the other hand, I still can not install 10.7.0 firebase SDKs with GoogleMLKits 3.2.0 due to `GTMSessionFetcher/Core`

```shell
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    FirebaseUI (= 12.3.0) was resolved to 12.3.0, which depends on
      FirebaseUI/Anonymous (= 12.3.0) was resolved to 12.3.0, which depends on
        FirebaseAnonymousAuthUI (~> 12.0) was resolved to 12.3.0, which depends on
          FirebaseAuth (< 11.0, >= 8.0) was resolved to 10.7.0, which depends on
            GTMSessionFetcher/Core (< 4.0, >= 2.1)

    FirebaseUI/Google was resolved to 12.3.0, which depends on
      FirebaseGoogleAuthUI (~> 12.0) was resolved to 12.3.0, which depends on
        GoogleSignIn (~> 6.0) was resolved to 6.2.4, which depends on
          GTMAppAuth (~> 1.3) was resolved to 1.3.1, which depends on
            GTMSessionFetcher/Core (< 3.0, >= 1.5)

    FirebaseUI/Google was resolved to 12.3.0, which depends on
      FirebaseGoogleAuthUI (~> 12.0) was resolved to 12.3.0, which depends on
        GoogleSignIn (~> 6.0) was resolved to 6.2.4, which depends on
          GTMSessionFetcher/Core (< 3.0, >= 1.1)

    GoogleMLKit/TextRecognition (= 3.2.0) was resolved to 3.2.0, which depends on
      MLKitTextRecognition (~> 1.4.0-beta6) was resolved to 1.4.0-beta6, which depends on
        MLKitCommon (~> 8.0) was resolved to 8.0.0, which depends on
          GTMSessionFetcher/Core (~> 1.1)
```

**Comment by paulb777** [comment]
This issue is resolved with MLKitCommon 9.0.0, MLKitTextRecognition 2.0.0 and GoogleMLKit 4.0.0: 
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing ARCore (1.36.0)
Installing AppAuth (1.6.0)
Installing Base64 (1.1.2)
Installing BoringSSL-GRPC (0.0.24)
Installing DigitsMigrationHelper (0.3.0)
Installing EarlGrey (1.16.0)
Installing Firebase (10.8.0)
Installing FirebaseABTesting (10.8.0)
Installing FirebaseAnalytics (10.8.0)
Installing FirebaseAppCheckInterop (10.8.0)
Installing FirebaseAppDistribution (10.8.0-beta)
Installing FirebaseAuth (10.8.0)
Installing FirebaseAuthInterop (10.8.0)
Installing FirebaseCore (10.8.0)
Installing FirebaseCoreExtension (10.8.0)
Installing FirebaseCoreInternal (10.8.0)
Installing FirebaseCrashlytics (10.8.0)
Installing FirebaseDatabase (10.8.0)
Installing FirebaseDynamicLinks (10.8.0)
Installing FirebaseFirestore (10.8.0)
Installing FirebaseFunctions (10.8.0)
Installing FirebaseInAppMessaging (10.8.0-beta)
Installing FirebaseInstallations (10.8.0)
Installing FirebaseMessaging (10.8.0)
Installing FirebaseMessagingInterop (10.8.0)
Installing FirebasePerformance (10.8.0)
Installing FirebaseRemoteConfig (10.8.0)
Installing FirebaseSessions (10.8.0)
Installing FirebaseSharedSwift (10.8.0)
Installing FirebaseStorage (10.8.0)
Installing GTMAppAuth (2.0.0)
Installing GTMSessionFetcher (2.3.0)
Installing Google-Mobile-Ads-SDK (10.2.0)
Installing GoogleAnalytics (3.21.0)
Installing GoogleAppIndexing (2.0.3)
Installing GoogleAppMeasurement (10.8.0)
Installing GoogleAppUtilities (1.1.2)
Installing GoogleAuthUtilities (2.0.2)
Installing GoogleConversionTracking (3.4.0)
Installing GoogleDataTransport (9.2.1)
Installing GoogleIDFASupport (3.14.0)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleMLKit (4.0.0)
Installing GoogleMaps (3.1.0)
Installing GoogleNetworkingUtilities (1.2.2)
Installing GoogleParsingUtilities (1.1.2)
Installing GooglePlacePicker (3.1.0)
Installing GooglePlaces (3.1.0)
Installing GooglePlusUtilities (1.1.2)
Installing GoogleSignIn (7.0.0)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleTagManager (7.4.3)
Installing GoogleToolboxForMac (2.3.2)
Installing GoogleUserMessagingPlatform (2.0.1)
Installing GoogleUtilities (7.11.0)
Installing GoogleUtilitiesComponents (1.1.0)
Installing JWT (2.2.0)
Installing Libuv-gRPC (0.0.10)
Installing MLImage (1.0.0-beta4)
Installing MLKitCommon (9.0.0)
Installing MLKitTextRecognition (2.0.0)
Installing MLKitTextRecognitionCommon (1.0.0)
Installing MLKitVision (5.0.0)
Installing PromisesObjC (2.2.0)
Installing PromisesSwift (2.2.0)
Installing Protobuf (3.22.1)
Installing abseil (1.20211102.0)
Installing gRPC-C++ (1.44.0)
Installing gRPC-Core (1.44.0)
```

**Comment by peepo3663** [comment]
Thank you for the clarification about GoogleMLKit 4.0.0. I do not know about this because in the Google ML Kits [Website](https://developers.google.com/ml-kit/release-notes)

It still showed as `3.2.0`
