### ISSUE TITLE
pb_check_proto3_default_value EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)

### ISSUE THREAD

**Issue by AhmedShanab74** [firebase/firebase-ios-sdk#12632]
### Description

Released app version 2.0.12 on 3/26 using Xcode 15.3,  Encountered a critical crash issue on the same day , reported via Firebase

Environments:
Xcode version: Xcode 15.3 
macOS version: macOS Sonoma 14.3.1 
Firebase version: Firebase(10.20.0)

### Reproducing the issue

i have update firebase to version 10.20.0  and upload app to app store , when user try to  update the app from app store app     crash  
i also update firebase to 10.22.0 and have the same issue 

<img width="1384" alt="img_1" src="https://github.com/firebase/firebase-ios-sdk/assets/128382748/834a0b48-ec23-4289-b2eb-34cad2cdbc94">
<img width="1048" alt="img_2" src="https://github.com/firebase/firebase-ios-sdk/assets/128382748/6cac854f-8eb0-4dd2-ac8c-9120c98fcd59">

### Firebase SDK Version

10.20.0 and i update to 10.22.0

### Xcode Version

15.3 

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Crashed: com.apple.main-thread
0  nanopb                         0x6904 pb_check_proto3_default_value + 342
1  nanopb                         0x6074 pb_encode + 172
2  FirebaseSessions               0x413c FIRSESEncodeProto + 64
3  FirebaseSessions               0xf04c $s16FirebaseSessions17SessionStartEventC14transportBytes10Foundation4DataVyF + 232
4  FirebaseSessions               0xf2d4 $s16FirebaseSessions17SessionStartEventC14transportBytes10Foundation4DataVyFTo + 28
5  GoogleDataTransport            0xdfac -[GDTCOREvent setDataObject:] + 68
6  GoogleDataTransport            0xde3c -[GDTCOREvent copy] + 72
7  GoogleDataTransport            0x1b000 -[GDTCORTransport sendEvent:onComplete:] + 44
8  FirebaseSessions               0xa834 $sSo15GDTCORTransportC16FirebaseSessions27GoogleDataTransportProtocolA2cDP11logGDTEvent5event10completionySo11GDTCOREventC_ys6ResultOyyts5Error_pGctFTW + 176
9  FirebaseSessions               0x5ec0 $s16FirebaseSessions14EventGDTLoggerC03logC05event10completionyAA012SessionStartC0C_ys6ResultOyyts5Error_pGctF + 224
10 FirebaseSessions               0x5f44 $s16FirebaseSessions14EventGDTLoggerCAA0cD8ProtocolA2aDP03logC05event10completionyAA012SessionStartC0C_ys6ResultOyyts5Error_pGctFTW + 20
11 FirebaseSessions               0xd1c4 $s16FirebaseSessions18SessionCoordinatorC014attemptLoggingC5Start5event8callbackyAA0cG5EventC_ys6ResultOyytAA0aB5ErrorOGctFyAMcfU_ + 176
12 FirebaseSessions               0xd3c4 $s16FirebaseSessions18SessionCoordinatorC10fillInFIID33_A99E81F187A7BA47A5374F4DC053A423LL5event8callbackyAA0C10StartEventC_ys6ResultOyytAA0aB5ErrorOGctFyAKySSs0V0_pGcfU_ + 180
13 FirebaseSessions               0xabe4 $sSo16FIRInstallationsC16FirebaseSessionsE14installationID10completionyys6ResultOySSs5Error_pGc_tFySSSg_sAH_pSgtcfU_TA + 48
14 FirebaseSessions               0xaaa8 $sSSSgs5Error_pSgIeggg_So8NSStringCSgSo7NSErrorCSgIeyByy_TR + 96
15 FirebaseInstallations          0x49bc __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 56
16 FBLPromises                    0x5130 __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 52
17 libdispatch.dylib              0x26a8 <redacted> + 32
18 libdispatch.dylib              0x4300 <redacted> + 20
19 libdispatch.dylib              0x129e0 <redacted> + 1056
20 libdispatch.dylib              0x125b0 _dispatch_main_queue_callback_4CF + 44
21 CoreFoundation                 0x36f9c <redacted> + 16
22 CoreFoundation                 0x33ca8 <redacted> + 1996
23 CoreFoundation                 0x333f8 CFRunLoopRunSpecific + 608
24 GraphicsServices               0x34f8 GSEventRunModal + 164
25 UIKitCore                      0x22c8a0 <redacted> + 888
26 UIKitCore                      0x22bedc UIApplicationMain + 340
27 MyApp                       0x10a910 main + 39 (AppDelegate.swift:39)
28 ???                            0x1b5cfadcc (Missing)
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

PODS:
  - Adjust (4.38.0):
    - Adjust/Core (= 4.38.0)
  - Adjust/Core (4.38.0)
  - Alamofire (5.9.0)
  - AlamofireEasyLogger (1.6.0):
    - Alamofire (>= 5.0)
  - AlgoliaSearchClient (8.18.2):
    - Logging
  - AlignedCollectionViewFlowLayout (1.1.2)
  - BadgeHub (1.0.0)
  - BEMCheckBox (1.4.1)
  - Cosmos (23.0.0)
  - CountryPickerView (3.3.0)
  - DropDown (2.3.13)
  - DynamicBlurView (4.1.0)
  - Firebase/CoreOnly (10.22.0):
    - FirebaseCore (= 10.22.0)
  - Firebase/Crashlytics (10.22.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.22.0)
  - Firebase/InAppMessaging (10.22.0):
    - Firebase/CoreOnly
    - FirebaseInAppMessaging (~> 10.22.0-beta)
  - Firebase/Messaging (10.22.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.22.0)
  - Firebase/RemoteConfig (10.22.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 10.22.0)
  - FirebaseABTesting (10.23.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCore (10.22.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.23.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.23.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.22.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInAppMessaging (10.22.0-beta):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseInstallations (10.23.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.22.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.22.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - FirebaseSharedSwift (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseSessions (10.23.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.23.0)
  - FittedSheets (1.4.5)
  - FSPagerView (0.8.3)
  - GoogleDataTransport (9.4.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - ImageSlideshow (1.9.2):
    - ImageSlideshow/Core (= 1.9.2)
  - ImageSlideshow/Core (1.9.2)
  - ImageSlideshow/Kingfisher (1.9.2):
    - ImageSlideshow/Core
    - Kingfisher (> 3.0)
  - InstantSearch (7.26.1):
    - InstantSearch/UI (= 7.26.1)
  - InstantSearch/Core (7.26.1):
    - AlgoliaSearchClient (~> 8.18)
    - InstantSearch/Insights
    - InstantSearchTelemetry (~> 0.1.3)
  - InstantSearch/Insights (7.26.1):
    - AlgoliaSearchClient (~> 8.18)
  - InstantSearch/UI (7.26.1):
    - InstantSearch/Core
  - InstantSearchTelemetry (0.1.3):
    - SwiftProtobuf (~> 1.20)
  - IQKeyboardManagerSwift (7.0.2)
  - Kingfisher (7.6.2)
  - LinearProgressBar (1.0.2)
  - Logging (1.4.0)
  - lottie-ios (3.4.4)
  - MOLH (1.4.3)
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - NVActivityIndicatorView (4.4.0):
    - NVActivityIndicatorView/Presenter (= 4.4.0)
  - NVActivityIndicatorView/Presenter (4.4.0)
  - OneSignal (2.16.7)
  - OneSignalXCFramework (3.12.9):
    - OneSignalXCFramework/OneSignalCore (= 3.12.9)
    - OneSignalXCFramework/OneSignalExtension (= 3.12.9)
    - OneSignalXCFramework/OneSignalOutcomes (= 3.12.9)
  - OneSignalXCFramework/OneSignalCore (3.12.9)
  - OneSignalXCFramework/OneSignalExtension (3.12.9):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalOutcomes
  - OneSignalXCFramework/OneSignalOutcomes (3.12.9):
    - OneSignalXCFramework/OneSignalCore
  - PayPalCheckout (0.112.2)
  - PopupDialog (1.1.1):
    - DynamicBlurView (~> 4.0)
  - Presentr (1.9)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - RSKPlaceholderTextView (8.0.0)
  - RxCocoa (6.6.0):
    - RxRelay (= 6.6.0)
    - RxSwift (= 6.6.0)
  - RxRelay (6.6.0):
    - RxSwift (= 6.6.0)
  - RxSwift (6.6.0)
  - SkyFloatingLabelTextField (4.0.0)
  - SMLocalize (0.5.1)
  - SwiftLuhn (1.0.0)
  - SwiftMessages (9.0.6):
    - SwiftMessages/App (= 9.0.6)
  - SwiftMessages/App (9.0.6)
  - SwiftProtobuf (1.25.2)
  - SwiftyUserDefaults (4.0.0)
  - Toast-Swift (5.1.0)

DEPENDENCIES:
  - Adjust
  - Alamofire
  - AlamofireEasyLogger
  - AlignedCollectionViewFlowLayout
  - BadgeHub
  - BEMCheckBox
  - Cosmos (~> 23.0)
  - CountryPickerView
  - DropDown
  - Firebase/Crashlytics (~> 10.22.0)
  - Firebase/InAppMessaging (~> 10.22.0)
  - Firebase/Messaging (~> 10.22.0)
  - Firebase/RemoteConfig (~> 10.22.0)
  - FittedSheets (= 1.4.5)
  - FSPagerView (~> 0.8.3)
  - ImageSlideshow
  - ImageSlideshow/Kingfisher
  - InstantSearch (~> 7.16)
  - IQKeyboardManagerSwift
  - Kingfisher (~> 7.6.1)
  - LinearProgressBar
  - lottie-ios (~> 3.4.3)
  - MOLH
  - NVActivityIndicatorView (= 4.4.0)
  - OneSignal (< 3.0, >= 2.11.2)
  - OneSignalXCFramework (< 4.0, >= 3.0.0)
  - PayPalCheckout (~> 0.112.2)
  - PopupDialog
  - Presentr
  - RSKPlaceholderTextView
  - RxCocoa
  - RxSwift
  - SkyFloatingLabelTextField
  - SMLocalize
  - SwiftLuhn
  - SwiftMessages (= 9.0.6)
  - SwiftyUserDefaults (~> 4.0.0)
  - Toast-Swift

SPEC REPOS:
  trunk:
    - Adjust
    - Alamofire
    - AlamofireEasyLogger
    - AlgoliaSearchClient
    - AlignedCollectionViewFlowLayout
    - BadgeHub
    - BEMCheckBox
    - Cosmos
    - CountryPickerView
    - DropDown
    - DynamicBlurView
    - Firebase
    - FirebaseABTesting
    - FirebaseCore
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInAppMessaging
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfig
    - FirebaseSessions
    - FirebaseSharedSwift
    - FittedSheets
    - FSPagerView
    - GoogleDataTransport
    - GoogleUtilities
    - ImageSlideshow
    - InstantSearch
    - InstantSearchTelemetry
    - IQKeyboardManagerSwift
    - Kingfisher
    - LinearProgressBar
    - Logging
    - lottie-ios
    - MOLH
    - nanopb
    - NVActivityIndicatorView
    - OneSignal
    - OneSignalXCFramework
    - PayPalCheckout
    - PopupDialog
    - Presentr
    - PromisesObjC
    - PromisesSwift
    - RSKPlaceholderTextView
    - RxCocoa
    - RxRelay
    - RxSwift
    - SkyFloatingLabelTextField
    - SMLocalize
    - SwiftLuhn
    - SwiftMessages
    - SwiftProtobuf
    - SwiftyUserDefaults
    - Toast-Swift

SPEC CHECKSUMS:
  Adjust: c98d85594a746ff9f2bafe424c5beb6db66cd6a8
  Alamofire: 02b772c9910e8eba1a079227c32fbd9e46c90a24
  AlamofireEasyLogger: f2fd10b57d973593a79a4b61f274c6a5cb3e1333
  AlgoliaSearchClient: dd74cf9fc8c9ccb4145b77b435945068dcd4ce50
  AlignedCollectionViewFlowLayout: ee2ef451e741ec08f8e0967d828001e2f051c20a
  BadgeHub: b227771329f78c37a2dae7502607ec6d00a50bd4
  BEMCheckBox: 5ba6e37ade3d3657b36caecc35c8b75c6c2b1a4e
  Cosmos: b5c6a9a637e28a061b54c8f8b1d8529d7d4db73f
  CountryPickerView: 6322ada32a80b0cd721b0267282a5c24f406f263
  DropDown: 8a2116376c1981888557f72ec2ffc9a5e0e456ec
  DynamicBlurView: 58e18fae80bb614e34681a4486870e7d257b62e8
  Firebase: 797fd7297b7e1be954432743a0b3f90038e45a71
  FirebaseABTesting: aec61ed9a34d85a95e2013a3fdf051426a2419df
  FirebaseCore: 0326ec9b05fbed8f8716cddbf0e36894a13837f7
  FirebaseCoreExtension: cb88851781a24e031d1b58e0bd01eb1f46b044b5
  FirebaseCoreInternal: 6a292e6f0bece1243a737e81556e56e5e19282e3
  FirebaseCrashlytics: e568d68ce89117c80cddb04073ab9018725fbb8c
  FirebaseInAppMessaging: bff8ac490bba54c298b48847e14bd56313d2da1b
  FirebaseInstallations: 42d6ead4605d6eafb3b6683674e80e18eb6f2c35
  FirebaseMessaging: 9f71037fd9db3376a4caa54e5a3949d1027b4b6e
  FirebaseRemoteConfig: e1b992a94d3674dddbcaf5d0d31a0312156ceb1c
  FirebaseSessions: f06853e30f99fe42aa511014d7ee6c8c319f08a3
  FirebaseSharedSwift: c92645b392db3c41a83a0aa967de16f8bad25568
  FittedSheets: 7f754c9f6fb4ea330cbc57c652b594255f2a6819
  FSPagerView: 670405b2f18e2a87fa37f20b00de783e562c25a8
  GoogleDataTransport: 6c09b596d841063d76d4288cc2d2f42cc36e1e2a
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  ImageSlideshow: be305b54eaf2b2cfc7a7141c7c734605d44dc07d
  InstantSearch: dfa1e71207059951d40aefc8e981bcf6199a5c27
  InstantSearchTelemetry: e1ea763a63ad2db96b4f5e8bc4cd4cc1147274b9
  IQKeyboardManagerSwift: d338c11a896e9f29603443700c4567e32f830c22
  Kingfisher: 6c5449c6450c5239166510ba04afe374a98afc4f
  LinearProgressBar: 619d6f286b608e501f39406557f60cdab3faf910
  Logging: beeb016c9c80cf77042d62e83495816847ef108b
  lottie-ios: 8f97d3271e155c2d688875c29cd3c74908aef5f8
  MOLH: e45827d200aeb1310641090fd8cd03ad2b42ae72
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  NVActivityIndicatorView: ec7440a57af2450319d3a4181cca7da6fc127064
  OneSignal: 67a3cf1d1edf2a9c22ba846e8d2eee2bf8cdb525
  OneSignalXCFramework: 3c3ef25ecca5eae1bf80a3272c49fd1dbab96b35
  PayPalCheckout: 9ecb796c36f899426bb2e10aec08cd236b5f022e
  PopupDialog: 720c92befd8bc23c13442254945213db5612f149
  Presentr: 7078d7eb5d1661ebeaae60c9e42a1e534de1b993
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  RSKPlaceholderTextView: 85cb165bfbfe160a2e7bfb6bcd77a21100ce1b52
  RxCocoa: 44a80de90e25b739b5aeaae3c8c371a32e3343cc
  RxRelay: 45eaa5db8ee4fb50e5ebd57deec0159e97fa51e6
  RxSwift: a4b44f7d24599f674deebd1818eab82e58410632
  SkyFloatingLabelTextField: 79ddc40e4ad59707fedbb48d605417aee48bb78a
  SMLocalize: 8e64c09714627d5537225bff8be464e965230859
  SwiftLuhn: 20ec3fe2b00699f5b2867c0133236722b05b902d
  SwiftMessages: f0c7ef4705a570ad6c5e208b611f4333e660ed92
  SwiftProtobuf: 407a385e97fd206c4fbe880cc84123989167e0d1
  SwiftyUserDefaults: 6a1951df1daa19337862b677dd9a4b9bd4c288cd
  Toast-Swift: dd369e68ee529f542c65bd0d0c6c50cd743cf6f2

PODFILE CHECKSUM: 48d1d769c18cf6740ff4839cf358d79525a20c7e

COCOAPODS: 1.12.1

**Comment by paulb777** [comment]
Please confirm that you're reproducing with 10.22.0 or 10.23.0. 

This is exactly the bug (#11403) that was fixed for several others with those releases.

**Comment by AhmedShanab74** [comment]
hello @paulb777  i update Firebase to 10.23.0 
and still have the same crash 
the crash happened when i start downloading the app 
My Podfile.lock
 - Firebase/CoreOnly (10.23.0):
    - FirebaseCore (= 10.23.0)
  - Firebase/Crashlytics (10.23.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 10.23.0)
  - Firebase/InAppMessaging (10.23.0):
    - Firebase/CoreOnly
    - FirebaseInAppMessaging (~> 10.23.0-beta)
  - Firebase/Messaging (10.23.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 10.23.0)
  - Firebase/RemoteConfig (10.23.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 10.23.0)
  - FirebaseABTesting (10.23.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCore (10.23.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreExtension (10.23.0):
    - FirebaseCore (~> 10.0)
  - FirebaseCoreInternal (10.23.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseCrashlytics (10.23.0):
    - FirebaseCore (~> 10.5)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSessions (~> 10.5)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesObjC (~> 2.1)
  - FirebaseInAppMessaging (10.23.0-beta):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseInstallations (10.23.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - FirebaseMessaging (10.23.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.8)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Reachability (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseRemoteConfig (10.23.0):
    - FirebaseABTesting (~> 10.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - FirebaseRemoteConfigInterop (~> 10.23)
    - FirebaseSharedSwift (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseRemoteConfigInterop (10.23.0)
  - FirebaseSessions (10.23.0):
    - FirebaseCore (~> 10.5)
    - FirebaseCoreExtension (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleDataTransport (~> 9.2)
    - GoogleUtilities/Environment (~> 7.10)
    - nanopb (< 2.30911.0, >= 2.30908.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (10.23.0)

https://github.com/firebase/firebase-ios-sdk/assets/128382748/0dd27c26-b55f-4c21-ad60-af8b5e291d28

**Comment by paulb777** [comment]
Are you able to reproduce locally building in Xcode? Does it make a difference to build for Debug or to build for Release?

**Comment by AhmedShanab74** [comment]
when i run the version 2.0.12 from xcode it works fine without crashes

**Comment by paulb777** [comment]
OK, we'll need a crash in a reproducible example built with Firebase 10.23.0 to make progress here.

**Comment by AhmedShanab74** [comment]
hi @paulb777  
users have an old version of the app 2.0.11 when they open the app an popup appears tell them they need to force update the app , the version on app store is 2.0.12 when they download it the app crash 
these screen shots are from Crashlytics dashboard of the app 
here the url of the app on store ==>>  https://apps.apple.com/eg/app/marasi-shopping-%D9%85%D8%B1%D8%A7%D8%B3%D9%8A-%D9%84%D9%84%D8%AA%D8%B3%D9%88%D9%82/id1476963784?l=ar

<img width="1703" alt="img-1" src="https://github.com/firebase/firebase-ios-sdk/assets/128382748/cedf80d2-6f27-463f-a5ef-f35cc9cc4178">
<img width="1703" alt="img-2" src="https://github.com/firebase/firebase-ios-sdk/assets/128382748/0bdfc146-400d-4a04-82f9-bde44aa2434f">
<img width="1703" alt="img-3" src="https://github.com/firebase/firebase-ios-sdk/assets/128382748/25e013ce-b230-4bcb-89fd-9a082660d8c0">

**Comment by AhmedShanab74** [comment]
@paulb777  notice that all crashes happened in ios 17

**Comment by AhmedShanab74** [comment]
@paulb777  i upload a new version to app store and it rejected because it crash on launch , 
even i install Firebase 10.23.0

**Comment by fee-dev** [comment]
I encountered the same issue where I'm unable to publish my app live because it crashes on the device when I'm testing and downloading a new version from TestFlight.

**Comment by AhmedShanab74** [comment]
@fee-dev  Did the same problem occur with  Firebase 10.23.0 ?

**Comment by ram-vilash** [comment]
After updating the firebase version it is still crashing in iOS 17

**Comment by guperini** [comment]
Same issue here. The app crashes in the first session after update.

**Comment by paulb777** [comment]
I'm going to close and lock this issue. 

This bug (https://github.com/firebase/firebase-ios-sdk/issues/11403) was fixed in Firebase 10.22.0. If you have this problem in a newer version, please open a new issue with the template fully completed.
