### ISSUE TITLE
LOGS & breadcrumbs view in firebase console are empty

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#13167]
### Description

Since 2 days ago I cannot see logs& breadcrumbs in firebase console. I don't know if this is because the SDK or it is because an error on the firebase console. 
Version 10.25.0

### Screenshot

<img width="641" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/85997060/55b15447-ab7a-4fce-8efd-16c991c3b98a">

### Firebase SDK Version

10.25.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS, macOS, App Extensions

**Comment by cyonix** [comment]
@rizafran Is the fix result in an SDK update?

**Comment by rizafran** [comment]
@cyonix, I think the fix will be applied on the backend side so it doesn't need an SDK update.

**Comment by themiswang** [comment]
Hello folks,

Confirmed the issue is fixed on our backend, Gonna close this issue.

**Comment by jesus-mg-ios** [comment]
@themiswang it still happens. Not for all non fatals errors and crashes, but some of them are empty when I'm sure they don't have to.

**Comment by Kal-Elx** [comment]
Just as @jesus-mg-ios I also see empty an empty Logs & Breadcrumbs tab for some error reports that should have data. 

Can this issue be reopened? 

<img width="1277" alt="image" src="https://github.com/firebase/firebase-ios-sdk/assets/41339152/1217be65-5703-4581-847d-a7e604de43b5">

**Comment by sipersso** [comment]
Same here. I am also getting the same issue. Interestingly I can see in the dashboard that firebase_screen events are happening including the correct parameters.

**Comment by hsoi** [comment]
Still happening for me as well.

@rizafran @themiswang curious - given the nature of the problem and the backend fix, should we expect existing entries to start showing logs? or will it only work for new entries that came in after the fix?

What can we do to help get this tracked down and truly fixed?

**Comment by rizafran** [comment]
Thanks for letting us know about the issue happening again. It seems that our engineers are already aware with the issue and they're currently investigating it. We'll let you know once we have an update.

**Comment by tosulc** [comment]
Any updates on this one?

**Comment by mserougi** [comment]
Experiencing the same issue as well.

**Comment by samedson** [comment]
Hey folks, did some digging into this. Right now I think there might be 2 issues going on.

Issue 1: If generally logs are showing up, but the screen_view Analytics breadcrumbs are not, you may need to check how you are using the Analytics API. The `AnalyticsParameterScreenClass` should be a string, not a class name. 

You'll see a log if you're running into this issue:

```
10.29.0 - [FirebaseAnalytics][I-ACS013000] Screen parameter value must be of type NSString: CrashlyticsSwiftUIExample.CrashButtonView
10.29.0 - [FirebaseAnalytics][I-ACS031028] Received invalid class for screen: CrashlyticsSwiftUIExample.CrashButtonView
```

Issue 2: Some folks seem to not see any logs at all, including logs added to Crashlytics via the `Crashlytics.log` API. If this is the case, we need to dig deeper into what may be a frontend issue by looking at your specific app. If you are experiencing this, please reach out to support and reference this github issue so we can look into your app. We haven't been able to reproduce this.

**Comment by sipersso** [comment]
We are still seeing the issue. Reached out to support and was told to update the SDK to the latest version (11.0) before you would help. Will do a release early next week and keep you posted.
