### ISSUE TITLE
Getting `trace trap` when using `upload-symbols`

### ISSUE THREAD

**Issue by msrutek-paylocity** [firebase/firebase-ios-sdk#13420]
### Description

When trying to upload dSYM to Crashlytics on our CI machine, we get `trace trap`. 

Enabling debug mode via

```
upload-symbols -ai REDACTED -p ios Redacted.app.dSYM.zip -d
```
we get
```
upload-symbols 3.16 build 35

Arguments:
Debug mode enabled
Google App ID: REDACTED
Platform: ios
DSYM Paths: ["/Users/ci/work/Redacted.app.dSYM.zip"]

Inspecting next path: /Users/ci/work/Redacted.app.dSYM.zip
Found archive at path: /Users/ci/work/Redacted.app.dSYM.zip
Inspecting next path: /var/folders/kv/xxrdyfss1d130vhwx0mf5stw0000gn/T///Users/ci/work/Redacted.app.dSYM.zip.unzipped/XXX.framework.dSYM
Found dSYM at path: /var/folders/kv/xxrdyfss1d130vhwx0mf5stw0000gn/T///Users/ci/work/Redacted.app.dSYM.zip.unzipped/XXX.framework.dSYM
Begin processing dSYM at /var/folders/kv/xxrdyfss1d130vhwx0mf5stw0000gn/T///Users/ci/work/Redacted.app.dSYM.zip.unzipped/XXX.framework.dSYM
[1]    18163 trace trap  -ai APP_ID -p ios  -d
```

✅ We've also tried using version `3.17` with no luck.

Is there any way to prevent this? Or can we get guidance on what could be causing this?

Thanks!

### Firebase SDK Version

10.27.0

### Xcode Version

15.4

### Installation Method

N/A

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

**Comment by JonathanPeterCole** [comment]
I was having the same issue with Xcode 15.4 installed and found that updating to Xcode 16 Beta 4 fixed it for me. Our pipelines running Xcode 15.2 also seem to be unaffected.

**Comment by rizafran** [comment]
Hi @msrutek-paylocity, I'm wondering if the issue has resolved by following the suggestion in https://github.com/firebase/firebase-ios-sdk/issues/13420#issuecomment-2256094473? If not, please provide a complete error logs of the issue to investigate. Thanks.

**Comment by msrutek-paylocity** [comment]
@rizafran It seems to be working locally. However, this is not a solution we can deploy to our CI machine - as we need to push product builds regularly - and beta software can't be used for that.

**Comment by msrutek-paylocity** [comment]
Hello @rizafran , can we expect any update on this? Thanks!

**Comment by msrutek-paylocity** [comment]
Hello @rizafran, any update on this? :)

**Comment by paulb777** [comment]
@msrutek-paylocity It looks like there is both a workaround and request for error logs above.

**Comment by msrutek-paylocity** [comment]
Hello @paulb777 @rizafran , do you have any guidance on how to provide the logs that would be beneficial to you?

**Comment by Almaz5200** [comment]
We too face that issue in our project, logs are the same as in the issue description, just as the Xcode version

**Comment by msrutek-paylocity** [comment]
Hello @paulb777 @themiswang @rizafran , we'd like to help this move forward.

By calling
```
log show --predicate 'eventMessage contains "upload-symbols"' --info --debug --last 1d
```

we got

```

Filtering the log data using "composedMessage CONTAINS "upload-symbols""
Timestamp                       Thread     Type        Activity             PID    TTL
2024-10-09 04:40:30.941758-0500 0x201c69   Default     0x4dd6ef             149    0    tccd: [com.apple.TCC:access] AUTHREQ_ATTRIBUTION: msgID=146.17170, attribution={responsible={TCCDProcess: identifier=com.apple.sshd-keygen-wrapper, pid=96720, auid=501, euid=501, responsible_path=/usr/libexec/sshd-keygen-wrapper, binary_path=/Users/admin/Runner-iOS/_work/mobile-next-gen-ios/mobile-next-gen-ios/Tools/Scripts/firebase-upload-symbols}, accessing={TCCDProcess: identifier=com.firebase.crashlytics.upload-symbols, pid=96720, auid=501, euid=501, binary_path=/Users/admin/Runner-iOS/_work/mobile-next-gen-ios/mobile-next-gen-ios/Tools/Scripts/firebase-upload-symbols}, requesting={TCCDProcess: identifier=com.apple.syspolicyd, pid=146, auid=0, euid=0, binary_path=/usr/libexec/syspolicyd}, },
2024-10-09 04:40:33.288464-0500 0x203b45   Default     0x0                  0      0    kernel: firebase-upload-symbols[96720] Corpse allowed 1 of 5
2024-10-09 04:40:35.311697-0500 0x1874f6   Default     0x0                  286    0    ReportCrash: Formulating fatal 309 report for corpse[96720] firebase-upload-symbols
2024-10-09 04:40:35.315836-0500 0x187578   Default     0x0                  44448  0    osanalyticshelper: (OSAnalytics) creating type 309 as /Library/Logs/DiagnosticReports/.firebase-upload-symbols-2024-10-09-044035.ips
2024-10-09 04:40:35.321397-0500 0x187578   Default     0x0                  44448  0    osanalyticshelper: (OSAnalytics) Saved type '309(<private>)' report (2 of max 25) at /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-09-044035.ips
2024-10-09 04:40:35.321505-0500 0x187578   Default     0x0                  44448  0    osanalyticshelper: xpc log creation type 309 result success: /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-09-044035.ips
2024-10-09 04:40:35.321581-0500 0x1874f6   Default     0x0                  286    0    ReportCrash: (OSAnalytics) client log create type 309 result success: /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-09-044035.ips
2024-10-09 04:40:35.321615-0500 0x1874f6   Default     0x0                  286    0    ReportCrash: no MetricKit for process firebase-upload-symbols type 309 bundleId (null)
2024-10-09 09:35:42.646954-0500 0x28f19a   Default     0x62ff9e             149    0    tccd: [com.apple.TCC:access] AUTHREQ_ATTRIBUTION: msgID=146.20578, attribution={responsible={TCCDProcess: identifier=com.apple.sshd-keygen-wrapper, pid=99643, auid=501, euid=501, responsible_path=/usr/libexec/sshd-keygen-wrapper, binary_path=/Users/admin/Runner-iOS/_work/mobile-next-gen-ios/mobile-next-gen-ios/Tools/Scripts/firebase-upload-symbols}, accessing={TCCDProcess: identifier=com.firebase.crashlytics.upload-symbols, pid=99643, auid=501, euid=501, binary_path=/Users/admin/Runner-iOS/_work/mobile-next-gen-ios/mobile-next-gen-ios/Tools/Scripts/firebase-upload-symbols}, requesting={TCCDProcess: identifier=com.apple.syspolicyd, pid=146, auid=0, euid=0, binary_path=/usr/libexec/syspolicyd}, },
2024-10-09 09:35:45.450209-0500 0x290be4   Default     0x0                  0      0    kernel: firebase-upload-symbols[99643] Corpse allowed 1 of 5
2024-10-09 09:36:11.041705-0500 0x203b5b   Default     0x0                  286    0    ReportCrash: Formulating fatal 309 report for corpse[99643] firebase-upload-symbols
2024-10-09 09:36:11.046926-0500 0x2604ed   Default     0x0                  44448  0    osanalyticshelper: (OSAnalytics) creating type 309 as /Library/Logs/DiagnosticReports/.firebase-upload-symbols-2024-10-09-093611.ips
2024-10-09 09:36:11.056133-0500 0x2604ed   Default     0x0                  44448  0    osanalyticshelper: (OSAnalytics) Saved type '309(<private>)' report (3 of max 25) at /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-09-093611.ips
2024-10-09 09:36:11.056312-0500 0x2604ed   Default     0x0                  44448  0    osanalyticshelper: xpc log creation type 309 result success: /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-09-093611.ips
2024-10-09 09:36:11.056413-0500 0x203b5b   Default     0x0                  286    0    ReportCrash: (OSAnalytics) client log create type 309 result success: /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-09-093611.ips
2024-10-09 09:36:11.056439-0500 0x203b5b   Default     0x0                  286    0    ReportCrash: no MetricKit for process firebase-upload-symbols type 309 bundleId (null)
2024-10-10 00:31:53.526533-0500 0x3713a7   Default     0x81d9fd             149    0    tccd: [com.apple.TCC:access] AUTHREQ_ATTRIBUTION: msgID=146.28642, attribution={responsible={TCCDProcess: identifier=com.apple.sshd-keygen-wrapper, pid=74320, auid=501, euid=501, responsible_path=/usr/libexec/sshd-keygen-wrapper, binary_path=/Users/admin/Runner-iOS/_work/mobile-next-gen-ios/mobile-next-gen-ios/Tools/Scripts/firebase-upload-symbols}, accessing={TCCDProcess: identifier=com.firebase.crashlytics.upload-symbols, pid=74320, auid=501, euid=501, binary_path=/Users/admin/Runner-iOS/_work/mobile-next-gen-ios/mobile-next-gen-ios/Tools/Scripts/firebase-upload-symbols}, requesting={TCCDProcess: identifier=com.apple.syspolicyd, pid=146, auid=0, euid=0, binary_path=/usr/libexec/syspolicyd}, },
2024-10-10 00:31:55.888143-0500 0x37263a   Default     0x0                  0      0    kernel: firebase-upload-symbols[74320] Corpse allowed 1 of 5
2024-10-10 00:31:57.661406-0500 0x36b532   Default     0x0                  286    0    ReportCrash: Formulating fatal 309 report for corpse[74320] firebase-upload-symbols
2024-10-10 00:31:57.664421-0500 0x35a7ad   Default     0x0                  44448  0    osanalyticshelper: (OSAnalytics) creating type 309 as /Library/Logs/DiagnosticReports/.firebase-upload-symbols-2024-10-10-003157.ips
2024-10-10 00:31:57.667885-0500 0x35a7ad   Default     0x0                  44448  0    osanalyticshelper: (OSAnalytics) Saved type '309(<private>)' report (4 of max 25) at /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-10-003157.ips
2024-10-10 00:31:57.667977-0500 0x35a7ad   Default     0x0                  44448  0    osanalyticshelper: xpc log creation type 309 result success: /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-10-003157.ips
2024-10-10 00:31:57.668054-0500 0x36b532   Default     0x0                  286    0    ReportCrash: (OSAnalytics) client log create type 309 result success: /Library/Logs/DiagnosticReports/firebase-upload-symbols-2024-10-10-003157.ips
2024-10-10 00:31:57.668072-0500 0x36b532   Default     0x0                  286    0    ReportCrash: no MetricKit for process firebase-upload-symbols type 309 bundleId (null)
```

Which yields a couple of `.ips` file locations. Below, we can find the contents of one such file.

```json
{
  "uptime": 67000,
  "procRole": "Unspecified",
  "version": 2,
  "userID": 501,
  "deployVersion": 210,
  "modelCode": "Mac14,12",
  "coalitionID": 375,
  "osVersion": {
    "train": "macOS 13.6.4",
    "build": "22G513",
    "releaseType": "User"
  },
  "captureTime": "2024-10-09 00:31:59.6530 -0500",
  "incident": "B74AD1A2-67A0-47FF-950C-91957B6A2BFB",
  "pid": 92887,
  "translated": false,
  "cpuType": "ARM-64",
  "roots_installed": 0,
  "bug_type": "309",
  "procLaunch": "2024-10-09 00:31:57.2953 -0500",
  "procStartAbsTime": 1612436926500,
  "procExitAbsTime": 1612493462296,
  "procName": "firebase-upload-symbols",
  "procPath": "/Users/USER/*/firebase-upload-symbols",
  "parentProc": "ruby",
  "parentPid": 85053,
  "coalitionName": "com.openssh.sshd.9CBDA752-15DF-48FA-9298-A9525D162362",
  "crashReporterKey": "C81DE06D-7E4A-F2E9-BF83-ABE57935F163",
  "responsiblePid": 376,
  "codeSigningID": "com.firebase.crashlytics.upload-symbols",
  "codeSigningTeamID": "EQHXZ8M8AV",
  "codeSigningFlags": 570503953,
  "codeSigningValidationCategory": 6,
  "codeSigningTrustLevel": 0,
  "sip": "enabled",
  "exception": {
    "codes": "0x0000000000000001, 0x000000019be0fd7c",
    "rawCodes": [1, 6910180732],
    "type": "EXC_BREAKPOINT",
    "signal": "SIGTRAP"
  },
  "termination": {
    "flags": 0,
    "code": 5,
    "namespace": "SIGNAL",
    "indicator": "Trace/BPT trap: 5",
    "byProc": "exc handler",
    "byPid": 92887
  },
  "os_fault": { "process": "firebase-upload-symbols" },
  "asi": { "CoreFoundation": ["*** CFRelease() called with NULL ***"] },
  "extMods": {
    "caller": { "thread_create": 0, "thread_set_state": 0, "task_for_pid": 0 },
    "system": { "thread_create": 0, "thread_set_state": 0, "task_for_pid": 42 },
    "targeted": {
      "thread_create": 0,
      "thread_set_state": 0,
      "task_for_pid": 0
    },
    "warnings": 0
  },
  "faultingThread": 1,
  "threads": [
    {
      "id": 1602786,
      "queue": "com.apple.main-thread",
      "frames": [
        {
          "imageOffset": 18160,
          "symbol": "__psynch_cvwait",
          "symbolLocation": 8,
          "imageIndex": 1
        },
        {
          "imageOffset": 30068,
          "symbol": "_pthread_cond_wait",
          "symbolLocation": 1232,
          "imageIndex": 2
        },
        {
          "imageOffset": 323052,
          "symbol": "-[NSOperation waitUntilFinished]",
          "symbolLocation": 512,
          "imageIndex": 3
        },
        {
          "imageOffset": 5755308,
          "symbol": "__NSOPERATIONQUEUE_IS_WAITING_ON_AN_OPERATION__",
          "symbolLocation": 16,
          "imageIndex": 3
        },
        {
          "imageOffset": 725660,
          "symbol": "-[NSOperationQueue addOperations:waitUntilFinished:]",
          "symbolLocation": 160,
          "imageIndex": 3
        },
        { "imageOffset": 82716, "imageIndex": 0 },
        { "imageOffset": 81664, "imageIndex": 0 },
        { "imageOffset": 81064, "imageIndex": 0 },
        { "imageOffset": 84056, "imageIndex": 0 },
        { "imageOffset": 57876, "imageIndex": 0 },
        { "imageOffset": 83676, "imageIndex": 0 },
        { "imageOffset": 81864, "imageIndex": 0 },
        { "imageOffset": 75928, "imageIndex": 0 },
        {
          "imageOffset": 24360,
          "symbol": "start",
          "symbolLocation": 2236,
          "imageIndex": 4
        }
      ]
    },
    {
      "triggered": true,
      "id": 1602793,
      "threadState": {
        "x": [
          { "value": 0 },
          { "value": 0 },
          { "value": 6156413456 },
          { "value": 6156413536 },
          { "value": 16 },
          { "value": 0 },
          { "value": 114 },
          { "value": 0 },
          {
            "value": 6911921791,
            "symbolLocation": 7483,
            "symbol": "_XMLPlistAppendDataUsingBase64.__CFPLDataEncodeTable"
          },
          {
            "value": 8447479808,
            "symbolLocation": 6792,
            "symbol": "__last_exception_backtrace__"
          },
          {
            "value": 8447484096,
            "symbolLocation": 0,
            "symbol": "__CFRuntimeBuiltinObjCClassTable"
          },
          { "value": 36028797018963960 },
          { "value": 50 },
          { "value": 5393919232 },
          {
            "value": 8442316248,
            "symbolLocation": 0,
            "symbol": "__CFConstantStringClassReference"
          },
          {
            "value": 8442316248,
            "symbolLocation": 0,
            "symbol": "__CFConstantStringClassReference"
          },
          { "value": 6908243564, "symbolLocation": 0, "symbol": "CFRelease" },
          { "value": 2 },
          { "value": 0 },
          { "value": 0 },
          { "value": 1 },
          { "value": 4311304248 },
          { "value": 6156414144 },
          { "value": 4311204007 },
          { "value": 105553170533184 },
          { "value": 6156415200 },
          { "value": 0 },
          { "value": 6156415360 },
          { "value": 67125248 }
        ],
        "flavor": "ARM_THREAD_STATE64",
        "lr": { "value": 6908243896 },
        "cpsr": { "value": 1073745920 },
        "fp": { "value": 6156413344 },
        "sp": { "value": 6156413344 },
        "esr": { "value": 4060086273, "description": "(Breakpoint) brk 1" },
        "pc": { "value": 6910180732, "matchesCrashFrame": 1 },
        "far": { "value": 0 }
      },
      "queue": "NSOperationQueue 0x139805020 (QOS: UNSPECIFIED)",
      "frames": [
        {
          "imageOffset": 1985916,
          "symbol": "CFRelease.cold.1",
          "symbolLocation": 16,
          "imageIndex": 5
        },
        {
          "imageOffset": 49080,
          "symbol": "CFRelease",
          "symbolLocation": 332,
          "imageIndex": 5
        },
        { "imageOffset": 102576, "imageIndex": 0 },
        { "imageOffset": 100796, "imageIndex": 0 },
        {
          "imageOffset": 17408,
          "symbol": "_dispatch_client_callout",
          "symbolLocation": 20,
          "imageIndex": 6
        },
        {
          "imageOffset": 23616,
          "symbol": "_dispatch_once_callout",
          "symbolLocation": 32,
          "imageIndex": 6
        },
        { "imageOffset": 97000, "imageIndex": 0 },
        { "imageOffset": 91268, "imageIndex": 0 },
        { "imageOffset": 6504, "imageIndex": 0 },
        { "imageOffset": 17020, "imageIndex": 0 },
        { "imageOffset": 16844, "imageIndex": 0 },
        {
          "imageOffset": 258464,
          "symbol": "__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__",
          "symbolLocation": 16,
          "imageIndex": 3
        },
        {
          "imageOffset": 258192,
          "symbol": "__NSOQSchedule_f",
          "symbolLocation": 172,
          "imageIndex": 3
        },
        {
          "imageOffset": 79128,
          "symbol": "_dispatch_block_async_invoke2",
          "symbolLocation": 148,
          "imageIndex": 6
        },
        {
          "imageOffset": 17408,
          "symbol": "_dispatch_client_callout",
          "symbolLocation": 20,
          "imageIndex": 6
        },
        {
          "imageOffset": 30852,
          "symbol": "_dispatch_continuation_pop",
          "symbolLocation": 504,
          "imageIndex": 6
        },
        {
          "imageOffset": 28396,
          "symbol": "_dispatch_async_redirect_invoke",
          "symbolLocation": 584,
          "imageIndex": 6
        },
        {
          "imageOffset": 89752,
          "symbol": "_dispatch_root_queue_drain",
          "symbolLocation": 396,
          "imageIndex": 6
        },
        {
          "imageOffset": 91840,
          "symbol": "_dispatch_worker_thread2",
          "symbolLocation": 164,
          "imageIndex": 6
        },
        {
          "imageOffset": 12344,
          "symbol": "_pthread_wqthread",
          "symbolLocation": 228,
          "imageIndex": 2
        },
        {
          "imageOffset": 7572,
          "symbol": "start_wqthread",
          "symbolLocation": 8,
          "imageIndex": 2
        }
      ]
    },
    {
      "id": 1602794,
      "frames": [
        {
          "imageOffset": 7564,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 2
        }
      ]
    }
  ],
  "usedImages": [
    {
      "source": "P",
      "arch": "arm64",
      "base": 4311023616,
      "size": 229376,
      "uuid": "4c4c44a7-5555-3144-a131-36f58d6571f1",
      "path": "/Users/USER/*/firebase-upload-symbols",
      "name": "firebase-upload-symbols"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6907539456,
      "size": 237560,
      "uuid": "226cee47-fcbf-3b8b-93c5-fcd5ed27e408",
      "path": "/usr/lib/system/libsystem_kernel.dylib",
      "name": "libsystem_kernel.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6907777024,
      "size": 53248,
      "uuid": "7acb080f-eabe-3a59-8d9f-7459f33bb263",
      "path": "/usr/lib/system/libsystem_pthread.dylib",
      "name": "libsystem_pthread.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6924554240,
      "CFBundleShortVersionString": "6.9",
      "CFBundleIdentifier": "com.apple.Foundation",
      "size": 10248192,
      "uuid": "05392821-5fc5-3c1a-82a4-006d989963a9",
      "path": "/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation",
      "name": "Foundation",
      "CFBundleVersion": "1979.102"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6904274944,
      "size": 583048,
      "uuid": "03576074-d9ac-3a0e-aad2-f4e02768bb50",
      "path": "/usr/lib/dyld",
      "name": "dyld"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6908194816,
      "CFBundleShortVersionString": "6.9",
      "CFBundleIdentifier": "com.apple.CoreFoundation",
      "size": 5087232,
      "uuid": "c8a55620-0514-3ffd-af7f-854d6b752b18",
      "path": "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation",
      "name": "CoreFoundation",
      "CFBundleVersion": "1979.102"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6906019840,
      "size": 294912,
      "uuid": "b86c558f-d7cd-340d-97a6-7c19135943bb",
      "path": "/usr/lib/system/libdispatch.dylib",
      "name": "libdispatch.dylib"
    }
  ],
  "sharedCache": {
    "base": 6903611392,
    "size": 3585982464,
    "uuid": "536dc90a-98cb-3f77-8b1f-dbf9ef4cfd83"
  },
  "vmSummary": "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=831.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=831.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           198.2M       23 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                         16K        1 \n__AUTH                             606K      151 \n__AUTH_CONST                      11.6M      292 \n__CTF                               824        1 \n__DATA                            2702K      279 \n__DATA_CONST                      14.2M      294 \n__DATA_DIRTY                       684K      101 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       803.4M        2 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                           218.0M      306 \ndyld private memory                272K        2 \nmapped file                       37.4M        5 \nshared memory                      624K        7 \n===========                     =======  ======= \nTOTAL                              2.0G     1483 \nTOTAL, minus reserved VM space     1.4G     1483 \n",
  "legacyInfo": {
    "threadTriggered": {
      "queue": "NSOperationQueue 0x139805020 (QOS: UNSPECIFIED)"
    }
  },
  "logWritingSignature": "1da29b04270d179aeef22e11d4a5384ea5ad0a70"
}

```

There's a particular line that got our attention, which is
```json
{ "CoreFoundation": ["*** CFRelease() called with NULL ***"] }
```

This might indicate a memory management issue. Is that possible? Could the reference be checked for `NULL`, before calling `CFRelease`?

Thanks!

**Comment by Almaz5200** [comment]
I can report that our log and `.ips` file is almost identical to the one sent by @msrutek-paylocity, which likely means that we have the same issue
``` json
{"app_name":"upload-symbols","timestamp":"2024-10-09 17:27:05.00 +0000","app_version":"","slice_uuid":"4c4c443e-5555-3144-a1e8-58603c770f00","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 13.6.1 (22G313)","roots_installed":0,"incident_id":"249C9938-C47E-4E75-B603-BC30C4DFC4BF","name":"upload-symbols"}
{
  "uptime" : 25000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "coalitionID" : 19405,
  "osVersion" : {
    "train" : "macOS 13.6.1",
    "build" : "22G313",
    "releaseType" : "User"
  },
  "captureTime" : "2024-10-09 17:26:57.9048 +0000",
  "incident" : "249C9938-C47E-4E75-B603-BC30C4DFC4BF",
  "pid" : 61056,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-10-09 17:26:52.8793 +0000",
  "procStartAbsTime" : 621894239019,
  "procExitAbsTime" : 622014568012,
  "procName" : "upload-symbols",
  "procPath" : "\/Users\/USER\/*\/upload-symbols",
  "parentProc" : "ruby",
  "parentPid" : 33193,
  "coalitionName" : "com.openssh.sshd.EB8FC02A-DE88-4862-94C3-023CE59C73F9",
  "crashReporterKey" : "DD7B5A8D-479A-AC69-3E6C-2D0AEDF0C6A6",
  "responsiblePid" : 28279,
  "responsibleProc" : "sshd",
  "codeSigningID" : "com.firebase.crashlytics.upload-symbols",
  "codeSigningTeamID" : "EQHXZ8M8AV",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x000000019c6b3d7c","rawCodes":[1,6919241084],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":61056},
  "os_fault" : {"process":"upload-symbols"},
  "asi" : {"CoreFoundation":["*** CFRelease() called with NULL ***"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":9},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":1617177,"queue":"com.apple.main-thread","frames":[{"imageOffset":18224,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":1},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":2},{"imageOffset":323052,"symbol":"-[NSOperation waitUntilFinished]","symbolLocation":512,"imageIndex":3},{"imageOffset":5755308,"symbol":"__NSOPERATIONQUEUE_IS_WAITING_ON_AN_OPERATION__","symbolLocation":16,"imageIndex":3},{"imageOffset":725660,"symbol":"-[NSOperationQueue addOperations:waitUntilFinished:]","symbolLocation":160,"imageIndex":3},{"imageOffset":18076,"imageIndex":0},{"imageOffset":17024,"imageIndex":0},{"imageOffset":16428,"imageIndex":0},{"imageOffset":19424,"imageIndex":0},{"imageOffset":71236,"imageIndex":0},{"imageOffset":19048,"imageIndex":0},{"imageOffset":17224,"imageIndex":0},{"imageOffset":5792,"imageIndex":0},{"imageOffset":24360,"symbol":"start","symbolLocation":2236,"imageIndex":4}]},{"triggered":true,"id":1617194,"threadState":{"x":[{"value":0},{"value":0},{"value":6135556624},{"value":6135556704},{"value":16},{"value":0},{"value":114},{"value":0},{"value":6920982143,"symbolLocation":7483,"symbol":"_XMLPlistAppendDataUsingBase64.__CFPLDataEncodeTable"},{"value":8449429504,"symbolLocation":6792,"symbol":"__last_exception_backtrace__"},{"value":8449433792,"symbolLocation":0,"symbol":"__CFRuntimeBuiltinObjCClassTable"},{"value":36028797018963960},{"value":39},{"value":5486188624},{"value":8444282328,"symbolLocation":0,"symbol":"__CFConstantStringClassReference"},{"value":8444282328,"symbolLocation":0,"symbol":"__CFConstantStringClassReference"},{"value":6917303916,"symbolLocation":0,"symbol":"CFRelease"},{"value":2},{"value":0},{"value":0},{"value":105553136496672},{"value":4332204048},{"value":4332203848},{"value":4332089348},{"value":105553136496672},{"value":6135558368},{"value":0},{"value":6135558528},{"value":67125248}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6917304248},"cpsr":{"value":1073745920},"fp":{"value":6135556512},"sp":{"value":6135556512},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6919241084,"matchesCrashFrame":1},"far":{"value":0}},"queue":"NSOperationQueue 0x147c7c080 (QOS: UNSPECIFIED)","frames":[{"imageOffset":1985916,"symbol":"CFRelease.cold.1","symbolLocation":16,"imageIndex":5},{"imageOffset":49080,"symbol":"CFRelease","symbolLocation":332,"imageIndex":5},{"imageOffset":98720,"imageIndex":0},{"imageOffset":96940,"imageIndex":0},{"imageOffset":17408,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":6},{"imageOffset":23616,"symbol":"_dispatch_once_callout","symbolLocation":32,"imageIndex":6},{"imageOffset":93148,"imageIndex":0},{"imageOffset":87512,"imageIndex":0},{"imageOffset":6512,"imageIndex":0},{"imageOffset":24864,"imageIndex":0},{"imageOffset":24688,"imageIndex":0},{"imageOffset":258464,"symbol":"__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__","symbolLocation":16,"imageIndex":3},{"imageOffset":258192,"symbol":"__NSOQSchedule_f","symbolLocation":172,"imageIndex":3},{"imageOffset":79128,"symbol":"_dispatch_block_async_invoke2","symbolLocation":148,"imageIndex":6},{"imageOffset":17408,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":6},{"imageOffset":30852,"symbol":"_dispatch_continuation_pop","symbolLocation":504,"imageIndex":6},{"imageOffset":28396,"symbol":"_dispatch_async_redirect_invoke","symbolLocation":584,"imageIndex":6},{"imageOffset":89752,"symbol":"_dispatch_root_queue_drain","symbolLocation":396,"imageIndex":6},{"imageOffset":91840,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":6},{"imageOffset":12344,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":2},{"imageOffset":7572,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":2}]},{"id":1617195,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331880448,
    "size" : 229376,
    "uuid" : "4c4c443e-5555-3144-a1e8-58603c770f00",
    "path" : "\/Users\/USER\/*\/upload-symbols",
    "name" : "upload-symbols"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6916599808,
    "size" : 237544,
    "uuid" : "a57217d4-b72e-3092-a6e4-3d9c1885fe92",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6916837376,
    "size" : 53248,
    "uuid" : "1f30fb9a-bdf9-32db-a709-8417666a7e45",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6933614592,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10248192,
    "uuid" : "19a4dcb2-d426-3efa-80e2-c7a5e1522f64",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1979.102"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6913335296,
    "size" : 583048,
    "uuid" : "49204446-242b-3d1e-9704-32f8ac99723e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6917255168,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5087232,
    "uuid" : "982f755b-2044-397a-8823-57ddc4341cf3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1979.102"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6915080192,
    "size" : 294912,
    "uuid" : "9897030f-75d3-374b-8787-322d3d72e096",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  }
],
  "sharedCache" : {
  "base" : 6912671744,
  "size" : 3553509376,
  "uuid" : "531c0369-32b5-3499-ad7a-31d86a6e6b93"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=705.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=705.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           192.2M       24 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                         16K        1 \n__AUTH                             612K      153 \n__AUTH_CONST                      11.6M      294 \n__CTF                               824        1 \n__DATA                            2716K      279 \n__DATA_CONST                      14.2M      296 \n__DATA_DIRTY                       684K      101 \n__FONT_DATA  2352        1 \n__LINKEDIT                       802.3M        2 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                           218.5M      308 \ndyld private memory                272K        2 \nmapped file                       37.0M        5 \nshared memory                      624K        7 \n===========                     =======  ======= \nTOTAL                              1.9G     1491 \nTOTAL, minus reserved VM space     1.4G     1491 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "NSOperationQueue 0x147c7c080 (QOS: UNSPECIFIED)"
  }
},
  "logWritingSignature" : "d1c03fcda32ebe0218cafcd4fa5b778914f670c7"
}
```

**Comment by igor84** [comment]
It is happening to us too. It works on machines with MacOS Sonoma 14.5 and XCode 15.2 but not on MacOS Sequoia 15.0.1 with XCode 15.2. We are now reinstalling that machine with older MacOS to try again.

**Comment by msrutek-paylocity** [comment]
Hello @paulb777 @rizafran @themiswang , any update on this? We also tried using version 3.18, which resulted in the same.

**Comment by Almaz5200** [comment]
We resolved the issue for us by updating CI machine to Sonoma and Xcode 16, but it's unfortunate it came to that.

**Comment by themiswang** [comment]
Hey folks,

I have removed all the methods need to do CFRelease in `upload-symbols`, change will be in next SDK release.

**Comment by msrutek-paylocity** [comment]
@themiswang Awesome, thanks! Do you have any ETA on the next release? :)

**Comment by themiswang** [comment]
@msrutek-paylocity will be on Nov 14, if you need in urgent you can download the artifact from main, I have merged the change already.

**Comment by msrutek-paylocity** [comment]
@themiswang Thank you, we've just tested it - and although we're not getting the `CFRelease` - related errors anymore, we're still getting a trace trap, now with `EXC_BAD_ACCESS`.

When inspecting the `.ips` logs, 

<details>
  <summary>Full crash log >>></summary>
  
```json
{
  "uptime": 6700000,
  "procRole": "Unspecified",
  "version": 2,
  "userID": 501,
  "deployVersion": 210,
  "modelCode": "Mac14,12",
  "coalitionID": 379,
  "osVersion": {
    "train": "macOS 13.6.4",
    "build": "22G513",
    "releaseType": "User"
  },
  "captureTime": "2024-11-04 23:37:06.4066 -0600",
  "incident": "BBAEEB57-854A-4A14-88F1-E798F69F4A69",
  "pid": 33028,
  "translated": false,
  "cpuType": "ARM-64",
  "roots_installed": 0,
  "bug_type": "309",
  "procLaunch": "2024-11-04 23:37:03.7191 -0600",
  "procStartAbsTime": 161402201378377,
  "procExitAbsTime": 161402265793518,
  "procName": "firebase-upload-symbols",
  "procPath": "/Users/USER/*/firebase-upload-symbols",
  "parentProc": "ruby",
  "parentPid": 25013,
  "coalitionName": "com.openssh.sshd.CE9CC868-1BDB-43DD-AEA6-1B61ED28E27B",
  "crashReporterKey": "5CFC3F53-391A-37C1-D8C7-D294C76DCDC7",
  "responsiblePid": 390,
  "codeSigningID": "com.firebase.crashlytics.upload-symbols",
  "codeSigningTeamID": "EQHXZ8M8AV",
  "codeSigningFlags": 570503953,
  "codeSigningValidationCategory": 6,
  "codeSigningTrustLevel": 0,
  "sip": "enabled",
  "vmRegionInfo": "0 is not in any region.  Bytes before following region: 4334665728\n      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1025dc000-102618000    [  240K] r-x/r-x SM=COW  ...pload-symbols",
  "exception": {
    "codes": "0x0000000000000001, 0x0000000000000000",
    "rawCodes": [1, 0],
    "type": "EXC_BAD_ACCESS",
    "signal": "SIGSEGV",
    "subtype": "KERN_INVALID_ADDRESS at 0x0000000000000000"
  },
  "termination": {
    "flags": 0,
    "code": 11,
    "namespace": "SIGNAL",
    "indicator": "Segmentation fault: 11",
    "byProc": "exc handler",
    "byPid": 33028
  },
  "vmregioninfo": "0 is not in any region.  Bytes before following region: 4334665728\n      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1025dc000-102618000    [  240K] r-x/r-x SM=COW  ...pload-symbols",
  "extMods": {
    "caller": { "thread_create": 0, "thread_set_state": 0, "task_for_pid": 0 },
    "system": {
      "thread_create": 0,
      "thread_set_state": 0,
      "task_for_pid": 2558
    },
    "targeted": {
      "thread_create": 0,
      "thread_set_state": 0,
      "task_for_pid": 0
    },
    "warnings": 0
  },
  "faultingThread": 1,
  "threads": [
    {
      "id": 124303407,
      "queue": "com.apple.main-thread",
      "frames": [
        {
          "imageOffset": 18160,
          "symbol": "__psynch_cvwait",
          "symbolLocation": 8,
          "imageIndex": 1
        },
        {
          "imageOffset": 30068,
          "symbol": "_pthread_cond_wait",
          "symbolLocation": 1232,
          "imageIndex": 2
        },
        {
          "imageOffset": 323052,
          "symbol": "-[NSOperation waitUntilFinished]",
          "symbolLocation": 512,
          "imageIndex": 3
        },
        {
          "imageOffset": 5755308,
          "symbol": "__NSOPERATIONQUEUE_IS_WAITING_ON_AN_OPERATION__",
          "symbolLocation": 16,
          "imageIndex": 3
        },
        {
          "imageOffset": 725660,
          "symbol": "-[NSOperationQueue addOperations:waitUntilFinished:]",
          "symbolLocation": 160,
          "imageIndex": 3
        },
        { "imageOffset": 19136, "imageIndex": 0 },
        { "imageOffset": 17160, "imageIndex": 0 },
        { "imageOffset": 16564, "imageIndex": 0 },
        { "imageOffset": 20772, "imageIndex": 0 },
        { "imageOffset": 72272, "imageIndex": 0 },
        { "imageOffset": 20396, "imageIndex": 0 },
        { "imageOffset": 17360, "imageIndex": 0 },
        { "imageOffset": 5908, "imageIndex": 0 },
        {
          "imageOffset": 24360,
          "symbol": "start",
          "symbolLocation": 2236,
          "imageIndex": 4
        }
      ]
    },
    {
      "triggered": true,
      "id": 124303417,
      "threadState": {
        "x": [
          { "value": 105553129913233 },
          { "value": 6132771688 },
          { "value": 1 },
          { "value": 1 },
          { "value": 12 },
          { "value": 0 },
          { "value": 0 },
          { "value": 512 },
          { "value": 4334760076 },
          { "value": 8161808061, "objc-selector": "retain" },
          { "value": 105553477079517 },
          { "value": 3 },
          { "value": 1 },
          { "value": 105553150911808 },
          {
            "value": 8353643040,
            "symbolLocation": 0,
            "symbol": "_NSConcreteStackBlock"
          },
          {
            "value": 8353643040,
            "symbolLocation": 0,
            "symbol": "_NSConcreteStackBlock"
          },
          {
            "value": 8353643040,
            "symbolLocation": 0,
            "symbol": "_NSConcreteStackBlock"
          },
          {
            "value": 3542644063696613452,
            "symbolLocation": 3542644056880316416,
            "symbol": "-[__NSStackBlock__ retain]"
          },
          { "value": 0 },
          { "value": 6132771784 },
          { "value": 105553129913233 },
          { "value": 0 },
          { "value": 105553129913216 },
          { "value": 4334890031 },
          { "value": 105553129913216 },
          { "value": 6132773088 },
          { "value": 0 },
          { "value": 6132773248 },
          { "value": 67125248 }
        ],
        "flavor": "ARM_THREAD_STATE64",
        "lr": { "value": 4334760040 },
        "cpsr": { "value": 1610618880 },
        "fp": { "value": 6132771760 },
        "sp": { "value": 6132771680 },
        "esr": {
          "value": 2181038086,
          "description": "(Instruction Abort) Translation fault"
        },
        "pc": { "value": 0 },
        "far": { "value": 0 }
      },
      "queue": "NSOperationQueue 0x125908350 (QOS: UNSPECIFIED)",
      "frames": [
        { "imageOffset": 0, "imageIndex": 5 },
        { "imageOffset": 89100, "imageIndex": 0 },
        { "imageOffset": 88592, "imageIndex": 0 },
        { "imageOffset": 6648, "imageIndex": 0 },
        { "imageOffset": 26232, "imageIndex": 0 },
        { "imageOffset": 26056, "imageIndex": 0 },
        {
          "imageOffset": 258464,
          "symbol": "__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__",
          "symbolLocation": 16,
          "imageIndex": 3
        },
        {
          "imageOffset": 258192,
          "symbol": "__NSOQSchedule_f",
          "symbolLocation": 172,
          "imageIndex": 3
        },
        {
          "imageOffset": 79128,
          "symbol": "_dispatch_block_async_invoke2",
          "symbolLocation": 148,
          "imageIndex": 6
        },
        {
          "imageOffset": 17408,
          "symbol": "_dispatch_client_callout",
          "symbolLocation": 20,
          "imageIndex": 6
        },
        {
          "imageOffset": 30852,
          "symbol": "_dispatch_continuation_pop",
          "symbolLocation": 504,
          "imageIndex": 6
        },
        {
          "imageOffset": 28396,
          "symbol": "_dispatch_async_redirect_invoke",
          "symbolLocation": 584,
          "imageIndex": 6
        },
        {
          "imageOffset": 89752,
          "symbol": "_dispatch_root_queue_drain",
          "symbolLocation": 396,
          "imageIndex": 6
        },
        {
          "imageOffset": 91840,
          "symbol": "_dispatch_worker_thread2",
          "symbolLocation": 164,
          "imageIndex": 6
        },
        {
          "imageOffset": 12344,
          "symbol": "_pthread_wqthread",
          "symbolLocation": 228,
          "imageIndex": 2
        },
        {
          "imageOffset": 7572,
          "symbol": "start_wqthread",
          "symbolLocation": 8,
          "imageIndex": 2
        }
      ]
    },
    {
      "id": 124303418,
      "frames": [
        {
          "imageOffset": 7564,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 2
        }
      ]
    }
  ],
  "usedImages": [
    {
      "source": "P",
      "arch": "arm64",
      "base": 4334665728,
      "size": 245760,
      "uuid": "4c4c44df-5555-3144-a123-2fe7ffcd2696",
      "path": "/Users/USER/*/firebase-upload-symbols",
      "name": "firebase-upload-symbols"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6818967552,
      "size": 237560,
      "uuid": "226cee47-fcbf-3b8b-93c5-fcd5ed27e408",
      "path": "/usr/lib/system/libsystem_kernel.dylib",
      "name": "libsystem_kernel.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6819205120,
      "size": 53248,
      "uuid": "7acb080f-eabe-3a59-8d9f-7459f33bb263",
      "path": "/usr/lib/system/libsystem_pthread.dylib",
      "name": "libsystem_pthread.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6835982336,
      "CFBundleShortVersionString": "6.9",
      "CFBundleIdentifier": "com.apple.Foundation",
      "size": 10248192,
      "uuid": "05392821-5fc5-3c1a-82a4-006d989963a9",
      "path": "/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation",
      "name": "Foundation",
      "CFBundleVersion": "1979.102"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6815703040,
      "size": 583048,
      "uuid": "03576074-d9ac-3a0e-aad2-f4e02768bb50",
      "path": "/usr/lib/dyld",
      "name": "dyld"
    },
    {
      "size": 0,
      "source": "A",
      "base": 0,
      "uuid": "00000000-0000-0000-0000-000000000000"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6817447936,
      "size": 294912,
      "uuid": "b86c558f-d7cd-340d-97a6-7c19135943bb",
      "path": "/usr/lib/system/libdispatch.dylib",
      "name": "libdispatch.dylib"
    }
  ],
  "sharedCache": {
    "base": 6815039488,
    "size": 3585982464,
    "uuid": "536dc90a-98cb-3f77-8b1f-dbf9ef4cfd83"
  },
  "vmSummary": "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=950.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=950.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           197.2M       22 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         360.0M        3         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                         16K        1 \n__AUTH                             612K      153 \n__AUTH_CONST                      11.6M      294 \n__CTF                               824        1 \n__DATA                            2725K      280 \n__DATA_CONST                      14.2M      296 \n__DATA_DIRTY                       684K      101 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       803.4M        2 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                           218.5M      308 \ndyld private memory                272K        2 \nmapped file                       36.9M        5 \nshared memory                      624K        7 \n===========                     =======  ======= \nTOTAL                              2.1G     1492 \nTOTAL, minus reserved VM space     1.4G     1492 \n",
  "legacyInfo": {
    "threadTriggered": {
      "queue": "NSOperationQueue 0x125908350 (QOS: UNSPECIFIED)"
    }
  },
  "logWritingSignature": "bdbdb8d4c20e9dc9707fd533f3e21b38ccd70e4d"
}

```
</details>

We're getting

```json
"exception": {
  "codes": "0x0000000000000001, 0x0000000000000000",
  "rawCodes": [1, 0],
  "type": "EXC_BAD_ACCESS",
  "signal": "SIGSEGV",
  "subtype": "KERN_INVALID_ADDRESS at 0x0000000000000000"
},
```

Could there be a memory management issue that should be fixed? Thanks!

**Comment by msrutek-paylocity** [comment]
Hello @themiswang, thanks for the info, here's a couple of question.

> ...wonder if you can find stack trace for the crash?

Would you have any recommendations on where to obtain those?


> We have also realized you are on a pretty old OS version. Wonder if could you give a try to update os version for your CI environment?

Yes, this is true. However, it's been proven to be very stable for us. Although we believe that an upgrade might fix the issue, we'd like consider all other options first.

Is there a way we could have access to the source code of `upload-symbols` so we could try to debug it?

**Comment by msrutek-paylocity** [comment]
Hello @themiswang , any thoughts on the post above? :)

**Comment by rizafran** [comment]
Hi @msrutek-paylocity, currently, there's no way to look into the source code of the `upload-symbols` as we haven't open source it and it's an internal tool, but feel free to file a feature request for that.

**Comment by msrutek-paylocity** [comment]
@rizafran Thanks, submitted a FR - https://github.com/firebase/firebase-ios-sdk/issues/14260

Also, we've updated one of our CI machines to macOS 14.7.1 and the problem went away 👍 

However, we might still want to fix it for the older macOS.

**Comment by msrutek-paylocity** [comment]
We've updated all our CI machines to macOS 14, so we'll be unable to provide additional feedback on this. For this reason, I'm closing this issue.
