### ISSUE TITLE
AppCheck API request error for a few percentage of active users

### ISSUE THREAD

**Issue by Kondamon** [firebase/firebase-ios-sdk#13924]
### Description

Some of our users get `The operation couldn’t be completed. API request error.`when using AppCheck. The issue is not reproducible on our side. See also https://github.com/firebase/firebase-ios-sdk/issues/12468#issuecomment-2420328451.

### Reproducing the issue

```
 AppCheck.appCheck().token(forcingRefresh: false) { [weak self] token, error in
 ...
// error
 }
 ```
 
**Error:**  `The operation couldn’t be completed. API request error. `

### Firebase SDK Version

11.3.0

### Xcode Version

15.4 (15F31d)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Check, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
The operation couldn’t be completed. API request error.
```

### If using Swift Package Manager, the project's Package.resolved

AppCheckCore 11.1.0

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Kondamon** [comment]
@ncooke3

**Comment by ncooke3** [comment]
Thanks, @Kondamon. Could you share your project number with me? Feel free to email it to: `nickcooke+gh` at google dot com

The SDK is labeling this as a generic network error so I'm hoping that the backend logs associated with the project number may provide more details.

**Comment by ncooke3** [comment]
Hi @Kondamon, I just released [AppCheckCore 11.2.0](https://github.com/google/app-check/releases/tag/11.2.0) which is compatible with the latest Firebase 11.x versions. You can pull it in by updating your SPM dependencies. The errors you shared traced back to reusing expired app attest challenges. Since these challenges are not stored anywhere, the hypothesis is that `URLSession`'s caching protocol may be giving back requested challenges rather than fetching new ones from the server–– leading to the reuse of expired challenges.

I'm going to mark this issue as fixed now, but we can re-open it if needed.

**Comment by Kondamon** [comment]
@ncooke3 Unfortunately, AppCheckCore 11.2.0 didn't resolve the issue. I'm still getting the same error message.

**Comment by ncooke3** [comment]
Thanks for checking, @Kondamon. This time, were you able to reproduce the error locally or were these reported from your released app?

**Comment by Kondamon** [comment]
@ncooke3, no, I'm not able to reproduce it locally. We have received the error in Crashlytics for our latest release.

**Comment by Kondamon** [comment]
@ncooke3, I have reviewed the logs and breadcrumbs again. Could it be possible that this error message is raised when there is no internet connection?
