### ISSUE TITLE
FirebaseApp.configure(): Performing I/O on the main thread can cause hangs.

### ISSUE THREAD

**Issue by nosferatu500** [firebase/firebase-ios-sdk#14619]
### Description

Hello!

I got this warning from Xcode today

> FirebaseApp.configure(): Performing I/O on the main thread can cause hangs.

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        FirebaseApp.configure()
        
        Messaging.messaging().delegate = self
```

### Firebase SDK Version

11.10.0

### Xcode Version

16.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by nosferatu500** [comment]
Stack trace leading up to next line

```
// GoogleUtilities/Environment/GULAppEnvironmentUtil

+ (BOOL)isAppExtension {
#if TARGET_OS_IOS || TARGET_OS_TV || TARGET_OS_WATCH
  // Documented by <a href="https://goo.gl/RRB2Up">Apple</a>
  BOOL appExtension = [[[NSBundle mainBundle] bundlePath] hasSuffix:@".appex"];     ← here
  return appExtension;
#elif TARGET_OS_OSX
  return NO;
#endif
}
```

**Comment by paulb777** [comment]
Please share the stack trace

**Comment by nosferatu500** [comment]
Hi! I haven't changed anything from the last report, and for now, I see no warnings in Xcode. I will update the issue if it appears again (probably an Xcode bug).

**Comment by goppinath** [comment]
Here are some more details. Xcode is displaying a warning in FIRApp.m at line 348, indicating that performing I/O operations on the main thread can lead to slow app launches, which may affect startup performance.

However, the Firebase documentation states that the default app configuration (_FIRAPP_DEFAULT) must be initialized on the main thread. This initialization process involves synchronous file I/O to read the GoogleService-Info.plist file from disk.

I am using Xcode version 16.4. Please refer to the screenshot for additional information.

<img width="1525" alt="Image" src="https://github.com/user-attachments/assets/44788b2a-9b92-4a15-90e6-17349b6e9d9f" />

**Comment by weakfl** [comment]
Still an issue with v12.0. The only workaround is to wrap initialisation in a Task:

```swift
Task(priority: .high) { @MainActor in
    FirebaseApp.configure()
    FirebaseConfiguration.shared.setLoggerLevel(.error)
}
```

Doing this results in the following warning:

> The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI).

So not an ideal solution either as it looks like it's possible to miss crashes which happen early in the application lifecycle.

@paulb777 any recommendations how to proceed?

**Comment by paulb777** [comment]
@weakfl Do you have the same stacktrace as https://github.com/firebase/firebase-ios-sdk/issues/14619#issuecomment-2775455137?

**Comment by weakfl** [comment]
@paulb777 pretty much, yes. `+[FIRAnalytics startWithConfiguration:options:]` seems to be the culprit.

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/4d89ffad-49c5-4136-8c0e-b9d08ec0ec8d" />

**Comment by morganchen12** [comment]
This should be fixed in the upcoming release.

**Comment by weakfl** [comment]
@morganchen12 @paulb777 still an issue with v12.1.0

EDIT:
Fyi, simulator is fine now, but still happens on device.

**Comment by ed-huang-jp** [comment]
Hi @morganchen12, could you let me know which PR fixed this issue?

**Comment by goppinath** [comment]
Yes, I can confirm that the fix worked on the simulator, **but not on the real device**. I tested it with the Firebase iOS SDK version 12.1.0 and Xcode 26.

**Comment by htcgh** [comment]
Hi all. I'm not able to reproduce these warnings. May I get some more stack traces? Thanks!

**Comment by goppinath** [comment]
@htcgh  Here is the stack trace. The name of the app has been obscured.

<img width="981" height="479" alt="Image" src="https://github.com/user-attachments/assets/daaa1e1b-6e2c-47bf-b9b9-3da8b95196b4" />

**Comment by weakfl** [comment]
@htcgh see stack trace below.

It's maybe worth noting that we are running staging and production versions of the app, which are pretty much identical, except for the bundle identifier. Only the production target shows this issue.

<img width="413" height="754" alt="Image" src="https://github.com/user-attachments/assets/9f861365-8630-4489-a565-655fcbea16a8" />

**Comment by htcgh** [comment]
Thanks @goppinath and @weakfl for the stack traces. They were really helpful. The upcoming SDK release will address those specific code paths. If there are more warnings that involve APM symbols, please share those too.

**Comment by goppinath** [comment]
@htcgh After updating to version 12.2.0, it seems the warning is **fixed**. I tried it with the simulator and a real device, tested with Xcode 26 beta 7.
