### ISSUE TITLE
Swift unit tests fail to find Firebase module

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#16]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 8.3
  * Firebase SDK version: 4.0
  * Library version: 4.0
  * Firebase Product: all (auth, database, storage, core, messaging, etc)

#### Steps to reproduce:

Unit tests for Swift projects that import Firebase fail to build
Details in http://stackoverflow.com/questions/38216090/xcode-unit-testing-with-cocoapods/39602648
Reproducible test case at https://github.com/marcelofabri/BrokenFirebase

**Comment by ryanwilson** [comment]
It looks like `${PODS_ROOT}/Firebase/Core/Sources` is appropriately being added to the regular target's `.xcconfig` file but not the test `.xcconfig` file. Trying to figure out if this is on our side, or if I can find issue in Cocoapods.

**Comment by ryanwilson** [comment]
In the meantime for people seeing this issue, adding `${PODS_ROOT}/Firebase/Core/Sources` to the `HEADER_SEARCH_PATHS` after `$(inherited)` in your `Pods-<ProjectName>Tests.debug.xcconfig` should fix the build.

Still investigating.

**Comment by ryanwilson** [comment]
### Workaround:
If you're running into this issue, there are two things you can do to mitigate this problem for now:
- Change `inherit! :search_paths` to `inherit! :complete` in your `Podfile`

If that doesn't work, or raises conflicts with other pods, try:
- Add `"${PODS_ROOT}/Firebase/Core/Sources"` to your **Tests target only** under `Build Settings -> Header Search Paths`

The root cause has to do with our internal build system and I'll track the progress at #58.

**Comment by JoGoFo-** [comment]
As per #58 this issue is resolved with CocoaPods 1.4.0

**Comment by jacobDaurizio** [comment]
I've had this problem and I found by running _sudo gem update_ in terminal and then adding _pod 'Firebase'_ to the podfile, I was bale to solve it. Hope this turns out the same for you. Good luck!

**Comment by jacobDaurizio** [comment]
Actually never mind the problem is back. Are you using Xcode 10?

**Comment by flexaddicted** [comment]
I have the same error.

**Comment by jacobDaurizio** [comment]
How do I do that?

**Comment by paulb777** [comment]
Some possible workarounds:

- Use CocoaPods 1.6.0
- Switch to the Xcode Legacy build system
- Add "${PODS_ROOT}/Firebase/CoreOnly/Sources" to the Tests target only under Build Settings -> Header Search Paths

If someone shares a reproducible example, I'll take a deeper look.

**Comment by flexaddicted** [comment]
@paulb777 Thanks for the reply.

For some strange reason, using `${PODS_ROOT}` does not resolve correctly.

**Comment by jacobDaurizio** [comment]
Sorry I’m really new to this. Could you tell me like a step by step like what things to press and where to type in Xcode for the ${PODS_ROOT} things? Your help is greatly appreciated.

**Comment by nebiros** [comment]
This is still happening. Confirmed with CocoaPods `1.6.0`. @shtnkgm workaround works. There's a way to set up this search path from the `Podfile`?

**Comment by AndresCianio** [comment]
Being the top search result probably makes this the best place to ask, eventhough the issue is closed.
@ryanwilson Issue is still happening. Should we stick to the mentioned workaround?

**Comment by LucaConfa** [comment]
Same here, issue still happening on CocoaPods `1.6.0`.
Confirming that @shtnkgm workaround was good for me!

**Comment by anonym24** [comment]
yes we should reopen this issue, still happens

**Comment by anonym24** [comment]
I have 
![image](https://user-images.githubusercontent.com/8851301/55291649-8e378780-53e9-11e9-861a-ec102af4191f.png)

But still I have this issue `Missing required module 'Firebase'`

![Screenshot at Mar 31 19-14-52](https://user-images.githubusercontent.com/8851301/55291656-aad3bf80-53e9-11e9-86ad-b0de95fc9ffd.png)

**Comment by anonym24** [comment]
I had to use this temporary solution https://stackoverflow.com/a/40524145/7767664 to fix it

**Comment by echamussy** [comment]
This is still an issue using cocoapods 1.6.2. The above workarounds have not helped me, it complains about the following Undefined Symbols:

![UploadCam___SchoolCam_Work_Package_-_Google_Docs_and_TutorialCatalogTests_swift](https://user-images.githubusercontent.com/259868/58795399-d9913080-85fa-11e9-859d-cdeed66fa6a9.png)

**Comment by morganchen12** [comment]
@echamussy this is a separate issue from the parent issue. The above issue is resolved with just fixing the header search paths; yours is one where you're missing symbols at link time. Please file a new issue and share a project that reproduces your error.

**Comment by rashdan** [comment]
+1

**Comment by ramunasjurgilas** [comment]
@morganchen12 For me it is still not clear how this could be fixed. Could you please explain how header search paths should be fixed.

I tried several suggestion, but they were not helping.

**Comment by paulb777** [comment]
@ramunasjurgilas See https://github.com/firebase/firebase-ios-sdk/issues/16#issuecomment-449701843

**Comment by MiZhen007** [comment]
I just wanna figure out whose bug it is, firebase? or cocoapods?

**Comment by paulb777** [comment]
I tested the reproducible test case above with Xcode 10.1 and CocoaPods 1.7.5 and it successfully finds the Firebase module.

We'll need an example that is reproducible with current tools to make more progress.

**Comment by ikeller96** [comment]
Wait so was there a fix? Still happening for me as well.

**Comment by paulb777** [comment]
@ikeller96 There was a CocoaPods fix in 1.6.0.  If it's still happening for you, we need a repro to investigate.

**Comment by ikeller96** [comment]
@paulb777 I am on CocoaPods version 1.5.3. I'll try updating and see if that works.

**Comment by ikeller96** [comment]
So @paulb777 I have CocoaPods v 1.6.0 now but I am getting the same error in a different test.

**Comment by morganchen12** [comment]
Have you tried deleting derived data since installing a new version of CocoaPods?

**Comment by ikeller96** [comment]
@morganchen12 Yes. Just tried that and I'm still getting the same error.

**Comment by morganchen12** [comment]
Can you share your project?

**Comment by ikeller96** [comment]
@morganchen12 This problem was occurring for me during an attempt at a swift 5 migration. Our company has decided to rebuild the app and therefore there will be no more releases so we are no longer going to try the swift 5 migration. Thank you for your help though.

**Comment by mikezucc** [comment]
Reposting an above reply from anonym24  for the weary traveler: 
"I had to use this temporary solution https://stackoverflow.com/a/40524145/7767664 to fix it"
