### ISSUE TITLE
Firebase 5.5.0's dependency on GoogleUtilities/* conflicts with GoogleTagManager 7.0.0's

### ISSUE THREAD

**Issue by cysp** [firebase/firebase-ios-sdk#1639]
### [READ] Step 1: Are you in the right place?

I think so? Judging by this previous issue for a similar problem: https://github.com/firebase/firebase-ios-sdk/issues/1384

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.4.1
  * Firebase SDK version: 5.5.0
  * Firebase Component: Analytics
  * Component version: 5.1.0

### [REQUIRED] Step 3: Describe the problem

FirebaseAnalytics declares a dependency on GoogleUtilities subspecs at version 5.2 but GoogleTagManager declares a dependency on the (old) umbrella spec at version 1.3.

#### Steps to reproduce:

With this Podfile:
```
platform :ios, '10.0'

target 'FirebaseDependencies' do
  use_frameworks!

  pod 'Firebase', '5.5.0'
  pod 'GoogleTagManager', '7.0.0'
end
```

- `pod install`

> Analyzing dependencies
> [!] CocoaPods could not find compatible versions for pod "GoogleUtilities":
>   In Podfile:
>     GoogleTagManager (= 7.0.0) was resolved to 7.0.0, which depends on
>       GoogleUtilities (~> 1.3)
> 
> Specs satisfying the `GoogleUtilities (~> 1.3)` dependency were found, but they required a higher minimum deployment target.

**Comment by paulb777** [comment]
Thanks for the report.  We plan to address this in the next release. In the meantime, a workaround is using the previous release of Firebase - `pod 'Firebase', '5.4.1'`

**Comment by paulb777** [comment]
Internally tracked at b/112272935

**Comment by paulb777** [comment]
Fixed with GoogleTagManager 7.1.0

**Comment by davidair** [comment]
We have released GoogleTagManager 7.1.0 fixing the dependency - the issue should be resolved now.

**Comment by cysp** [comment]
Hi. Thanks for the fast turnaround on this. 😁 

Unfortunately, however, I'm seeing some crashes on launch which I _think_ I have narrowed down to occurring when there are stored events from a previous session that have not been sent yet. (Though I'm not fully certain of that.)
I've reproduced it a couple of times by performing a few actions while in aeroplane mode, killing the app, leaving aeroplane mode and then launching a new app session.

The exception I'm seeing is in `-[TAGHitStore addPendingEvent:]`:
` -[APMValue encodeWithCoder:]: unrecognized selector sent to instance …`

Setting a breakpoint on `-addPendingEvent:` seems to indicate that the `APMValue` object is appearing as the value for the `_si` parameter of a `screen_view` event:
```
(lldb) po [$arg3 _ivarDescription]
<TAGPendingEvent: 0x28149e880>:
in TAGPendingEvent:
	_allowPassthrough (BOOL): NO
	_name (NSString*): @"_vs"
	_origin (NSString*): @"auto+gtm"
	_parameters (NSDictionary*): <__NSDictionaryM: 0x281a95820>
	_timestamp (NSDate*): <__NSDate: 0x2818d4810>
in NSObject:
	isa (Class): TAGPendingEvent (isa, 0x1a10545005d)

(lldb) po [$arg3 valueForKey:@"_parameters"]
{
    "_o" = auto;
    "_sc" = SGLaunchScreenViewController;
    "_si" = "-7837184538219958768";
}

(lldb) po [[[$arg3 valueForKey:@"_parameters"] objectForKey:@"_si"] class]
APMValue

…

2018-08-09 20:39:02.331511+1000 Westfield[2269:415757] -[APMValue encodeWithCoder:]: unrecognized selector sent to instance 0x281a957e0

(lldb) po 0x281a957e0
-7837184538219958768
```

**Comment by paulb777** [comment]
@cysp Thanks for the detailed report. We understand the issue and are investigating a solution.

**Comment by davidair** [comment]
We have just released GoogleTagManager 7.1.1. @cysp - can you please check if updating to it fixes the crash?

**Comment by cysp** [comment]
Thanks! I've been able to hit the previously-crashing codepath under the debugger and can confirm that it doesn't crash any longer. 😀

**Comment by blolo** [comment]
I'm still seeing the same exact crash , with 7.1.1 google tag manager , any suggestions? 

-[APMValue encodeWithCoder:]: unrecognized selector sent to instance 0x28257e780
default	14:29:50.260407 -0400
	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[APMValue encodeWithCoder:]: unrecognized selector sent to instance 0x28257e780'

**Comment by paulb777** [comment]
@blolo Tracking internally at b/116807869

**Comment by htcgh** [comment]
@blolo Which version of FirebaseAnalytics are you using?

**Comment by blolo** [comment]
@htcgh  we are using FirebaseAnalytics (5.1.0).

**Comment by htcgh** [comment]
@blolo Can you please verify if the crash still exists with FirebaseAnalytics 5.2.0?

**Comment by rpanadero** [comment]
Hi,

I'm also facing this issue with `pod 'GoogleTagManager', '7.1.0'`

`[APMValue encodeWithCoder:]: unrecognized selector sent to instance 0x28257e780
`

And I cannot update this dependency because my project is a Cordova one and if I update the dependency the project doesn't compile. Any workaround? I have tried several things, but the problem remains.

Thanks in advance!

**Comment by paulb777** [comment]
New issue opened at #3053. Please continue discussion there.
