### ISSUE TITLE
Crash in -[TAGHitStore addPendingEvent:]

### ISSUE THREAD

**Issue by ffittschen** [firebase/firebase-ios-sdk#2465]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: Version 10.1 (10B61)
  * Firebase SDK version: 5.16.0
  * Firebase Component: GoogleTagManager
  * Component version: 7.1.1

### [REQUIRED] Step 3: Describe the problem

We are observing a crash happening in `-[TAGHitStore addPendingEvent:]`.

#### Steps to reproduce:

We are not able to reproduce it yet.

Crashlog:
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x22f239eb8 __exceptionPreprocess
1  libobjc.A.dylib                0x22e433f18 objc_exception_throw
2  CoreFoundation                 0x22f14ef10 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x22f23f924 ___forwarding___
4  CoreFoundation                 0x22f2416f0 _CF_forwarding_prep_0
5  Foundation                     0x22fcc744c _encodeObject
6  Foundation                     0x22fbd88bc -[NSKeyedArchiver _encodeArrayOfObjects:forKey:]
7  Foundation                     0x22fc0639c -[NSDictionary(NSDictionary) encodeWithCoder:]
8  Foundation                     0x22fcc744c _encodeObject
9  Foundation                     0x22fc27e00 +[NSKeyedArchiver archivedDataWithRootObject:]
10 <Redacted>                     0x100a62a80 -[TAGHitStore addPendingEvent:]
11 <Redacted>                     0x100a53e30 __29-[TAGContainer processEvent:]_block_invoke
12 libdispatch.dylib              0x22ec3bb9c _dispatch_call_block_and_release
13 libdispatch.dylib              0x22ec3d134 _dispatch_client_callout
14 libdispatch.dylib              0x22ec4464c _dispatch_lane_serial_drain
15 libdispatch.dylib              0x22ec45194 _dispatch_lane_invoke
16 libdispatch.dylib              0x22ec4d480 _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x22ee3eb20 _pthread_wqthread
18 libsystem_pthread.dylib        0x22ee44dd4 start_wqthread
```

**Comment by paulb777** [comment]
Internally reported at b/127275684

**Comment by ffittschen** [comment]
Is there any update on this issue? We still see quite a lot of crashes due to this problem.

**Comment by ffittschen** [comment]
@paulb777 Is there an update to this issue?

**Comment by allenktv** [comment]
Hi @ffittschen , Are you using Swift or Obj-c for your app when using this? Are you using optionals or Swift enums/closures by any chance?

**Comment by ffittschen** [comment]
Hi @allenktv, we are using GTM in a Swift app and therefore we also use optionals, enums and closures. However, we have a protocol `TrackableValue` to constrain the parameter types we send with Firebase Analytics using a small wrapper `func logEvent(_ key: String, parameters: [String: TrackableValue])` to the following `String`, `Bool`, `Int`, `UInt64`, `Float`, `Double`.

**Comment by allenktv** [comment]
Hi @ffittschen, I see, thank you for responding. We cannot seem to reproduce it on our end and I do not believe this has been reported elsewhere. What percentage of your users are experiencing this and how often are you seeing these crashes?

**Comment by allenktv** [comment]
I believe we can close this issue for now due to lack of communication.

**Comment by surajthomask** [comment]
We are facing this issue in our production app. We can't reproduce this as well, but has been occurring 30 times for 24 users in last 7 days. Below is the resolved pod dependencies for firebase stack.

   - Firebase/Core (6.1.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.0.1)
  - Firebase/CoreOnly (6.1.0):
    - FirebaseCore (= 6.0.1)
  - Firebase/InAppMessagingDisplay (6.1.0):
    - Firebase/CoreOnly
    - FirebaseInAppMessagingDisplay (~> 0.14.0)
  - Firebase/Messaging (6.1.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.0.1)
  - Firebase/Performance (6.1.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.0.0)
  - Firebase/RemoteConfig (6.1.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.0.0)
  - FirebaseABTesting (3.0.0):
    - FirebaseCore (~> 6.0)
    - Protobuf (~> 3.5)
  - FirebaseAnalytics (6.0.1):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.1)
    - GoogleAppMeasurement (= 6.0.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.2.0)
  - FirebaseCore (6.0.1):
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Logger (~> 6.0)
  - FirebaseDynamicLinks (4.0.0):
    - FirebaseAnalyticsInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
  - FirebaseInAppMessaging (0.14.1):
    - FirebaseAnalyticsInterop (~> 1.2)
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
  - FirebaseInAppMessagingDisplay (0.14.0):
    - FirebaseCore (~> 6.0)
    - FirebaseInAppMessaging (>= 0.14.0)
  - FirebaseInstanceID (4.1.0):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebaseMessaging (4.0.1):
    - FirebaseAnalyticsInterop (~> 1.1)
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Reachability (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
    - Protobuf (~> 3.1)
  - FirebasePerformance (3.0.0):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
    - FirebaseRemoteConfig (~> 4.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/ISASwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseRemoteConfig (4.0.0):
    - FirebaseABTesting (~> 3.0)
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.0)
    - GoogleUtilities/Environment (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - Protobuf (~> 3.5)

**Comment by surajthomask** [comment]
@allenktv  Is there any update on this issue? We are still facing these crashes and is really messing up the app stability metrics.

As an additional information, we do not pass nil to Firebase as value. In all places we are passing non-optional Any as the value and string as key. 

We would really appreciate it, if this issue is resolved asap.

**Comment by maximeavonvc** [comment]
Hey everyone !

We have this same crash since 2 weeks, mainly on iPhone with iOS 13 and firebase 6.7.0.
It appears when we added a lot of new tracking...

What is the situation about this crash ?

**Comment by surajthomask** [comment]
@maximeavonvc Apparently no one is looking into this :-( After my last comment on October 29th, we had this crash occurring 653 times affecting 566 users, that is single crash taking up more than 70% of all crashes, and there is literally nothing we can do about it, other than hoping that Firebase engineers picks this up.

@morganchen12 Will you be able to prioritise this and assign to someone for action, since the ticket has been unassigned almost a month back.

**Comment by alex-ost** [comment]
+1, it's major crash for us.

**Comment by TSCombine** [comment]
We have a lot of them, this is from a Swift project running on iOS 13
`
[__SwiftValue encodeWithCoder:]: unrecognized selector sent to instance 0x282a69f20

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1998eea48 __exceptionPreprocess
1  libobjc.A.dylib                0x199615fa4 objc_exception_throw
2  CoreFoundation                 0x1997f25a8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1998f2af4 ___forwarding___
4  CoreFoundation                 0x1998f4a7c _CF_forwarding_prep_0
5  Foundation                     0x199c9e144 _encodeObject
6  Foundation                     0x199bb810c -[NSKeyedArchiver _encodeArrayOfObjects:forKey:]
7  Foundation                     0x199be313c -[NSDictionary(NSDictionary) encodeWithCoder:]
8  Foundation                     0x199c9e144 _encodeObject
9  Foundation                     0x199c03b88 +[NSKeyedArchiver archivedDataWithRootObject:]
10 Sanistaal                      0x104d90f20 -[TAGHitStore addPendingEvent:]
11 Sanistaal                      0x104d825d8 __29-[TAGContainer processEvent:]_block_invoke
12 libdispatch.dylib              0x1995ba610 _dispatch_call_block_and_release
13 libdispatch.dylib              0x1995bb184 _dispatch_client_callout
14 libdispatch.dylib              0x199567404 _dispatch_lane_serial_drain$VARIANT$mp
15 libdispatch.dylib              0x199567df8 _dispatch_lane_invoke$VARIANT$mp
16 libdispatch.dylib              0x199571314 _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x19960ab88 _pthread_wqthread
18 libsystem_pthread.dylib        0x19960d760 start_wqthread`

**Comment by Dertif** [comment]
Same here, this is our top crash with 90% of our app crashes.
@allenktv any plan on working to fix this any time soon ?

**Comment by yellowgmk** [comment]
We have the same problem here, it is also our main cause of crash in the application. It seems this problem has been going for a year now and has never been investigated because the issue keeps getting closed?

**Comment by morganchen12** [comment]
The Tag Manager team has prepared a fix internally, but we do not know when it will be released.

Unfortunately, this has been the case for a while now.

**Comment by surajthomask** [comment]
@morganchen12  I'm relieved to know that this is being addressed by the team. Can you please push for a release of this fix on priority? We would appreciate it over the moon. This crash is leaving our stability metrics in the bin. 

Hoping for the best news..!

Last 90 days ->
<img width="470" alt="Screenshot 2020-02-12 at 11 25 11 AM" src="https://user-images.githubusercontent.com/631760/74312075-58de2300-4d8a-11ea-989c-a669724ca05f.png">

**Comment by FDavidse20** [comment]
@morganchen12 This crash is also by far our number 1 crash. We would really appreciate it enormously if there is a fix for this!
Any ideas if that might happen anytime soon?

**Comment by morganchen12** [comment]
We've upped the priority of the internal ticket and continued to bug the Tag Manager team to release the fix, but we do not know when their next release will arrive.

If you're affected by this bug, please share the amount/percentage of crashing sessions attributed to this bug. If there's enough crashes across a significant number of apps (which it seems like there is), it will help us raise the priority further.

I understand that this last step should not be necessary and that it's frustrating watching Firebase crash your app. Sorry everyone for the inconvenience.

**Comment by FDavidse20** [comment]
@morganchen12 Thank you for your reply. For our app we've had to actually pause the phased rollout for a new version, because we got a velocity alert from Crashlytics for this crash. The app is rolled out to only 1% of the users, but it causes roughly a 1000 crashes a day. Which is already about 70% of all current crashes for all of our app versions. 
So we can't resume rollout for our current version of our app, because then the crashes would simply explode.

**Comment by Dertif** [comment]
<img width="1262" alt="Capture d’écran 2020-02-14 à 13 25 52" src="https://user-images.githubusercontent.com/1146704/74531780-e4dc8000-4f2d-11ea-8b86-7a38039a9706.png">


This is in the last 90 days. It represents 60% of total crashes of the same period

**Comment by maximeavonvc** [comment]
Hi everyone !
On our app, `This issue has 16437 crashes affecting 13149 users` for the last 90 days.
And this is our number 1 crash...

Happy if that this crash may be fixed in a short future.

**Comment by Dadoufi** [comment]
Hi,
It's also the number one crash on our app...

Would really apreciate if there was a fix for this issue as soon as possible.

**Comment by FDavidse20** [comment]
@morganchen12, are they any updates yet about when the fix is going to be released? 
This issue still causes a lot of crashes for our app. And drops the crash free user percentage by more then 5%. It's by far our number one crash.

**Comment by morganchen12** [comment]
Hey all. At this point I have bugged the tag manager team to the best of my ability and further agitating them will not speed up their release. The release is still in progress, but I do not have an ETA.

Fortunately, there is a workaround: this issue can be avoided by checking every Analytics event log call your app is making and ensuring that there are no Swift-only types (structs, non-`@objc` classes, and pure enums without a string or numeric raw value). This is potentially a lot of Analytics calls to check.

I'll try to add some diagnostic code to the Analytics SDK so it will emit warning logs if you're logging events with pure Swift values.

**Comment by morganchen12** [comment]
Google-internal change cr/297637641 adds an Analytics warning when you log an event with parameters containing a Swift value that's not representable as an ObjC Foundation type, and is slated for the next release. Hopefully this will make it easier to debug while we continue to wait for a Tag Manager release.

**Comment by surajthomask** [comment]
@morganchen12 Thank you for bugging the tag manager team, and we do really appreciate pointing in Swift-only types direction. We have identified one event passing an enumeration case to analytics layer, and is fixing it now. And the timeline from which crash started appearing matches with the time we added that event. 
Once again, thank you very much. Hopefully this crash will go away with our next app release.

**Comment by yellowgmk** [comment]
For our application, we have 41,4% crashes and all crashes are due to Firebase/GTM.
Also, I can't find a place in our code where we would pass a pure Swift type to Firebase. All values that we pass are Strings.

**Comment by morganchen12** [comment]
@yellowgmk if it's not related to Swift types, can you share the stack trace?

**Comment by yellowgmk** [comment]
Only once I could have the crash while the debugger was attached:

<img width="512" alt="Screenshot 2020-03-02 at 16 56 06" src="https://user-images.githubusercontent.com/18701089/75756321-c00b4980-5d30-11ea-8b02-7fee3de585a8.png">

**Comment by ahmedAlmasri** [comment]
+1

**Comment by morganchen12** [comment]
@yellowgmk do you have the exception message as well, printed after the crash? Without it, it's not possible to tell if this is the same crash or a different one.

**Comment by paulb777** [comment]
GoogleTagManager 7.1.3 was released today with a fix for this issue. Let us know how it goes.

**Comment by morganchen12** [comment]
Hey all, the TagManager fix was pushed at the end of last week. [Here's the podspec](https://github.com/CocoaPods/Specs/tree/master/Specs/9/5/6/GoogleTagManager/7.1.3); please update and test your apps.

Note that the Swift-only value check will still be included in the next Firebase release, which should be out soon as well.

I'm going to close this issue since the fix is released, but if it regresses please continue to comment here and I'll reopen it. Thanks everyone for your patience.

**Comment by yellowgmk** [comment]
We've embedded GoogleTagManager 7.1.3 in our application, but it doesn't seem to solve the problem.
We have trouble reproducing the problem, but our users have it consistently and we have about 50% crashes in our user base, all caused by this issue.
- The crash always happens at app startup.
- Usually the application crashes once at app startup and then it works the second time the user launches it.
- The crash happens more often in production environment rather than in development environment, that's why we have a hard time reproducing it.
- It looks like the crash often happens after updating the application from one version to another.
- The error is always `Fatal Exception: NSInvalidArgumentException
-[APMValue encodeWithCoder:]: unrecognized selector sent to instance 0xXXXXXXXX`, either originating from `-[TAGHitStore addPendingEvent:]` or from `
-[NSOrderedSet initWithSet:copyItems:]`.
- On a case where I could reproduce the crash while the debugger was attached, I got the stack trace that I posted here a few days ago, where we can see the queue path of the crash across operations.

**Comment by morganchen12** [comment]
@yellowgmk can you update to the latest version of Analytics and then try to force the crash by logging a Swift-only type?

**Comment by surajthomask** [comment]
I can confirm that we don't have this crash anymore. So the issue was, as mentioned by @morganchen12  that we were passing a swift only type, in our case an enumeration case to the Firebase. Once we replaced that swift only type with it's rawValue, the crash disappeared. 

If you have a central place where all analytics calls are routed through it's easy to find where these crashes are coming from. Convert the analytics info dictionary to Data with `JSONSerialization.data(withJSONObject:, options:)`. And look for any crashes. If either key or value is a swift only type, it will crash. So fix them up. Hope this helps someone.
