### ISSUE TITLE
Broken Auth Integration Tests

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#3022]
The Auth Integration Tests are broken and causing the Travis post-submit builds to fail. From https://travis-ci.org/firebase/firebase-ios-sdk/jobs/533793926

    ✗ testUpdatingUsersEmail, ((auth.currentUser.email) equal to (kOldUserEmail)) failed: ("(null)") is not equal to ("olduseremail@iosapitests.com")
    ✗ testUpdatingUsersEmail, ((apiError) == nil) failed: "Error Domain=FIRAuthErrorDomain Code=17007 "The email address is already in use by another account." UserInfo={NSLocalizedDescription=The email address is already in use by another account., FIRAuthErrorUserInfoNameKey=ERROR_EMAIL_ALREADY_IN_USE}"
    ✗ testUpdatingUsersEmail, Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Created account with email and password.".
    ✗ testUpdatingUsersEmail, ((apiError) == nil) failed: "Error Domain=FIRAuthErrorDomain Code=17007 "The email address is already in use by another account." UserInfo={NSLocalizedDescription=The email address is already in use by another account., FIRAuthErrorUserInfoNameKey=ERROR_EMAIL_ALREADY_IN_USE}"
    ✗ testUpdatingUsersEmail, ((auth.currentUser.email) equal to (kNewUserEmail)) failed: ("(null)") is not equal to ("newuseremail@iosapitests.com")
    ✗ testUpdatingUsersEmail, Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Delete current user finished.".
    ✗ testUpdatingUsersEmail, failed - Failed to wait for expectations in deleting user. Error: The operation couldn’t be completed. (com.apple.XCTestErrorDomain error 0.)
AnonymousAuthTests

**Comment by renkelvin** [comment]
There was an issue of deleting user with our backend. It's fixed and rerun should work now. Verified locally.

**Comment by paulb777** [comment]
Thanks @renkelvin. We're green again in the [latest build](https://travis-ci.org/firebase/firebase-ios-sdk/builds/533938094).

**Comment by paulb777** [comment]
This issue is back and breaking the builds since sometime yesterday.

**Comment by renkelvin** [comment]
The issue should be fixed now.
Since all our testing environments (sdks and backends) share a single Firebase project, there could be inconsistency of the user accounts. I'm considering use a dedicated project for iOS SDK.

**Comment by paulb777** [comment]
Thanks!  A dedicated project sgtm.  Should we leave this issue open to track or do you want to track separately?

**Comment by renkelvin** [comment]
It should be tracked separately. I'll discuss the plan with our TL and create an internal bug.

**Comment by paulb777** [comment]
The integration tests broke CI again all weekend.

**Comment by renkelvin** [comment]
https://github.com/firebase/firebase-ios-sdk/pull/3125

**Comment by renkelvin** [comment]
I noticed that there more tests broken and I'm working on that.

**Comment by renkelvin** [comment]
Auth apis broken due to backend changes. Disable all tests for now. https://github.com/firebase/firebase-ios-sdk/pull/3128

**Comment by renkelvin** [comment]
Reenabled. https://github.com/firebase/firebase-ios-sdk/pull/3318
