### ISSUE TITLE
Firebase In App message is not coming when app is in foreground on iPhone

### ISSUE THREAD

**Issue by abdulshamim** [firebase/firebase-ios-sdk#3391]
Firebase In App message is not coming when app is in foreground ios swift. And also it sometime coming and some time not coming.

Please help Iy would be great help.
Thanks and regards
Abdul

**Comment by abdulshamim** [comment]
Xcode Version: 10.1 (10B61)
Firebase SDK version: 6.4.0
Firebase Component: In-App Messaging
FirebaseInAppMessaging (0.15.1)
FirebaseInAppMessagingDisplay (0.15.0)
FirebaseInstanceID (4.2.1)

Firebase In App message is not coming when app is in foreground on iPhone. 
And also it sometime coming and some time not coming.

**Comment by morganchen12** [comment]
We fixed a similar issue in Firebase 6.5.0. Please try upgrading and seeing if the new version fixes your issue.

**Comment by abdulshamim** [comment]
Firebase 6.5.0
FirebaseCore 6.1.0
FirebaseInAppMessaging 0.15.2
FirebaseInAppMessagingDisplay 0.15.2
FirebaseInstanceID 4.2.2

I had updated to pods version, but still not receiving  In-App messages in foreground.
Also When I'm publishing campaign it is not coming, but when I am testing using Instance ID it is working fine.

**Comment by abdulshamim** [comment]
Any update? @christibbs @morganchen12

**Comment by christibbs** [comment]
Looking into this shortly. Do you get any errors in the logs when you try getting messages locally? Try searching for `[Firebase/InAppMessaging]` in the logs (assuming you're running with the `-FIRDebugEnabled` command line argument).

**Comment by abdulshamim** [comment]
Yes, FIRDebugEnabled enabled in edit scheme.
When app is launching from background/Not running messages comes but when app is in foreground still not coming. I am attaching screen shots which might be helpful for you. 

![Screenshot 2019-07-25 at 9 39 06 AM](https://user-images.githubusercontent.com/13666188/61998408-2ceca000-b0cd-11e9-994b-f38211cb5166.png)
![Screenshot 2019-07-28 at 12 06 10 AM](https://user-images.githubusercontent.com/13666188/61998411-34ac4480-b0cd-11e9-865b-acb72f79e64e.png)

https://drive.google.com/file/d/15g-STL7ojBlhqwFsewCDZnffmKKZhxEF/view?usp=sharing

**Comment by christibbs** [comment]
Sorry for the delay, I was out of the office. From the video, it looks like the behavior is expected. In test on device mode, you need to background and foreground the app for the notification to appear.

Even in published campaigns, in app messages that are set to appear on foreground only trigger when app goes from being in a background state to being foregrounded. So if you publish an `on_foreground` campaign, you'd need to background the app in the simulator, then open again. In production, this is a "next time the user opens the app" kind of logic.

You can also publish a campaign with a custom event (f/e: `on_button_tapped`) to appear and trigger that event using [this method](https://firebase.google.com/docs/reference/swift/firebaseinappmessaging/api/reference/Classes/InAppMessaging#triggerevent_:).

**Comment by abdulshamim** [comment]
Thank you so much @christibbs

**Comment by prakhar1989** [comment]
Test
