### ISSUE TITLE
How to set AB Testing version

### ISSUE THREAD

**Issue by ilyon** [firebase/firebase-ios-sdk#3624]
We are using AB Testing and we have learned some information from this question (https://stackoverflow.com/questions/57437506/firebase-ab-test-regex-for-ios-app-version-not-working/57475586# 57475586), the version number is replaced by the build number, but recently we found in the new AB Testing setting, the regular expression needs to match the version number, if the regular expression is set according to the build number, the amount of users affected is 0, which one to fill in, the version number or the build number?
![61566185030_ pic_hd](https://user-images.githubusercontent.com/2276323/63237266-d4e02e00-c273-11e9-9f54-4d680da94e48.jpg)

**Comment by SinanKadavath** [comment]
@ilyon is this a Notification experiment?

**Comment by ilyon** [comment]
> @ilyon is this a Notification experiment?

No, it's a remote config experiment.

**Comment by christibbs** [comment]
Looking into this, sorry for the delay.

**Comment by ethan021021** [comment]
Not sure if this is known or not but the same issue occurs with remote config as well:

https://stackoverflow.com/a/41465959

Would be great to see a fix for this! 👍

**Comment by christibbs** [comment]
This is a Firebase remote config issue, as referenced in https://stackoverflow.com/a/41465959. It is currently being worked on.

**Comment by christibbs** [comment]
The Remote Config issue has been fixed. For targeting, you should use `CFBundleVersion`, which maps to the `Build` field in Xcode project settings > Targets > General > Identity.

**Comment by reshadf** [comment]
@christibbs I am still having issues here. It is not working for me it is always returning true. I have updated to the most recent version of the sdk. 

Also, on another note. Why do you guys use CFBundleVersion? I think both CFBundleVersion and CFBundleShortVersionString should work. We use the latter and CFBundleVersion is rarely used in our app. 

Is it possible to make them both actually work?

**Comment by christibbs** [comment]
@reshadf sorry for the delay. Going with `CFBundleVersion` for targeting was a product decision, we currently don't have any plans to support both.

For your issue (always returning true): are you seeing that the experiment always shows up regardless of targeted version?
