### ISSUE TITLE
iOS 13 kept killing app instance after app entering background.

### ISSUE THREAD

**Issue by su3** [firebase/firebase-ios-sdk#3759]
[REQUIRED] Step 2: Describe your environment
Xcode version: 11 Beta 7
iOS: 13.1 (iOS 13 Beta 8 has the same issue)
Firebase SDK version: 6.7.0
Firebase Component:
Firebase: 6.7.0
Firebase/Analytics

Use cocopod like this:
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Analytics' '6.7.0'

[REQUIRED] Step 3: Describe the problem
iOS (13.1) kept killing app instance after app entering background.

Steps to reproduce:
1. Integrate Firebase Analytics into app like:
        FirebaseApp.configure()
        Fabric.sharedSDK().debug = false
        Fabric.with([Crashlytics.self])

        ...
        Analytics.logEvent...
    Build and run the app (detach XCode if it's started from XCode).

2. Put app into background (swipe up or press Home button) and turn off phone screen for several minutes.

3. Wake up the phone and tap the app icon to bring the app to foreground:
Expected:
The app is recovered from previous suspended state.

Got:
The previous app instance was destroyed by iOS and a new app instance is created.

If we remove all Firebase pods as well as the code referencing them from our project, we got expected results - the app is able to survive from background state.

**Comment by morganchen12** [comment]
@su3 can you share the stack trace for the background kill?

**Comment by su3** [comment]
@morganchen12 No crash reports. No stack trace. It's like an normal termination except it just shouldn't be terminated by the OS.
Any chance it's caused by leaking background tasks inside Firebase?

**Comment by morganchen12** [comment]
That was a bug fixed recently in Firebase. Background termination should still leave a stack trace on the device, which you can access from the Devices menu in Xcode. The exception code is usually `0x8badf00d`.

It's unlikely this bug is a regression of the background tasks issue since that was released relatively recently.

cc @mikehaney24

**Comment by morganchen12** [comment]
Also @su3 does this occur on iOS 12 or just 13?

**Comment by su3** [comment]
@morganchen12 It's always reproducible on iOS 13. Not an issue on 12.

**Comment by mccarron** [comment]
@su3 do you see `libdyld.dylib` or `GULLoggingClientQueue` crashes in Crashlytics (or similar?) I am getting about 10 a week right now from iOS 13 users and I think this issue is related. 

It's always iOS 13 users and always the app is backgrounded. 

```
Crashed: GULLoggingClientQueue
0  libdyld.dylib                  0x1988d7d8c <redacted> + 44
1  ???                            0x0 (Missing)
2  ???                            0x0 (Missing)
3  ???                            0x0 (Missing)
4  ???                            0x6636bc81988e2c00 (Missing)
5  ???                            0x0 (Missing)
6  ???                            0x593b0c81986cc000 (Missing)
7  ???                            0x0 (Missing)
8  ???                            0x0 (Missing)
9  libdispatch.dylib              0x198787bb0 <redacted> + 32
10 ???                            0x2a27128198789000 (Missing)
11 ???                            0x2216a1019878f400 (Missing)
12 ???                            0x7f7a440198790000 (Missing)
13 ???                            0x0 (Missing)
14 ???                            0x0 (Missing)
15 ???                            0x2302c781987f4c00 (Missing)
```

**Comment by morganchen12** [comment]
@mccarron are you able to share a symbolicated stack trace?

**Comment by mccarron** [comment]
@morganchen12 I would if I had one, that's the "symbolicated" one. It's all Crashlytics shows me for the crashes like this one. 

![Screen Shot 2019-09-06 at 6 36 55 PM](https://user-images.githubusercontent.com/45654/64466063-5f7ab700-d0d5-11e9-911a-f5ae71b3659b.png)

**Comment by hamedh** [comment]
It took a long time to track down, but this is happening for my app too on iOS 13. The cause is Firebase, simply removing Firebase makes the app survive background state. Otherwise it gets killed by the OS

**Comment by paulb777** [comment]
@maksymmalyhin Any thoughts about how GULLoggingClientQueue could crash in the background on iOS 13?

**Comment by adamup928** [comment]
I'm getting these background crashes, too.  Seems to be an issue for iOS 12 as well, but only when running a build that was created using the iOS 13 SDK.  

My symptoms are identical to the parent post by @su3, but I'm on Firebase SDK version 6.8.1.  

When I pull the device logs using Xcode, there are no .ips files generated for these crashes.  If I remove the Firebase SDK, the app does not crash after backgrounding.  

I assume this crash is a watchdog timer exception, probably a termination code of `0x8badf00d`, but I can't find any logs to confirm it.

**Comment by delort** [comment]
IOS 13 has changes the location and where the app lifecycle is managed. Checkout: https://github.com/firebase/firebase-ios-sdk/issues/3521

**Comment by su3** [comment]
Do you have an ETA on the fix? Thank you!

@adamup928 Yeah, exactly the same symptoms here. If we build our app with latest Xcode 11 GM version, our app suffers the same background kill even on iOS 12 which didn't happen with Xcode 10 built app.

**Comment by su3** [comment]
@mikehaney24 I believe this issue has been fixed in GDTCCTS 1.0.4. Thank you for the effort.

**Comment by adamup928** [comment]
Updating to GDTCCTS 1.0.4 (and Firebase 6.8.1) seems to have resolved the issue for iOS devices; however, we're still seeing `0x8badf00d` terminations on iPadOS 13.1.  Reverting to Firebase `6.4.0` (and its dependencies) causes the terminations to stop.  The terminations are not as predictable; they do not occur on each and every backgrounding of the application anymore.  

Is anybody else experiencing this with the updated GDTCCTS?

```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001b5ea78e8 __ulock_wait + 8
1   libsystem_platform.dylib      	0x00000001b5dc2040 _os_unfair_lock_lock_slow + 196
2   libobjc.A.dylib               	0x00000001b5dddd18 look_up_class + 88
3   CoreFoundation                	0x00000001b5f8b1f4 -[NSInvocation invoke] + 204
4   UIKitCore                     	0x00000001ba4b2060 -[_UIActionWhenIdle invoke] + 80
5   CoreFoundation                	0x00000001b6034a20 _runLoopObserverWithBlockContext + 40
6   CoreFoundation                	0x00000001b603667c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
7   CoreFoundation                	0x00000001b603131c __CFRunLoopDoObservers + 420
8   CoreFoundation                	0x00000001b60318cc __CFRunLoopRun + 1292
9   CoreFoundation                	0x00000001b6031098 CFRunLoopRunSpecific + 480
10  GraphicsServices              	0x00000001c0193534 GSEventRunModal + 108
11  UIKitCore                     	0x00000001ba150b3c UIApplicationMain + 1940
12  [redacted]                 	0x0000000104c6bc18 main + 2309144 (main.m:16)
13  libdyld.dylib                 	0x00000001b5eb0f30 start + 4
```

**Comment by mikehaney24** [comment]
Is this reproducible locally? Device? Simulator? Sending me the device console logs (not the app logs in Xcode) filtered on your app would be especially useful.

**Comment by adamup928** [comment]
Yes, it's reproducible locally.  Device is an iPad Mini (5th generation).  Not testing on the simulator.  I haven't pushed to a beta channel, yet, either.

I've removed Firebase/Analytics because I have a suspicion (https://forums.developer.apple.com/thread/122075 + another crash log below) something's going on in there, and I'm currently testing that configuration locally.  

I'll attempt to capture filtered console logs and get them to you.

Here's another crash log:
```

Date/Time:           2019-09-17 15:01:11.5242 -0500
Launch Time:         2019-09-17 14:33:25.5174 -0500
OS Version:          iPhone OS 13.1 (17A5837a)
Release Type:        Beta
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_MEMORY_ERROR at 0x0000000102c98149
VM Region Info: 0x102c98149 is in 0x102c98000-0x102d74000;  bytes after start: 329  bytes before end: 900790
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      __LINKEDIT             0000000102c40000-0000000102c98000 [  352K] r--/r-- SM=COW  ...[redacted]
--->  mapped file            0000000102c98000-0000000102d74000 [  880K] r--/rw- SM=COW  ...t_id=d1ac069d
      __TEXT                 0000000102d74000-0000000102da8000 [  208K] r-x/rwx SM=COW  .../AFNetworking

Thread 9 name:  Dispatch queue: com.apple.network.connections
Thread 9 Crashed:
0   libdyld.dylib                 	0x00000001b5eb1df0 dyld3::closure::Image::containsAddress+ 7664 (void const*, void const*, unsigned char*) const + 44
1   libdyld.dylib                 	0x00000001b5ebd254 invocation function for block in dyld3::AllImages::infoForNonCachedImageMappedAt(void const*, void + 53844 (dyld3::LoadedImage const&, unsigned char) block_pointer) const + 88
2   libdyld.dylib                 	0x00000001b5ebd254 invocation function for block in dyld3::AllImages::infoForNonCachedImageMappedAt(void const*, void + 53844 (dyld3::LoadedImage const&, unsigned char) block_pointer) const + 88
3   libdyld.dylib                 	0x00000001b5ebd13c dyld3::AllImages::infoForNonCachedImageMappedAt(void const*, void + 53564 (dyld3::LoadedImage const&, unsigned char) block_pointer) const + 228
4   libdyld.dylib                 	0x00000001b5ebce58 dyld3::AllImages::infoForImageMappedAt+ 52824 (void const*, dyld3::MachOLoaded const**, unsigned long long*, char const**) const + 388
5   libdyld.dylib                 	0x00000001b5ec1b2c dyld3::dyld_image_header_containing_address+ 72492 (void const*) + 72
6   libsystem_trace.dylib         	0x00000001b5ca3820 _os_log_impl_flatten_and_send + 2016
7   libnetwork.dylib              	0x00000001b84b5154 nw_socket_handle_socket_event + 4860
8   libdispatch.dylib             	0x00000001b5d6300c _dispatch_client_callout + 20
9   libdispatch.dylib             	0x00000001b5d6578c _dispatch_continuation_pop + 408
10  libdispatch.dylib             	0x00000001b5d75f18 _dispatch_source_invoke2 + 892
11  libdispatch.dylib             	0x00000001b5d758c4 _dispatch_source_invoke + 428
12  libdispatch.dylib             	0x00000001b5d6b004 _dispatch_workloop_invoke2 + 572
13  libdispatch.dylib             	0x00000001b5d6ab20 _dispatch_workloop_invoke + 428
14  libdispatch.dylib             	0x00000001b5d72f20 _dispatch_workloop_worker_thread + 580
15  libsystem_pthread.dylib       	0x00000001b5dc8aa0 _pthread_wqthread + 280
16  libsystem_pthread.dylib       	0x00000001b5dcec78 start_wqthread + 8
```

**Comment by adamup928** [comment]
Even without Firebase/Analytics, I'm still seeing a watchdog timer violation (same device as before):

```
Date/Time:           2019-09-17 17:44:16.0731 -0500
Launch Time:         2019-09-17 17:18:36.2700 -0500
OS Version:          iPhone OS 13.1 (17A5837a)
Release Type:        Beta
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGKILL)
Exception Subtype: KERN_MEMORY_ERROR at 0x0000000100a67898
VM Region Info: 0x100a67898 is in 0x100990000-0x100a68000;  bytes after start: 882840  bytes before end: 1895
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC metadata        000000010098c000-0000000100990000 [   16K] r--/rwx SM=PRV  
--->  mapped file            0000000100990000-0000000100a68000 [  864K] r--/rw- SM=COW  ...t_id=cd46e49d
      __TEXT                 0000000100a68000-0000000100a74000 [   48K] r-x/rwx SM=COW  

Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: application<redacted>:517 exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 49.670 (user 49.670, system 0.000), 13% CPU", | "Elapsed application CPU time (seconds): 11.875, 3% CPU" | )
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libdyld.dylib                 	0x00000001b5eb33d0 dyld3::closure::ObjCStringTable::hash+ 13264 (char const*, unsigned long) const + 16
1   libdyld.dylib                 	0x00000001b5eb3a60 dyld3::closure::ObjCStringTable::getIndex+ 14944 (char const*) const + 56
2   libdyld.dylib                 	0x00000001b5eb37e4 dyld3::closure::ObjCStringTable::getPotentialTarget+ 14308 (char const*) const + 24
3   libdyld.dylib                 	0x00000001b5eb3ad0 dyld3::closure::ObjCClassDuplicatesOpt::getClassLocation+ 15056 (char const*, objc_opt::objc_opt_t const*, void*&) const + 48
4   libdyld.dylib                 	0x00000001b5ec0d08 dyld3::AllImages::forEachObjCClass(char const*, void + 68872 (void*, bool, bool*) block_pointer) const + 76
5   libobjc.A.dylib               	0x00000001b5df1f98 getPreoptimizedClass + 164
6   libobjc.A.dylib               	0x00000001b5ddcec0 getClassExceptSomeSwift+ 52928 (char const*) + 24
7   libobjc.A.dylib               	0x00000001b5dddd20 look_up_class + 96
8   CoreFoundation                	0x00000001b5f8b1f4 -[NSInvocation invoke] + 204
9   UIKitCore                     	0x00000001ba4b2060 -[_UIActionWhenIdle invoke] + 80
10  CoreFoundation                	0x00000001b6034a20 _runLoopObserverWithBlockContext + 40
11  CoreFoundation                	0x00000001b603667c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
12  CoreFoundation                	0x00000001b603131c __CFRunLoopDoObservers + 420
13  CoreFoundation                	0x00000001b60318cc __CFRunLoopRun + 1292
14  CoreFoundation                	0x00000001b6031098 CFRunLoopRunSpecific + 480
15  GraphicsServices              	0x00000001c0193534 GSEventRunModal + 108
16  UIKitCore                     	0x00000001ba150b3c UIApplicationMain + 1940
17  nonprintable-path             	0x000000010029a510 0x100068000 + 2303248
18  libdyld.dylib                 	0x00000001b5eb0f30 start + 4
```

**Comment by pradipaub36** [comment]
I'm having Firebase SDK v6.8.1 and getting the same issue, Whenever change app state from background to foreground the app starts from splash screen instead of the existing screen.

**Comment by ivovdry** [comment]
Had similar crash on iOS 13. Was connected to Data Protection Complete mode: https://forums.developer.apple.com/thread/122858. After changing to NSFileProtectionCompleteUntilFirstUserAuthentication works as expected.

**Comment by travischapman** [comment]
Firebase 6.9.0
GoogleDataTransportCCTSupport 1.1.0

Issue is still present in iOS 13.1, but absent in iOS 12
`Can't end BackgroundTask: no background task exists with identifier 18 (0x12), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.`

**Comment by morganchen12** [comment]
@travischapman can you file a new issue? This looks slightly different than the parent issue, since it's not resulting in a crash.

**Comment by mikehaney24** [comment]
@travischapman @morganchen12 This is an iOS issue. If you create a completely empty project and run it and background the app, it will say this.

![image](https://user-images.githubusercontent.com/1082754/66428019-11a1e900-e9ca-11e9-93bc-61ceb6d27dd4.png)
