### ISSUE TITLE
[ISSUE] Deprecated API Usage - Apple may deny builds

### ISSUE THREAD

**Issue by filipealva** [firebase/firebase-ios-sdk#3780]
#3011 # [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.6.0
  * Firebase Component: Core
  * Component version: 6.6.0

#### Steps to reproduce:

What happened? 

When I upload a build for TestFlight Apple advises me that I'm making use of a deprecated API and they still start rejecting builds like that. I investigated and it's Firebase iOS SDK making some calls to `UIWebView`. 

What's the suggested solution? How can I be safe that my build will not be denied because of Firebase's SDK? 

This could be a description, log/console output, etc.

```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```

**Comment by ryanwilson** [comment]
Thank you for the report - this is a duplicate of #3722 and is fixed by #3723. The release should be out today if all goes well.

**Comment by paulb777** [comment]
I'll reopen, since while the issue in this repo with DynamicLinks is being fixed in Firebase 6.8.0, the issue still remains in Crashlytics(b/140424496) and FirebaseML(b/140396933).  

This was previously reported at https://github.com/firebase/quickstart-ios/issues/788. I'll close that one and keep it open here.

**Comment by paulb777** [comment]
b/140559063 is another related internal tracking bug

**Comment by samedson** [comment]
Just released Crashlytics 3.14.0 which should fix this issue

**Comment by morganchen12** [comment]
If anyone sees this issue after Crashlytics 3.14.0, please comment here and we'll re-open.

**Comment by OnurVar-OSF** [comment]
@morganchen12 , @paulb777 

Our app (written on React-Native but using`FirebaseMLVision (0.18.0)`) is still showing that `UIWebView` being used in `FirebaseMLCommon (0.18.0)`,
![Screen Shot 2019-09-24 at 17 16 41](https://user-images.githubusercontent.com/36157923/65519820-49e7f880-deef-11e9-8adc-bdcbc66294f7.png)

**Comment by OnurVar** [comment]
@morganchen12 , @paulb777 

Our app (written on React-Native but using`FirebaseMLVision (0.18.0)`) is still showing that `UIWebView` being used in `FirebaseMLCommon (0.18.0)`

![Screen Shot 2019-09-24 at 17 16 41](https://user-images.githubusercontent.com/4017312/65519945-7e5bb480-deef-11e9-8b2f-cbe639bb9cc2.png)

**Comment by paulb777** [comment]
Yes- sorry the issue still exists in MLKit and Ads (#3862) - reopening here for MLKit

**Comment by ryanwilson** [comment]
Firebase 6.10.0 was just released and MLKit should be fixed. Please re-open if you find otherwise!
