### ISSUE TITLE
Firebase InAppMessaging messageDisplaySuppressed not working properly.

### ISSUE THREAD

**Issue by fvonk** [firebase/firebase-ios-sdk#4028]
* Xcode version: 11
  * Firebase SDK version: FirebaseInAppMessagingDisplay (0.15.4):
    - FirebaseCore (~> 6.2)
  * Firebase Component: FirebaseInAppMessagingDisplay
  * Component version: FirebaseInAppMessaging (0.15.4):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.0)
    - GoogleDataTransportCCTSupport (~> 1.0)

In app did finished launching call:
FirebaseApp.configure()
InAppMessaging.inAppMessaging().delegate = inAppMessageDelegate
InAppMessaging.inAppMessaging().messageDisplaySuppressed = true

BUT 
self.displayExecutor is nil while I pass true value of messageDisplaySuppressed. So self.displayExecutor.suppressMessageDisplay is NO. And suppress displaying alert not working.

What can I do with this ?
Thanks in advance.

**Comment by MatthiasB94** [comment]
@fvonk This issue should be fixed with #3922 which is included in version 6.10.0. Unfortunately I didn't create an issue for this, so it's not included in the changelog.

**Comment by paulb777** [comment]
Thanks @MatthiasB94 !  Sorry we missed the release notes update.

@fvonk Let us know if `pod update` does not resolve the issue.
