### ISSUE TITLE
Firestore: Fatal Error on document keys with ó (o-acute)

### ISSUE THREAD

**Issue by brianhiss** [firebase/firebase-ios-sdk#445]
### Environment
* Xcode version: Xcode 9.1, Simulator: iOS 11.1 iPhone 6
* Firebase SDK version: 4.5.0
* Firebase Component: Firestore
 * Component version: 0.9.1
* Development Operating System: MacOS Sierra 10.12.6

### Issue

I was having an issue with FATAL crashes when query for all venues in a collection when there was a document with ó (o-acute) in the key.

Example: `<FSTDocumentKey: venues/empellón-taqueria>`

Even deleting the key from the Firebase Firestore Web Console would still produce FATAL crashes until I deleted the app from the simulator and re-built from Xcode.

This does not occur in the Firebase Admin Tools SDK or in the Realtime Database, only in the firebase-ios-sdk library.

Not sure if this is expected behavior, or a bug. I thought I would report it anyhow.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Read document has key (<FSTDocumentKey: venues/empellón-taqueria>) instead of expected key (<FSTDocumentKey: venues/empellón-taqueria>).'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011218a1ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000110c4cf41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011218f372 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010f52e089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   MyProj                               0x000000010d381eaa -[FSTLevelDBRemoteDocumentCache decodedMaybeDocument:withKey:] + 754
	5   MyProj                               0x000000010d38188f -[FSTLevelDBRemoteDocumentCache documentsMatchingQuery:] + 488
	6   MyProj                               0x000000010d382729 -[FSTLocalDocumentsView documentsMatchingCollectionQuery:] + 171
	7   MyProj                               0x000000010d38252f -[FSTLocalDocumentsView documentsMatchingQuery:] + 210
	8   MyProj                               0x000000010d3879c1 -[FSTLocalStore executeQuery:] + 79
	9   MyProj                               0x000000010d36cef4 -[FSTSyncEngine listenToQuery:] + 273
	10  MyProj                               0x000000010d36521d -[FSTEventManager addListener:] + 469
	11  MyProj                               0x000000010d366c64 __64-[FSTFirestoreClient listenToQuery:options:viewSnapshotHandler:]_block_invoke + 62
	12  libdispatch.dylib                   0x0000000116eca3f7 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x0000000116ecb43c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x0000000116ed395b _dispatch_queue_serial_drain + 1162
	15  libdispatch.dylib                   0x0000000116ed42df _dispatch_queue_invoke + 336
	16  libdispatch.dylib                   0x0000000116ed007d _dispatch_queue_override_invoke + 733
	17  libdispatch.dylib                   0x0000000116ed71f9 _dispatch_root_queue_drain + 772
	18  libdispatch.dylib                   0x0000000116ed6e97 _dispatch_worker_thread3 + 132
	19  libsystem_pthread.dylib             0x000000011738f5a2 _pthread_wqthread + 1299
	20  libsystem_pthread.dylib             0x000000011738f07d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by wilhuff** [comment]
Thanks for the report!

Was there anything special about the query you were performing here or were you just trying to listen to `venues`?

**Comment by brianhiss** [comment]
@wilhuff Nothing special, just listening to `venues`. 

If I replaced the `ó` with an `o`, everything works.

**Comment by tropicdome** [comment]
Has this fix been released? I am experiencing the same issue with the following version of Firestore
- Firebase/Firestore (4.7.0)
- FirebaseFirestore (0.9.3)

**Comment by wilhuff** [comment]
This fix was released with Firebase 4.8.0 (Firestore 0.9.4).

**Comment by karlolopez** [comment]
Same issue here, I deleted de document which ID was generating trouble with unsupported characters and still get firestore document has key instead of expected error. 
As @tropicdome  said disabling presistence make it work but Im in production and dont know the consequences of this.

```
 FIRFirestoreSettings * settings = [[FIRFirestoreSettings alloc]init];
    settings.persistenceEnabled = NO;
    self.db = [FIRFirestore firestore];
```

**Comment by morganchen12** [comment]
This happens because Firestore will try to load persisted values before receiving data from the server, since server availability isn't guaranteed.

If you upgrade Firestore, it should be able to load the cached values on your user's devices without crashing.

**Comment by karlolopez** [comment]
Ive updated firestore and all firebase components and still had the issue.

**Comment by morganchen12** [comment]
Can you upload a sample project reproducing the bug? It should be fixed in the newest Firestore version.
