### ISSUE TITLE
File "FirebaseCore-umbrella.h" generated when using Carthage causing warnings

### ISSUE THREAD

**Issue by MichaelNL** [firebase/firebase-ios-sdk#5209]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.21.0
  * Firebase Component: Core
  * Component version: 6.21.0
  * Installation method: Carthage

### [REQUIRED] Step 2: Describe the problem

When adding Firebase v6.21.0 to your project using Carthage, a header file called "FirebaseCore-umbrella.h" is created in FirebaseCore. This will trigger a warning in Xcode, as it is not included in the header file defined in the module.modulemap of FirebaseCore.
This does not happen when using v6.19.0 of Firebase.

Warning in Xcode is: `umbrella header for module 'FirebaseCore' does not include header 'FirebaseCore-umbrella.h'`

#### Steps to reproduce:

Follow steps in Carthage.md to install setup Firebase using Carthage, by adding this line to the Carthage file:
`binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.21.0`

**Comment by paulb777** [comment]
Thanks for the report. We'll fix for the next release. 

In the meantime, a workaround is to manually delete 'FirebaseCore-umbrella.h' and any other unreferenced umbrella.h files.

**Comment by donnywdavis** [comment]
I am seeing this as well for `FirebaseCore`, `FirebaseInstanceID`, and `FirebaseMessaging` when installing through CocoaPods. Just wanted to note this so that it's not flagged as just a Carthage issue. 🙂

**Comment by paulb777** [comment]
The 6.21.0 regression has been fixed for the two binary distributions - Carthage and Zipfile - and will be available in the next release.

@donnywdavis I don't see the issue for CocoaPods installs.  If you're seeing it there, please create another issue with the template filled out.

**Comment by gbejarano01** [comment]
@paulb777 I see you merged a PR fixing this issue but I still see the following warnings while running the app:

---

warning: Swift error in fallback scratch context: error: <module-includes>:1:1: error: umbrella header for module 'FirebaseCore' does not include header 'FirebaseCore-umbrella.h'
#import "Headers/FirebaseCore.h"
^

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Firebase.h"
        ^

error: /Users/germanbejarano/GitHub/project1819-ios/Carthage/Build/iOS/Firebase.framework/Headers/Firebase.h:15:9: error: could not build module 'FirebaseCore'
#import <FirebaseCore/FirebaseCore.h>
        ^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseAuth' does not include header 'FirebaseAuth-umbrella.h'
#import "Headers/FirebaseAuth.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseDatabase' does not include header 'FirebaseDatabase-umbrella.h'
#import "Headers/FirebaseDatabase.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseDynamicLinks' does not include header 'FirebaseDynamicLinks-umbrella.h'
#import "Headers/FirebaseDynamicLinks.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseFirestore' does not include header 'FirebaseFirestore-umbrella.h'
#import "Headers/FirebaseFirestore.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseFunctions' does not include header 'FirebaseFunctions-umbrella.h'
#import "Headers/FirebaseFunctions.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseInstanceID' does not include header 'FirebaseInstanceID-umbrella.h'
#import "Headers/FirebaseInstanceID.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseMessaging' does not include header 'FirebaseMessaging-umbrella.h'
#import "Headers/FirebaseMessaging.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseRemoteConfig' does not include header 'FirebaseRemoteConfig-umbrella.h'
#import "Headers/FirebaseRemoteConfig.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseStorage' does not include header 'FirebaseStorage-umbrella.h'
#import "Headers/FirebaseStorage.h"
^

error: could not build Objective-C module 'Firebase'
---

Any ideas? Sorry to hijack this thread, let me know if I need to create a new Issue for this.

**Comment by gbejarano01** [comment]
@paulb777 I see you merged a PR fixing this issue but I still see the following warnings while running the app:

---

warning: Swift error in fallback scratch context: error: <module-includes>:1:1: error: umbrella header for module 'FirebaseCore' does not include header 'FirebaseCore-umbrella.h'
#import "Headers/FirebaseCore.h"
^

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Firebase.h"
        ^

error: /Users/user/GitHub/project/Carthage/Build/iOS/Firebase.framework/Headers/Firebase.h:15:9: error: could not build module 'FirebaseCore'
#import <FirebaseCore/FirebaseCore.h>
        ^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseAuth' does not include header 'FirebaseAuth-umbrella.h'
#import "Headers/FirebaseAuth.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseDatabase' does not include header 'FirebaseDatabase-umbrella.h'
#import "Headers/FirebaseDatabase.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseDynamicLinks' does not include header 'FirebaseDynamicLinks-umbrella.h'
#import "Headers/FirebaseDynamicLinks.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseFirestore' does not include header 'FirebaseFirestore-umbrella.h'
#import "Headers/FirebaseFirestore.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseFunctions' does not include header 'FirebaseFunctions-umbrella.h'
#import "Headers/FirebaseFunctions.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseInstanceID' does not include header 'FirebaseInstanceID-umbrella.h'
#import "Headers/FirebaseInstanceID.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseMessaging' does not include header 'FirebaseMessaging-umbrella.h'
#import "Headers/FirebaseMessaging.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseRemoteConfig' does not include header 'FirebaseRemoteConfig-umbrella.h'
#import "Headers/FirebaseRemoteConfig.h"
^

error: <module-includes>:1:1: error: umbrella header for module 'FirebaseStorage' does not include header 'FirebaseStorage-umbrella.h'
#import "Headers/FirebaseStorage.h"
^

error: could not build Objective-C module 'Firebase'
---

Any ideas? Sorry to hijack this thread, let me know if I need to create a new Issue for this.

**Comment by paulb777** [comment]
@gbejarano01 Thanks for the report. I've just compared the 6.21.0 and 6.22.0 releases and verified that the offending umbrella.h files are no longer there. Please make sure that you've run `carthage update` to 6.22.0 or see above for the workaround with 6.21.0.

**Comment by gbejarano01** [comment]
Thanks @paulb777 !! yeah, last time I run Carthage it pulled 6.21.0, wil will try pulling 6.22.0. Thanks!

**Comment by gbejarano01** [comment]
That worked @paulb777 Thanks for the quick response!
