### ISSUE TITLE
159818353: Dynamic Links causes a warning banner to appear under iOS 14

### ISSUE THREAD

**Issue by rhysforyou** [firebase/firebase-ios-sdk#5893]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.5 (11E608c)
  * Firebase SDK version: 6.10.0
  * Firebase Component: Dynamic Links
  * Component version: 6.10.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When launching my app on a device running the iOS 14 or iPadOS 14 beta, when I've copied something on another device, I get this system generated banner:

![Image from iOS (1)](https://user-images.githubusercontent.com/320910/85512838-af634400-b63d-11ea-91fe-5795c7b8da84.png)

This appears to be caused by Firebase Dynamic Links, which attempts to check for a dynamic link saved in the pasteboard by a previously visited landing page.

Not sure what the best solution here is, but we're definitely going to get complaints when users update to iOS 14, launch our app, and immediately see something that looks like us harvesting their data.

**Comment by PycKamil** [comment]
There are new  iOS 14 Pasteboard API available on, this should probably be used now to avoid getting this banner https://developer.apple.com/documentation/uikit/uipasteboard/detectionpattern/3618951-probableweburl?changes=latest_major

**Comment by ryanwilson** [comment]
Thanks for the report! And thanks @PycKamil for pointing out the new Pasteboard API. We'll look at getting this resolved quickly because you're right - that's not a good user experience at all.

**Comment by rohandandavati** [comment]
Internal tracking: b/159818353

**Comment by eldhosembabu** [comment]
May be we should be able to query the pasteboard with new api (https://developer.apple.com/documentation/uikit/uipasteboard/detectionpattern?changes=latest_minor) before trying to access it.

**Comment by ncooke3** [comment]
Hey everybody, 

While we are still exploring potential solutions, we would appreciate feedback on a current approach we are exploring. Feel free to pull in the below version of 'Firebase/DynamicLinks' and let us know if this reduces the issue in your tests.

```ruby
pod 'Firebase/DynamicLinks', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'nc-dl-ios14'
```

We'll keep this thread updated with future developments!

**Comment by rasod** [comment]
@ncooke3 Out of transparency could we have some questions officially answered regarding this feature.

1. When does the SDK currently (production version) access the Pasteboard to check for a DL? Every foreground? On Interval? First Launch Only? Other Events.
2. Is the contents of the pasteboard sent off device for any reason? If so why?
3. If the SDK didn’t access the pasteboard at all what features of DL would stop working? It makes sense that the pasteboard is used to complete the journey when the user goes from the landing page of a DL to the App Store then to first run. What other features of DL are enabled by the pasteboard?

Thanks

**Comment by paulb777** [comment]
Internally tracked at b/159818353

**Comment by roelwillems** [comment]
> @ncooke3 Out of transparency could we have some questions officially answered regarding this feature.
> 
> 1. When does the SDK currently (production version) access the Pasteboard to check for a DL? Every foreground? On Interval? First Launch Only? Other Events.
> 2. Is the contents of the pasteboard sent off device for any reason? If so why?
> 3. If the SDK didn’t access the pasteboard at all what features of DL would stop working? It makes sense that the pasteboard is used to complete the journey when the user goes from the landing page of a DL to the App Store then to first run. What other features of DL are enabled by the pasteboard?
> 
> Thanks

This would be very helpful for companies investigating what is happening with there apps. Do you have a time frame for clarification on this topic?

**Comment by Nikooos** [comment]
> Hey everybody,
> 
> While we are still exploring potential solutions, we would appreciate feedback on a current approach we are exploring. Feel free to pull in the below version of 'Firebase/DynamicLinks' and let us know if this reduces the issue in your tests.
> 
> ```ruby
> pod 'Firebase/DynamicLinks', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'nc-dl-ios14'
> ```
> 
> We'll keep this thread updated with future developments!

I've been trying with this branch, but I still get the warning banner.

No further research yet, but just used the pod from that specific branch, ran `pod install` and build the app in the simulator. When the app is completely closed (not running in background) and started while having something on the clipboard, the warning banner shows up.

**Comment by blwinters** [comment]
I saw that a fix was merged into master that will first check `pasteboard.hasURLs` before accessing it, which is awesome.

In the case of reopening the app and the pasteboard happens to have a URL in it, I believe the pasteboard banner would be shown again which could be confusing for the user. I have a feature request in for this through support, but I'll mention it here for discussion purposes: 

It would be nice for the API to allow us to turn off pasteboard checks if the app logic no longer needs to check initial launch dynamic links from the pasteboard (unless I'm mistaken and the check already won't be triggered by subsequent app opens).

**Comment by phungkytown** [comment]
@ncooke3 I updated by Podfile to target the `nc-dl-ios14` branch as you suggested, but am not seeing those changes after running `pod install`. Do the podspec files need to be updated for that branch so that I don't keep pulling the latest production release?

**Comment by paulb777** [comment]
@phungkytown You would also need to point all of the dependencies of FirebaseDynamicLinks to their podspec versions in the branch.

An easier way to try is likely to just update a standard Firebase 6.27.* installation with the diffs from https://github.com/firebase/firebase-ios-sdk/pull/5905/files

**Comment by phungkytown** [comment]
Figured it out. Thanks for the assist, @paulb777!

**Comment by noremac** [comment]
There appears to be a blessed way to do this now on iOS 14+: [UIPasteboard.DetectionPattern](https://developer.apple.com/documentation/uikit/uipasteboard/3650484-detectpatterns). Is there any plan to use this?

**Comment by blwinters** [comment]
@noremac When I accessed the pasteboard using that API it still showed the banner.

**Comment by eldhosembabu** [comment]
Hi @rasod , Please find official answers for your questions inline below:

> @ncooke3 Out of transparency could we have some questions officially answered regarding this feature.
> 
> 1. When does the SDK currently (production version) access the Pasteboard to check for a DL? Every foreground? On Interval? First Launch Only? Other Events.

**During the very first launch of the app (post-install), FDL sdk will check the pasteboard to see whether the app was installed as a result of clicking on an FDL.**

**It is possible that some apps might have misconfigured their FDL integration, where the pasteboard is checked at every app launch.  This happens when the app fails to call dynamicLinkFromCustomSchemeURL method described in FDL [docs](https://firebase.google.com/docs/dynamic-links/ios/receive#objective-c_3).**

> 2. Is the contents of the pasteboard sent off device for any reason? If so why?

**If the SDK identifies pasteboard content as an [url (and the contents look like a FDL short url)](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.m#L273-L294), the url from the Pasteboard is sent to FDL servers to validate and report the installation count back to the app developer. This data is processed in accordance with the Firebase [DPST](https://firebase.google.com/terms/data-processing-terms).**

> 3. If the SDK didn’t access the pasteboard at all what features of DL would stop working? It makes sense that the pasteboard is used to complete the journey when the user goes from the landing page of a DL to the App Store then to first run. What other features of DL are enabled by the pasteboard?

FDL SDK uses the pasteboard for deep-linking post app install (deferred deep-linking, where the link is copied on the [app preview page](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)) and app install attribution;  otherwise, FDL does not use the pasteboard for anything else.   

**Disabling pasteboard access affects the app in the following ways:
Deferred deep-linking will not work as reliably.  At best, your app receives [weak matches](https://firebase.google.com/docs/reference/unity/namespace/firebase/dynamic-links#linkmatchstrength) for deep-links.
App install attribution stats will be less accurate (potentially undercounting app installs).**

**To disable pasteboard access, set the Info.plist property `FirebaseDeepLinkPasteboardRetrievalEnabled` to `false`.**

> 
> Thanks

**Comment by rasod** [comment]
@eldhosembabu thank you for the info. For clarity the plist option is available starting on version 6.28.0 of the iOS SDK correct?

**Comment by paulb777** [comment]
@rasod Yes the plist option was released with 6.28.0. Leaving this issue open for a more complete solution.

**Comment by lorenc-tomasz** [comment]
@paulb777 Solution on 6.28.x is good enough for now, however maybe it was good to consider add there a condition that disables it only on iOS 14?

**Comment by rasod** [comment]
As we know, one of the main selling features of DL is the first run experience, where you can take a new user directly to the place that caused them to install the app. That being a social link or a marketing campaign or coupon. Disabling that feature ends up gutting DL. Having the paste notification on the other hand, even only on first launch, is not the best first impression to make. Even if your intentions are good users will assume the worst, and that you are “spying” on them. “No good deed goes unpunished”.

I did file a radar with Apple to suggest an additional detection pattern similar to the current WebURL one, but specific only to the apps associated domains. That way the app would only need to access the pasteboard if the url contained was a DL/URL for that apps website, possibility asking for permission first if it does contain a DL.

Ultimately the writing is on the wall and using the pasteboard for simple inter-app communication is not a viable solution anymore. In the long run App Clips may end up being better approach allowing the app to take the user directly to a specific journey - coupon redemption page, article page, video player etc.

Thanks

**Comment by GracieJP** [comment]
I'm not able to see this plist attribute after updating to the most recent version. I added the attribute myself but it didn't affect the reading of the clipboard upon launch.

**Comment by m-j-g** [comment]
> I'm not able to see this plist attribute after updating to the most recent version. I added the attribute myself but it didn't affect the reading of the clipboard upon launch. Any guidance would be very helpful.

Yeah I just tried the same thing, same experience.  This is really bad.

**Comment by impl-kano** [comment]
Same here... using SDK above 6.28 and added the property `FirebaseDeepLinkPasteboardRetrievalEnabled` to false, yet nothing seems to happen...

**Comment by impl-kano** [comment]
> I'm not able to see this plist attribute after updating to the most recent version. I added the attribute myself but it didn't affect the reading of the clipboard upon launch. Any guidance would be very helpful.

Same here ...but solved by clearing the cache and DerivedData.

- Use the SDK above 6.28 and add the property `FirebaseDeepLinkPasteboardRetrievalEnabled` to false.
- Run the command below

```
watchman watch-del-all &&
rm -rf node_modules/ &&
rm -rf ios/Pods ios/build ios/Podfile.lock &&
yarn cache clean —force &&
rm -rf $TMPDIR/react-* &&
rm -rf $TMPDIR/haste-* &&
rm -rf $TMPDIR/metro-* &&
rm -rf ~/Library/Developer/Xcode/DerivedData/
```

then my project works fine now.

**Comment by GracieJP** [comment]
I had no success with your solution @impl-kano

**Comment by nnarayann** [comment]
No success here either

**Comment by joaoffcosta** [comment]
@GracieJP @nnarayann it may be that the issue is with some other library. Investigate for instance Google’s Mobile Ad SDK which has also been linked with this issue.

I don't think there is a way of knowing which is the offending library without doing something like this: https://hugotunius.se/2020/06/05/snooping-on-the-clipboard-snoopers.html

**Comment by m-j-g** [comment]
@joaoffcosta 
I removed dynamic links from my project and the alerts stopped.

**Comment by nnarayann** [comment]
Thank you very much @joaoffcosta. At the end, it was a problem in our side, but you helped us out to find what the real issue was.

**Comment by agordeev** [comment]
With `FirebaseDeepLinkPasteboardRetrievalEnabled` dynamic links stopped working on the first app install. On other hand, displaying the user that the app is reading from his pasteboard is unacceptable. Looks like we need to wait for a better solution :-/

**Comment by marcelderkskarlmax** [comment]
After updating Firebase to version `7.3.0` the warning banner does not show up any more in my app. Does this mean that this issue has been fixed ?

Also I did not set the `FirebaseDeepLinkPasteboardRetrievalEnabled` flag to `false`.

**Comment by yz** [comment]
any update on this?

**Comment by henrySSiberian** [comment]
Any update on this topic? I think the bug still remains because I have not seen that they have recently released an update of the firebase ios sdk library :/

**Comment by eldhosembabu** [comment]
> With `FirebaseDeepLinkPasteboardRetrievalEnabled` set to false dynamic links stopped working on the first app install. On other hand, displaying that the app is reading from the user's pasteboard is unacceptable. Looks like we need to wait for a better solution :-/

hi @agordeev could you please let me know whether you are not at all receiving any links after `FirebaseDeepLinkPasteboardRetrievalEnabled` set to false? You are supposed to get FDL working with a weak/default match. Please let us know if thats not the case. thanks

**Comment by yz** [comment]
> > With `FirebaseDeepLinkPasteboardRetrievalEnabled` set to false dynamic links stopped working on the first app install. On other hand, displaying that the app is reading from the user's pasteboard is unacceptable. Looks like we need to wait for a better solution :-/
> 
> hi @agordeev could you please let me know whether you are not at all receiving any links after `FirebaseDeepLinkPasteboardRetrievalEnabled` set to false? You are supposed to get FDL working with a weak/default match. Please let us know if thats not the case. thanks

Hi, how to get the weak/default match?  Is there any code sample?

**Comment by misyobun** [comment]
> > > With `FirebaseDeepLinkPasteboardRetrievalEnabled` set to false dynamic links stopped working on the first app install. On other hand, displaying that the app is reading from the user's pasteboard is unacceptable. Looks like we need to wait for a better solution :-/
> > 
> > 
> > hi @agordeev could you please let me know whether you are not at all receiving any links after `FirebaseDeepLinkPasteboardRetrievalEnabled` set to false? You are supposed to get FDL working with a weak/default match. Please let us know if thats not the case. thanks
> 
> Hi, how to get the weak/default match? Is there any code sample?

@yz Hi, You can get the weak/default match info like this.

```
// DynamicLink
if let dynamicLink: DynamicLink = DynamicLinks.dynamicLinks().dynamicLink(fromCustomSchemeURL: url) {
    print(" \(dynamicLink.matchType)") <---------
}
```

I can guess that the match(weak/default) is based on the device information here.

https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m#L208

**Comment by abbas-mulani** [comment]
Any update on this?

I have done following:

1. Added FirebaseDeepLinkPasteboardRetrievalEnabled and set it to false in Info.plist.
2. Perform diagnosis :

`[FIRDynamicLinks performDiagnosticsWithCompletion:nil];`

Output : performDiagnostic completed successfully! No errors found.

Then also, it is showing popup of paste board.

**Comment by santiagolimas** [comment]
Has there been any update on this topic?

**Comment by marcelderkskarlmax** [comment]
I am a bit lost with this.

In our project I have set the `FirebaseDeepLinkPasteboardRetrievalEnabled` to false.
I don't see the warning banner anymore but then also the dynamic link doesn't survive the app install.

This is how we are handling the link.
```
        let linkHandled = DynamicLinks.dynamicLinks().handleUniversalLink(incomingURL) {( dynamicLink, error ) in
            guard error == nil else {
                Log.message("Dynamic link error: \(error!.localizedDescription)")
                return
            }

            if let dynamicLinkUrl = dynamicLink?.url {
                self.redirect(universalLink: dynamicLinkUrl)
            }
        }
```

When opening the link with a previously installed app, the dynamic link works fine.
When opening the link with the post install flow, the dynamic link does not work.

**Comment by kaz-mercari** [comment]
Is there any updates on this?

**Comment by paulb777** [comment]
I'm going to close this issue, since the original problem was addressed with the plist option in 6.28.0.  Please open another issue for related or other questions and issues.
