### ISSUE TITLE
Firestore crashing when attempting to write data

### ISSUE THREAD

**Issue by drekka** [firebase/firebase-ios-sdk#633]
I'm new to Firestore, but so far have not been able to get it to work at all. I've been logged the problem over on [StackOverFlow](https://stackoverflow.com/questions/48094652/ios-trying-to-access-firestore-triggers-exc-bad-access).

The summary is that when I execute this code:

    let db = Firestore.firestore()
    let doc = db.collection("users").addDocument(data: [
        "first": "Ada",
        "last": "Lovelace",
        "born": 1815
    ]) { err in
        if let err = err {
            print("Error adding document: \(err)")
        }
    }

It executes immediately, but never runs the completion block. Then about 4 minutes later it crashes with this in the log:

    2018-01-09 21:11:23.584982+1100 Crux[2671:334948] *** Assertion failure in 
        -[FSTWriteStream closeWithFinalState:error:], third_party/firebase/ios/Source/Firestore/Source/Remote/FSTStream.m:348

**Comment by drekka** [comment]
I've just figured out that the crash was caused by the firestorm access rules not allow read/write. Changing the rule to allow public read/write allowed me to write the record.

Weirdly though, once I could do this, all the other records I had written appeared in the console where previously it had been blank as if the writes had failed.

**Comment by morganchen12** [comment]
That sounds like a bug. Unauthorized reads and writes should return errors and then fail rather than be queued forever. If you set your security rules to deny all reads and writes, can you still reproduce the issue? If so, can you send us some logs?

**Comment by mikelehen** [comment]
I think the crash is related to switching users and we have a fix that should go out in an upcoming release.

The writes getting queued could be related to switching users as well...  If you perform some writes and then sign out or switch users before they are completed, then they will be indefinitely queued until you sign in as the original user again (because we can't authenticate the writes to the server once you sign in as somebody else).

**Comment by mikelehen** [comment]
I think the crash is related to switching users and we have a fix that should go out in an upcoming release.

The writes getting queued could be related to switching users as well...  If you perform some writes and then sign out or switch users before they are completed, then they will be indefinitely queued until you sign in as the original user again (because we can't authenticate the writes to the server once you sign in as somebody else).

**Comment by drekka** [comment]
In the app I'm using a Firebase user which I previously signed in. Admittedly it's possible I've done something wrong there as this is the first time I've used Firebase. However just before running the above code, I retrieve the current Firebase user (don't have the code in front of me, but I think it's something like 

    let user = Auth.auth().currentUser

And I do get a user. With the timeouts, I've just bee triggering the above code and then waiting, not touching the app or triggering any other code and I've only got my one test user in play (which I've not signed in or out), so changing users as the cause would seem to be unlikely. 

@mikelehen - haven't tried locking up the rules since then, but I do want to change them so I'll see what happens :-)

**Comment by mikelehen** [comment]
Interesting. If you don't have any signOut() or signIn*() code that's being hit, then indeed my theory is void. :-/  So yeah, please do let us know if you can still reproduce this.  And then if you can enable logging with Firestore.enableLogging(true) and send us the output, that would be great.

**Comment by paulb777** [comment]
Fixed in Firebase 4.8.1 and FirebaseFirestore 0.10.0

**Comment by uknowmeright** [comment]
I am still running into this error on Firestore 0.10

```
2018-02-09 11:59:27.698270-0500 FamClub[12205:5002398] *** Assertion failure in -[FSTWriteStream closeWithFinalState:error:], third_party/firebase/ios/Source/Firestore/Source/Remote/FSTStream.m:348
2018-02-09 11:59:27.698580-0500 FamClub[12205:5002398] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: closeWithFinalState should only be called for a started stream that has an active delegate.'
*** First throw call stack:
(0x182c67164 0x181eb0528 0x182c67038 0x1836017f4 0x100f4e468 0x100f41518 0x100f41620 0x100f0e3d4 0x100f04944 0x103a492cc 0x103a4928c 0x103a57f80 0x103a4c7ec 0x103a58f6c 0x103a60020 0x18288ef1c 0x18288eb6c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

Anyone else still experiencing this?

**Comment by morganchen12** [comment]
@uknowmeright, can you share a project that reproduces this issue?

**Comment by uknowmeright** [comment]
Sorry, I thought I was on 0.1.0 but did not force a pod update. It is not producing this error anymore.
