### ISSUE TITLE
[APMAnalytics load]  and [GTMSessionUploadFetcher load] take too much time at app startup

### ISSUE THREAD

**Issue by shanksGuo** [firebase/firebase-ios-sdk#6936]
### Feature proposal

* Firebase Component: APMAnalytics, GTMSessionUploadFetcher

I found [APMAnalytics load]  and [GTMSessionUploadFetcher load] method take long time to execute, in my case, when app launches, [APMAnalytics load] takes 51ms and  [GTMSessionUploadFetcher load] takes 95ms.  see the pic below. I wish you can remove +load method considering Apple is not recommend +load.
By the way, there were too many +load method in firebase and related sdk, such as #6902 #6855 , I wonder if it is possible remove all +load to keep code in control
<img width="2393" alt="Screen Shot 2020-11-10 at 10 31 43" src="https://user-images.githubusercontent.com/8662571/98623267-48250280-2346-11eb-8076-1577e6d9f4ae.png">
<img width="2356" alt="Screen Shot 2020-11-10 at 11 09 33" src="https://user-images.githubusercontent.com/8662571/98623284-4fe4a700-2346-11eb-959b-031cf95767ca.png">

**Comment by maksymmalyhin** [comment]
@shanksGuo Thank you for the report. Appreciate your time spent detailed investigation!

As for `+load` methods usage by Firebase: for most of the cases the method Firebase classes implement it to register an SDK dependency with the Firebase component system. Completely removing the code from `+load` methods would make Firebase initialization much more involving process for developers. I think instead we should:
1.concentrate on moving any unnecessary and slow operation (like ones in the issues) out of the `+load` method
2. Set up startup testing on CI to prevent regressions in the future. 

We will work on these items. Sorry for troubles.

**Comment by maksymmalyhin** [comment]
I updated the title to better represent the issue and intended action items.

**Comment by maksymmalyhin** [comment]
Analytics part is tracked internally at b/173110496.

**Comment by shanksGuo** [comment]
@maksymmalyhin  Thanks for your efforts, and I wonder which release version will these items be merged?

**Comment by maksymmalyhin** [comment]
@shanksGuo Sorry for the delayed response. The `GTMSessionUploadFetcher` issue should be fixed by https://github.com/google/gtm-session-fetcher/pull/219. It can be tested from the branch - add the following line to the Podfile:

```
pod 'GTMSessionFetcher', :git=>'https://github.com/maksymmalyhin/gtm-session-fetcher.git', :branch=>'mm/load-optimization'
```

The Analytics issue fix is still in progress. @htcgh may provide more detailed update on it.

**Comment by htcgh** [comment]
Sorry for the late response. The Analytics fix was included in Firebase 7.2.0.

**Comment by Monster-L** [comment]
@maksymmalyhin Thanks for your reply, I have updated to the latest 7.3, but the problem still exists。
Kill the application, restart the application will probably crash
