### ISSUE TITLE
upload-symbols fail with "Could not be onboarded statusCode 403"

### ISSUE THREAD

**Issue by srdanrasic** [firebase/firebase-ios-sdk#6961]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0 or 12.1
  * Firebase SDK version: 7.0.0 (and earlier)
  * Installation method: `Carthage` (select one)
  * Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

We have an app with multiple targets / configurations. Each of these configurations has a different bundle identifier. We've set up an app on Firebase for each of these configurations. Now, for some, and only some configurations, we are getting the following error when running the `run` script:

```
error: Could not be onboarded statusCode 403
```

That error seems to be coming from `upload-symbols` executable. 

What are possible reasons for such error? 

Thank you

**Comment by tundsD53** [comment]
I think we’re having the same issue, i’m also having issues setting up crashlytics via Carthage & have a similar issue i have posted [here](https://github.com/firebase/firebase-ios-sdk/issues/6952)

**Comment by srdanrasic** [comment]
Could anyone from the Firebase team provide a hint on what are the reasons behind that error message? Thank you.

**Comment by samedson** [comment]
Hey apologies for this noisy error folks. This should not have an impact on your crashes or dSYM uploads. This is probably only impacting apps that were onboarded to Firebase more recently.

We'll be shipping a change to fix this early next week in the backend so no SDK update from you should be needed.

**Comment by srdanrasic** [comment]
Thank you @samedson!

**Comment by evanleeuwen** [comment]
> Hey apologies for this noisy error folks. This should not have an impact on your crashes or dSYM uploads. This is probably only impacting apps that were onboarded to Firebase more recently.
> 
> We'll be shipping a change to fix this early next week in the backend so no SDK update from you should be needed.

@samedson,

What are the solutions for this when being impacted, our dSYMs are not getting uploaded?

Cheers,

EvL

**Comment by srdanrasic** [comment]
Hey @samedson, would you have an update on this issue? We are still experiencing the problem.

**Comment by samedson** [comment]
Just got the change out that should fix this. Can you try again now @srdanrasic? 

@evanleeuwen if you're experiencing dSYM upload issues, can you reach out to support? It shouldn't be related to this issue.

**Comment by evanleeuwen** [comment]
> Just got the change out that should fix this. Can you try again now @srdanrasic?
> 
> @evanleeuwen if you're experiencing dSYM upload issues, can you reach out to support? It shouldn't be related to this issue.

I believe the changes I made, in order to keep this issue from failing our CI system, play a part in it still not working. I've reverted and I'm seeing success (so far). Haven't triggered a crash yet, but CI system didn't fail and I don't see the log message either.

Thanks

**Comment by srdanrasic** [comment]
@samedson, I've just got through the upload process 🎉 Will do more testing tomorrow, but it seems to be working. Thank you!

**Comment by morganchen12** [comment]
Closing this since it appears to be resolved. Please let us know if that's not the case. Thanks!
