### ISSUE TITLE
Firebase Performance warns me to add Analytics, which is not available on Catalyst

### ISSUE THREAD

**Issue by steipete** [firebase/firebase-ios-sdk#7693]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.8
  * Installation method: Zip file
  * Firebase Component: Performance

### [REQUIRED] Step 2: Describe the problem

<img width="827" alt="Screen Shot 2021-03-10 at 14 06 08" src="https://user-images.githubusercontent.com/58493/110634027-c507a200-81a9-11eb-92cc-e8cb2766249c.png">

When building, I see a warning that asks me to add Firebase Analytics when using Performance, however we build for Catalyst and Analytics is not available there.

Seems related to https://github.com/firebase/firebase-ios-sdk/issues/4563

#### Steps to reproduce:

Integrate from Zip. Add Performance. Archive Catalyst app.

**Comment by steipete** [comment]
Side note - we can finally ship Crashlytics for our Catalyst app, super excited about this. Thanks for handling my last bug report so quickly!

**Comment by paulb777** [comment]
@steipete Thanks for the report. This issue - #7487 - was just fixed in the 7.8.0 release.  Did you update the Firebase.h from the the [7.8.0 zip download](https://github.com/firebase/firebase-ios-sdk/releases/tag/7.8.0)?

**Comment by steipete** [comment]
I indeed forgot to update it, but updating didn't resolve the issue.

If I look at the header it's clear why. See the selected part for the fix:
<img width="878" alt="Screen Shot 2021-03-10 at 18 25 36" src="https://user-images.githubusercontent.com/58493/110670846-217cb880-81ce-11eb-8db8-804f249ac88a.png">

**Comment by paulb777** [comment]
Oops! Thanks for pointing that out. We'll get it updated for the next release.

`FIREBASE_ANALYTICS_SUPPRESS_WARNING` should only be needed by iOS Remote Config users wanting to suppress the warning.

We'll need to discuss with the Performance and RemoteConfig teams the right fix for iOS since Performance doesn't need Analytics, but its dependency RemoteConfig might want the warning?  But either way, there shouldn't be the need for Catalyst and your suggestion should be applied.

**Comment by steipete** [comment]
Thanks for looking into this! I'd also take a Catalyst build of Analytics, would make things simpler :)

**Comment by paulb777** [comment]
Sent #7719 to fix and reopened #7487 for the related iOS issue
