### ISSUE TITLE
Crash in grpc_library.h line 42 under iOS and iPadOS 14

### ISSUE THREAD

**Issue by JanGorman** [firebase/firebase-ios-sdk#9462]
### Step 1: Describe your environment

  * Xcode version: 13.2.1
  * Firebase SDK version: 8.13.0
  * Installation method: `CocoaPods`
  * Firebase Component: Firestore
  * Target platform(s): `iOS`

#### Steps to reproduce:

Haven't been able to reproduce myself yet. The crash is spiking in our latest app release and only affects devices running iOS and iPadOS 14. 

I've tried reproducing on a physical device running iOS 14 with Address Sanitizer and Undefined Behaviour Sanitizer enabled, alas without success.

The logs we get from Crashlytics:

Crashed: com.google.firebase.firestore
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
```
Crashed: com.google.firebase.firestore
0  FirebaseFirestore              0x2d514 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) + 42 (grpc_library.h:42)
1  FirebaseFirestore              0x2d3d8 grpc_impl::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) + 247 (completion_queue_impl.h:247)
2  FirebaseFirestore              0x2b100 firebase::firestore::remote::Datastore::Datastore(firebase::firestore::core::DatabaseInfo const&, std::__1::shared_ptr<firebase::firestore::util::AsyncQueue> const&, std::__1::shared_ptr<firebase::firestore::credentials::CredentialsProvider<firebase::firestore::credentials::AuthToken, firebase::firestore::credentials::User> >, std::__1::shared_ptr<firebase::firestore::credentials::CredentialsProvider<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, firebase::firestore::remote::ConnectivityMonitor*, firebase::firestore::remote::FirebaseMetadataProvider*) + 104 (datastore.cc:104)
3  FirebaseFirestore              0x61750 firebase::firestore::core::FirestoreClient::Initialize(firebase::firestore::credentials::User const&, firebase::firestore::api::Settings const&) + 3237 (memory:3237)
4  FirebaseFirestore              0x6f4c firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 993 (atomic:993)
5  FirebaseFirestore              0x12aefc firebase::firestore::util::Task::ExecuteAndRelease() + 1871 (functional:1871)
6  libdispatch.dylib              0x61280 _dispatch_client_callout + 16
7  libdispatch.dylib              0x9dcc _dispatch_lane_serial_drain$VARIANT$mp + 612
8  libdispatch.dylib              0xa8a8 _dispatch_lane_invoke$VARIANT$mp + 424
9  libdispatch.dylib              0x14338 _dispatch_workloop_worker_thread + 712
10 libsystem_pthread.dylib        0xa5a4 _pthread_wqthread + 272
11 libsystem_pthread.dylib        0xd874 start_wqthread + 8
```

**Comment by schmidt-sebastian** [comment]
@JanGorman Thanks for reporting this. This looks like an issue in the underlying library and likely the same as https://github.com/grpc/grpc/issues/24850. I will ping someone from the GRPC team to gain some traction.

**Comment by EliotAndres** [comment]
I work with Janm, adding more information on this. Here's how the crashes look like:

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/9083711/159485933-3baa4bb1-46fa-40f1-9541-78a1a02dd043.png">


We didn't update Firebase before the release started crashing, and we're a bit curious as to why it started with this release. Would you have any pointers on where to look?

**Comment by ondrejkorol** [comment]
We experienced the exact same issue! All affected devices were running iOS 14.8.1.

**Comment by schmidt-sebastian** [comment]
@ondrejkorol That's very interesting. Do you see any crashes with iOS 14.8.1 and prior versions of the Firestore SDK (< 8.13)?

**Comment by codingrhythm** [comment]
We don't have crashes from Firebase SDK, but we have similar crashes from the gRPC library we integrated with our App. The crash only happens for some iOS 14 users. We didn't bump gRPC between releases, this is what our stack trace looks like.
<img width="782" alt="Screen Shot 2022-04-08 at 2 07 17 pm" src="https://user-images.githubusercontent.com/1888415/162360641-600e39fe-c2ea-44fe-8caf-9be821fbf47f.png">

We even tried to release a previous build (which is not crashing) with just a version bump, the strange thing is the build with only a version bump started crashing as well with the same stack trace. This leads me to think, there might be something changed from the Apple side when recompiling the app from the bitcode. 

Xcode 13.3 was released on [14th Mar 2022](https://xcodereleases.com/). The timeline aligns, but I am not sure if it could be the cause. When I compare the install size of 2 builds with only version difference. The second one has 1mb less.

| Old version released before 14th Mar | New version released after 14 Mar with only version bump |
| --- | --- | 
| <img width="643" alt="Screen Shot 2022-04-08 at 1 31 28 pm" src="https://user-images.githubusercontent.com/1888415/162361255-acf92588-ddf3-490c-9757-f56b44a774f5.png"> | <img width="662" alt="Screen Shot 2022-04-08 at 1 31 20 pm" src="https://user-images.githubusercontent.com/1888415/162361279-3e66bbd4-8504-40a7-82c5-dcd1aa98854a.png"> |

The gRPC lib is integrated with the iOS app as an XCFramework via SPM. The iOS project is built using Xcode 13.2.1 as well.

**Comment by ondrejkorol** [comment]
> @ondrejkorol That's very interesting. Do you see any crashes with iOS 14.8.1 and prior versions of the Firestore SDK (< 8.13)?


We have the prior version – FirebaseFirestore (8.12.1). Could the new version (8.13) solve it?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68337693/162793264-917f83b8-79ec-4404-b7a0-c2ba36df5ea6.png">

**Comment by codingrhythm** [comment]
[Xcode 13.3.1](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3_1-release-notes) is out, the issue might have been solved if a new build is submitted.
> When you target iOS 13.4 and later and enable bitcode, the bitcode segment is now stripped correctly. This fixes a crash that prevented some apps from running in older operating systems (iOS 14 and earlier). (90024354) (FB9951126)

**Comment by codingrhythm** [comment]
I am able to confirm that releasing another build without any changes except for a version bump resolves the issue,.

**Comment by JanGorman** [comment]
Thanks @codingrhythm for the detailed investigation and your follow-up. We submitted a new version as well with Xcode 13.3.1 that is still in review. I'll update here once it's released

**Comment by JanGorman** [comment]
Confirmed on our end as well that releasing with 13.3.1 fixes the issue. Thanks everyone

**Comment by porchgeneration** [comment]
We have had the exact same issue and now released a new build built with Xcode 13.3.1 and Firestore version 9 but we are still seeing the crash. ( before grpc_library.h line 43 now grpc_library.h line 45) Anyone else ?

**Comment by codingrhythm** [comment]
Same for us. We did further investigation and found out the crash is from the users who installed the app via MDM. The same build doesn't crash if it's installed via AppStore. The work around for us at the moment is to build the app with Xcode 13.2.1 with Bitcode disabled.

**Comment by ondrejkorol** [comment]
Yeah, it's back..

```
grpc_library.h - Line 42
grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) + 42
```

**Comment by porchgeneration** [comment]
Any news ? Are any of you getting the crash using Remote Config with Firebase ?

**Comment by dconeybe** [comment]
I'll take a look into this. The flaky nature of this issue suggest some memory mismanagement that sometimes you get away with, and other times you don't. I'll pour through Firestore's code and see what I can find. Any additional stack traces would be greatly appreciated.

**Comment by ondrejkorol** [comment]
Is there any progress please? iOS 14 is still crashing from time to time.
```
Crashed: com.google.firebase.firestore – EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
0  FirebaseFirestore              0x2f614 GrpcLibraryCodegen + 42 (grpc_library.h:42)
1  FirebaseFirestore              0x2f4d8 CompletionQueue + 247 (completion_queue_impl.h:247)
2  FirebaseFirestore              0x2d1c4 Datastore + 104 (datastore.cc:104)
3  FirebaseFirestore              0x637d0 Initialize + 958 (shared_ptr.h:958)
4  FirebaseFirestore              0x90e8 ExecuteBlocking + 997 (atomic:997)
5  FirebaseFirestore              0x119e58 ExecuteAndRelease + 491 (function.h:491)
```

**Comment by dconeybe** [comment]
@ondrejkorol Unfortunately, no progress yet. I have been stepping through the code line by line to try to figure out what might be causing this but I don't see anything. Could you tell me which version of the Firebase iOS SDK you are using? Also, is it possible that this crash is occurring when the app is shutting down?

**Comment by ondrejkorol** [comment]
@dconeybe  We have Firebase Firestore v8.8.
Looks like this is happening during the app launch when we're setting up a Firestore listener (observing a collection). The newest crashes are again tied to iOS 14.8.1.

@porchgeneration, @JanGorman are you still experiencing these crashes?

**Comment by JanGorman** [comment]
@ondrejkorol We're not seeing this crash. We've since updated to v8.15.0 (and moved to SPM) so as @dconeybe suggests, this will probably help in your case.

**Comment by paulb777** [comment]
Going to close, since it looks like the issue is addressed with the gRPC 1.44.0 available with Firebase 8.15.0+

**Comment by eroscai** [comment]
@dconeybe @paulb777 we are still receiving this crash, gRPC version and Firebase version have been updated to required version.
The only difference is that XCode has been updated to the latest version 13.4. 

**environment**:
- Xcode version: 13.4
- Firebase SDK version: 8.15.0
- Installation method: CocoaPods
- Firebase Component: Firestore
- Target platform(s): iOS

**stack trace**:
```
Crashed: com.google.firebase.firestore
0  FirebaseFirestore              0x2ed90 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) + 45 (grpc_library.h:45)
1  FirebaseFirestore              0x2ec54 grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) + 253 (completion_queue.h:253)
2  FirebaseFirestore              0x2c954 firebase::firestore::remote::Datastore::Datastore(firebase::firestore::core::DatabaseInfo const&, std::__1::shared_ptr<firebase::firestore::util::AsyncQueue> const&, std::__1::shared_ptr<firebase::firestore::credentials::CredentialsProvider<firebase::firestore::credentials::AuthToken, firebase::firestore::credentials::User> >, std::__1::shared_ptr<firebase::firestore::credentials::CredentialsProvider<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, firebase::firestore::remote::ConnectivityMonitor*, firebase::firestore::remote::FirebaseMetadataProvider*) + 104 (datastore.cc:104)
3  FirebaseFirestore              0x63204 firebase::firestore::core::FirestoreClient::Initialize(firebase::firestore::credentials::User const&, firebase::firestore::api::Settings const&) + 958 (shared_ptr.h:958)
4  FirebaseFirestore              0x844c firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 997 (atomic:997)
5  FirebaseFirestore              0x133414 firebase::firestore::util::Task::ExecuteAndRelease() + 491 (function.h:491)
6  libdispatch.dylib              0x481c _dispatch_client_callout + 20
7  libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
8  libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
9  libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
10 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
11 libsystem_pthread.dylib        0xa74c start_wqthread + 8
```

**Comment by eroscai** [comment]
@paulb777 Done!

[Podfile.lock.zip](https://github.com/firebase/firebase-ios-sdk/files/8799245/Podfile.lock.zip)

**Comment by dconeybe** [comment]
@eroscai are you able to reproduce the crash? If so, there is some extra logging I'd like you to add to help debug this.

**Comment by eroscai** [comment]
@dconeybe I can't reproduce this crash myself. It only happens on iOS 14, and it happens very beginning of the launch, because i can't see any logs from the Logs column of Crashlytics dashboard.
We will try to use XCode 13.3.1 to archive and release the new version, if there is any progress, i will update here.

**Comment by eroscai** [comment]
By the way, I found some warnings during the build time, I don't know if it is related to this crash.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/280369/171133909-031ccd9d-35cc-4ed3-8014-8ef8e49c9bce.png">

**Comment by dconeybe** [comment]
https://github.com/grpc/grpc/issues/29843 opened

**Comment by codingrhythm** [comment]
Just install the app via MDM on an iOS 14 device to reproduce the crash.

**Comment by dconeybe** [comment]
Update: Other users have reported similar grpc crashes when apps are installed via MDM: https://github.com/grpc/grpc/issues/29500. I have no updates but I'd encourage you to follow https://github.com/grpc/grpc/issues/29500 and https://github.com/grpc/grpc/issues/29843 to get the latest updates on the progress of the investigation.

**Comment by dconeybe** [comment]
I don't have the time I'd like to reproduce this issue for myself and dig into it. For anyone that can reproduce this issue, could you try reproducing with a build that has Address Sanitizer enabled (https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early)? If ASAN finds a bug, this could point directly to the root cause.

**Comment by codingrhythm** [comment]
From what I know, I don't think it's a runtime issue. It is an issue caused by the new Xcode toolchain, bitcode, iOS version and MDM distribution.

If the app is not running on iOS 14, you won't have this issue.
If you build and submit the app with Xcode versions older than 13.4 and with bitcode disabled, you won't have this issue.
If the app is not installed via MDM, you won't have this issue. 
Otherwise, the app crashes when launched 100% if it's installed via MDM and running on iOS 14.

**Comment by codingrhythm** [comment]
BTW, since Xcode 14 removes support for bitcode, I think this issue might be fixed. But it's still in beta at the moment, so we cannot verify it.

**Comment by ondrejkorol** [comment]
We can't reproduce it either. Only the App Store version crashes on iOS 14 devices (mostly 14.8.1). Released via Xcode 13.3.1. We got feedback from a user that after downloading the app, it was crashing right after opening. But when he deleted the app and download it again, it worked... 

@codingrhythm – so you're suggesting that Xcode 13.4 + bitcode disabled will resolve this issue?

**Comment by codingrhythm** [comment]
@ondrejkorol Xcode 13.3.1 + bitcode disabled works for us. We tried 13.4 + bitcode disabled, didn't work.

**Comment by codingrhythm** [comment]
@ondrejkorol BTW, we only see crashes for MDM installs. For the exact same build, if the app is installed via TestFlight or AppStore, it doesn't crash.  However, if the app is installed via MDM (even when the MDM redirects to AppStore to download the app), the app crashes on launch. We observe a difference in binary size between MDM install and AppStore install on the same build.

**Comment by codingrhythm** [comment]
@ondrejkorol Sorry, I made a mistake on the Xcode version. The working version for us is Xcode 13.2.1.

**Comment by ondrejkorol** [comment]
Thanks! In our case, it's the build downloaded from the App Store. And I'd expect the same for you @DimDL , right? So it's not only MDM issue.

**Comment by DimDL** [comment]
Hi @ondrejkorol . We don't use MDM, it affects our Appstore build indeed.

**Comment by DimDL** [comment]
Looks like a server-side mitigation was found on August 24th, this crash is disappearing and almost gone. We haven't done anything special about it. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/6987784/187397908-c8f4d95d-9ca2-491a-baf5-5380e0f82684.png">

**Comment by dconeybe** [comment]
Now that xcode 14 has disabled bitcode by default, is this crash still reproducible by anyone that has built their app with xcode 14?

**Comment by ondrejkorol** [comment]
> Now that xcode 14 has disabled bitcode by default, is this crash still reproducible by anyone that has built their app with xcode 14?

I believe it wasn't reproducible ever.
@DimDL - in your case the issue really did disappear without doing anything special? In our case, it's still present.

Firebase 10.0.0
```
FirebaseFirestore
grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) + 104
```

**Comment by dconeybe** [comment]
@ondrejkorol I spent a few hours investigating this again today, and came to the same conclusion as I did 6 months ago: https://github.com/firebase/firebase-ios-sdk/issues/9462#issuecomment-1142555266. Basically, this _should_ never happen.

The crash is due to the global variable `g_glip` from grpc being null. But `g_glip` is initialized before `main()` is even called, and it is  set exactly once, and is never again set back to null. It's "impossible" for it to be null and fail the assertion, which occurs long after `main()` has been invoked.

So the only explanations that I can think of are pretty wild:
1. Some buggy compiler optimization is eliding the initialization of `g_glip` or is assuming that it is always null and eliding the check at runtime.
2. There is an ODR violation causing two different `g_glip` globals to be present in your application and initialization is initializing one of them and the runtime assertion check is checking another.
3. The "Static Initialization Order Fiasco" is causing the null initialization to win.

Do any of these sounds like they may be affecting you?

I'm going to leave another comment on https://github.com/grpc/grpc/issues/29843 to see if the grpc engineers have more ideas.

**Comment by paulb777** [comment]
To see if multiple copies of the library are linked into the app, the Xcode console will show warnings at launch time.

**Comment by dconeybe** [comment]
@ondrejkorol Could you share your `Podfile.lock`?

**Comment by dconeybe** [comment]
@ondrejkorol Could you also run `grep -r g_glip Pods` in your project root and paste the output? I'm looking for duplicate definitions of `g_glip`.

For example, here is what I see when I run it in my clone of https://github.com/firebase/quickstart-ios, which is correct/expected (i.e. the one and only definition of `g_glip` is in `Pods/gRPC-C++/src/cpp/codegen/codegen_init.cc`):

```
$ grep -r g_glip Pods
Pods/gRPC-C++/include/grpcpp/impl/grpc_library.h:    if (grpc::g_glip == nullptr) {
Pods/gRPC-C++/include/grpcpp/impl/grpc_library.h:      grpc::g_glip = g_gli;
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:extern GrpcLibraryInterface* g_glip;
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      GPR_CODEGEN_ASSERT(g_glip &&
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      g_glip->init();
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      GPR_CODEGEN_ASSERT(g_glip &&
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      g_glip->shutdown();
Pods/gRPC-C++/src/cpp/codegen/codegen_init.cc:grpc::GrpcLibraryInterface* grpc::g_glip;
```

**Comment by dconeybe** [comment]
@ondrejkorol One more question... are you by any chance using Firestore in the initialization of a global variable? Because that could explain why `g_glip` is null because then the Firestore code _could_ be running before `g_glip` is initialized.

**Comment by ondrejkorol** [comment]
Thank you both for your investigation! @dconeybe I think you found the real cause!
That's right, we use Firebase for initialization of a shared object (singleton) on app launch (`didFinishLaunchingWithOptions`)!

Basically, we call there:
` FirebaseApp.configure(options: options)`
and on the next line, we initialize the shared object for handling the chat (= touching Firestore and Storage).

So that could cause the issue on iOS 14 but not on higher versions? Hmm, how could I prevent it?
(in our Podfile we have Firestore or any other Firebase library only once)

**Comment by dconeybe** [comment]
Hmm, that's interesting. However, `didFinishLaunchingWithOptions` is called _after_ main, so the c++ globals should already be initialized. Calling `FirebaseApp.configure(options: options)` in `didFinishLaunchingWithOptions` should be safe too. In fact, that's what we demonstrate in quickstart demo app [link](https://github.com/firebase/quickstart-ios/blob/c9a0bd3d51d361a437e72b03542fabec44081094/firestore/FirestoreExample/AppDelegate.swift#L27).

Do you do anything with _firestore_ in `didFinishLaunchingWithOptions`?

Another possibility is if you have any objective-c code in your app that uses Firestore from a `+load` method. That would be a problem because `+load` is called _before_ `main` and I'm not sure if (and doubt that) there are guarantees about it being invoked before or after static global variable initialization.

**Comment by ondrejkorol** [comment]
Right? I thought about whether it could be connected to the fact we "configure it" twice.
Basically, after that we start working with it - setup listeners etc.
But this crash occurs within the first 1-2 seconds (according to Crashlytics - we weren't able to catch it in Xcode)

Oh, and we don't have any objective-c code related to Firestore.
```
// App Delegate

func application(_: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    FirebaseApp.configure(options: options)
    ChatService.initialize()
    ...
}

// ChatService - Shared instance

let database: Firestore

func initialize() {
    
    let app: FirebaseApp?
    
    if let existingInstance = FirebaseApp.app() {
        app = existingInstance
    } else {
        let appName = UUID().uuidString
        FirebaseApp.configure(name: appName, options: options)
        app = FirebaseApp.app(name: appName)
    }

   database = Firestore.firestore(app: firebaseApp)
}
```

**Comment by dconeybe** [comment]
@ondrejkorol Are you using CocoaPods? If yes, please provide a link to a gist with your Podfile.lock contents. Also, run the `grep` command from https://github.com/firebase/firebase-ios-sdk/issues/9462#issuecomment-1325846049 and paste the output.

**Comment by ondrejkorol** [comment]
@dconeybe  Yes, we're using Cocoapods.
Here is the Podfile lock: [link](https://gist.github.com/ondrejkorol/65ec68702377843512b84c1a2a787125)

```
grep -r g_glip Pods
Pods/gRPC-C++/include/grpcpp/impl/grpc_library.h:    if (grpc::g_glip == nullptr) {
Pods/gRPC-C++/include/grpcpp/impl/grpc_library.h:      grpc::g_glip = g_gli;
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:extern GrpcLibraryInterface* g_glip;
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      GPR_CODEGEN_ASSERT(g_glip &&
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      g_glip->init();
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      GPR_CODEGEN_ASSERT(g_glip &&
Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h:      g_glip->shutdown();
Pods/gRPC-C++/src/cpp/codegen/codegen_init.cc:grpc::GrpcLibraryInterface* grpc::g_glip;
```

**Comment by dconeybe** [comment]
@ondrejkorol Thanks for posting your Podfile.lock and the output from that grep command. I don't see anything unusual from the information that you've provided. Unfortunately, I don't have any other ideas of how to proceed. My gut instinct is that grpc's initialization logic of `g_glip` contains some undefined behavior, but I can't identify it. 

I _do_ have one idea, but it's a long shot. If I were to provide you with a patch for grpc, would you be able to build your app and publish it to the app store with that patch applied to grpc in the Pods directory?

**Comment by dconeybe** [comment]
Here is the patch: https://gist.github.com/dconeybe/31892c1d5c6b1c7d366947a46ee0207a

This patch potentially fixes an issue with the static initialization of `g_glip` in grpc. But since I cannot reproduce the crash I cannot test it out for myself.

Here is how you would use it:
1. Run `pod update` or `pod install` on your project; this will create the `Pods` directory.
2. Run `patch -Np0 -i grpc.patch.txt`

After running the "patch" command you should see output like this, which indicates success:
```
patching file Pods/gRPC-C++/include/grpcpp/impl/codegen/call_op_set.h
patching file Pods/gRPC-C++/include/grpcpp/impl/codegen/completion_queue.h
patching file Pods/gRPC-C++/include/grpcpp/impl/codegen/core_codegen_interface.h
patching file Pods/gRPC-C++/include/grpcpp/impl/codegen/grpc_library.h
patching file Pods/gRPC-C++/include/grpcpp/impl/codegen/server_context.h
patching file Pods/gRPC-C++/include/grpcpp/impl/codegen/server_interface.h
patching file Pods/gRPC-C++/include/grpcpp/impl/grpc_library.h
patching file Pods/gRPC-C++/src/cpp/codegen/codegen_init.cc
```

Now build your project in xcode and publish it to the app store. Make sure that the build you publish to the app store has this patch applied to grpc. Once published, see if the crash reports continue or cease.

**Comment by ondrejkorol** [comment]
Oh wow! Thank you! I'm going to include this patch in the next release! And I'll let you know whether crash reports continue or cease.
Once again, thank you so much, I truly appreciate it!
